import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import test from "node:test";
import { pathToFileURL } from "node:url";

import PizZip from "pizzip";

const repoRoot = resolve(import.meta.dirname, "..");
const modulePath = join(
  repoRoot,
  "scripts",
  "form-refinement",
  "normalized-contract-refinement.mjs",
);
const contractsDir = join(repoRoot, "docs", "audit", "docx", "contracts");

const EXPECTED_FIELDS = Object.freeze({
  "BM-005": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "sourceVerification.requestRoundText",
    "sourceVerification.procedureArticlesLine",
    "sourceVerification.reasonLine",
    "sourceVerification.requestedAuthorityLine",
    "sourceVerification.issue1Line",
    "sourceVerification.issue2Line",
    "sourceVerification.issue3Line",
    "sourceVerification.additionalIssuesLine",
    "sourceVerification.resultSubmissionLine",
    "recipients.investigatingAgencyLine",
    "recipients.archiveLine",
    "signature.signerName",
  ],
  "BM-006": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "sourceRequest.reasonLine",
    "sourceRequest.receiverName",
    "sourceRequest.actionLine",
    "sourceRequest.caseSummary",
    "sourceRequest.actionResultLine",
    "agency.bodyName",
    "recipients.primaryLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-007": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "legalBasis.procedureArticlesLine",
    "sourceMaterialRequest.reasonLine",
    "sourceMaterialRequest.article1Line",
    "sourceMaterialRequest.documentItem1Line",
    "sourceMaterialRequest.documentItem2Line",
    "sourceMaterialRequest.documentItem3Line",
    "sourceMaterialRequest.additionalDocumentItemsLine",
    "sourceMaterialRequest.deadlineLine",
    "recipients.primaryLine",
    "recipients.archiveLine",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-008": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "sourceTransfer.caseSummary",
    "sourceTransfer.reasonLine",
    "sourceTransfer.senderName",
    "sourceTransfer.receiverName",
    "agency.bodyName",
    "recipients.primaryLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-009": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "sourceResolutionExtension.procedureArticlesLine",
    "sourceResolutionExtension.receptionLegalBasisLine",
    "sourceResolutionExtension.proposalLegalBasisLine",
    "sourceResolutionExtension.reasonLine",
    "sourceResolutionExtension.article1Line",
    "sourceResolutionExtension.article2Line",
    "sourceResolutionExtension.requestingAgencyRecipientLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-010": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "sourceSuspension.reasonLine",
    "sourceSuspension.caseSummary",
    "agency.bodyName",
    "sourceSuspension.receivedDateLine",
    "sourceSuspension.article2Line",
    "sourceSuspension.article3Line",
    "recipients.primaryLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-011": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "legalBasis.procedureArticlesLine",
    "sourceSuspensionCancellation.considerationLine",
    "sourceSuspensionCancellation.article1Line",
    "sourceSuspensionCancellation.article2Line",
    "recipients.primaryLine",
    "recipients.sourceProviderLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-012": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "sourceRecovery.reasonLine",
    "sourceRecovery.suspensionDecisionCode",
    "sourceRecovery.suspensionDecisionIssueDateLine",
    "sourceRecovery.suspensionDecisionIssuedBy",
    "sourceRecovery.caseSummary",
    "recipients.primaryLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-014": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "legalBasis.procedureArticlesLine",
    "sourceDirectInspection.article1Line",
    "sourceDirectInspection.teamLeaderLine",
    "sourceDirectInspection.member1Line",
    "sourceDirectInspection.member2Line",
    "sourceDirectInspection.additionalMembersLine",
    "sourceDirectInspection.article3Line",
    "sourceDirectInspection.article4Line",
    "recipients.primaryLine",
    "recipients.teamMembersLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-015": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "sourceDirectInspectionPlan.attachedDecisionLine",
    "sourceDirectInspectionPlan.purposeLine1",
    "sourceDirectInspectionPlan.purposeLine2",
    "sourceDirectInspectionPlan.purposeLine3",
    "sourceDirectInspectionPlan.receivedStatsBlock",
    "sourceDirectInspectionPlan.resolvedStatsBlock",
    "sourceDirectInspectionPlan.prosecutionDecisionStatsLine",
    "sourceDirectInspectionPlan.nonProsecutionDecisionStatsLine",
    "sourceDirectInspectionPlan.transferredStatsLine",
    "sourceDirectInspectionPlan.pendingStatsLine",
    "sourceDirectInspectionPlan.suspendedStatsLine",
    "sourceDirectInspectionPlan.advantagesLine",
    "sourceDirectInspectionPlan.limitationsLine",
    "sourceDirectInspectionPlan.recommendationsLine",
    "sourceDirectInspectionPlan.inspectionTimeLine",
    "sourceDirectInspectionPlan.dataPeriodLine",
    "sourceDirectInspectionPlan.methodsBlock",
    "sourceDirectInspectionPlan.requestPreparationLine",
    "recipients.primaryLine",
    "recipients.teamMembersLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-016": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "legalBasis.procedureArticlesLine",
    "sourceDirectInspectionConclusion.implementationDecisionLine",
    "sourceDirectInspectionConclusion.receivedTotalLine",
    "sourceDirectInspectionConclusion.receivedDenunciationLine",
    "sourceDirectInspectionConclusion.receivedCrimeReportLine",
    "sourceDirectInspectionConclusion.receivedProsecutionRequestLine",
    "sourceDirectInspectionConclusion.receivedDirectDiscoveryLine",
    "sourceDirectInspectionConclusion.receivedSelfSurrenderLine",
    "sourceDirectInspectionConclusion.receivedOtherLine",
    "sourceDirectInspectionConclusion.resolvedStatsBlock",
    "sourceDirectInspectionConclusion.prosecutionDecisionStatsLine",
    "sourceDirectInspectionConclusion.nonProsecutionDecisionStatsLine",
    "sourceDirectInspectionConclusion.transferredStatsLine",
    "sourceDirectInspectionConclusion.pendingStatsLine",
    "sourceDirectInspectionConclusion.suspendedStatsLine",
    "sourceDirectInspectionConclusion.advantagesLine",
    "sourceDirectInspectionConclusion.violationsLine",
    "sourceDirectInspectionConclusion.violationReasonsLine",
    "sourceDirectInspectionConclusion.recommendationsBlock",
    "sourceDirectInspectionConclusion.implementationRequestLine",
    "recipients.primaryLine",
    "recipients.teamMembersLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-017": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "caseInitiationRequest.procedureArticlesLine",
    "caseInitiationRequest.assessmentLine",
    "caseInitiationRequest.article1Line",
    "caseInitiationRequest.article2Line",
    "caseInitiationRequest.investigationAuthorityRecipientLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-018": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "legalBasis.procedureArticlesLine",
    "caseInitiationChangeRequest.considerationLine",
    "caseInitiationChangeRequest.currentOffenseLegalLine",
    "caseInitiationChangeRequest.changeGroundLine",
    "caseInitiationChangeRequest.newOffenseLegalLine",
    "caseInitiationChangeRequest.requestAuthorityLine",
    "caseInitiationChangeRequest.requestChangeDecisionLine",
    "recipients.primaryLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-023": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "legalBasis.procedureArticlesLine",
    "crimeReport.content",
    "case.caseTitle",
    "offense.offenseName",
    "offense.legalArticle",
    "investigation.article2Line",
    "recipients.investigationUnitLine",
    "recipients.superiorProcuracyLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-030": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "recipients.primaryLine",
    "legalBasis.procedureArticlesLine",
    "sourceResolutionNotice.agencyActionLine",
    "sourceResolutionNotice.noticeRecipientLine",
    "sourceResolutionNotice.sourceInfoLine",
    "sourceResolutionNotice.resolutionResultLine",
    "recipients.copyLine",
    "recipients.archiveLine",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-031": [
    "agency.parentName",
    "agency.name",
    "document.documentCodeLine",
    "document.issuePlaceAndDateLine",
    "agency.bodyName",
    "legalBasis.juvenileLegalBasisLine",
    "legalBasis.requestApprovalLine",
    "measure.reasonLine",
    "measure.article1Line",
    "measure.article2Line",
    "recipients.investigationUnitLine",
    "recipients.personLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-033": [
    "agency.parentNameUpper",
    "agency.nameUpper",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "custody.extensionAttemptText",
    "official.issuingAuthorityLine",
    "legalBasis.procedureArticlesLine",
    "legalBasis.juvenileJusticeLine",
    "custody.detentionDecisionLine",
    "custody.previousExtensionDecisionLine",
    "custody.approvalProposalLine",
    "custody.approvalProposalAgencyLine",
    "custody.approvalReasonLine",
    "custody.approvalArticle1Line",
    "custody.executionRequestLine",
    "recipients.executionAgencyLine",
    "recipients.personLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-156": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "legalBasis.procedureArticlesLine",
    "caseDecision.prosecutionDecisionLegalBasisLine",
    "accusedDecision.prosecutionDecisionLegalBasisLine",
    "caseJoinder.legalBasisLine",
    "caseRecovery.legalBasisLine",
    "investigationConclusion.legalBasisLine",
    "indictment.criminalActDescriptionLine",
    "indictment.aggravatingMitigatingAnalysisLine",
    "indictment.evidenceHandlingLine",
    "indictment.civilLiabilityLine",
    "indictment.otherFactsLine",
    "indictment.summaryConclusionLine",
    "indictment.absentAccusedNoteLine",
    "indictment.defendantIdentityLine",
    "indictment.familyBackgroundLine",
    "indictment.specialStatusLine",
    "indictment.administrativeViolationLine",
    "indictment.criminalRecordLine",
    "indictment.preventiveMeasureLine",
    "indictment.crimeConclusionLine",
    "indictment.aggravatingMitigatingLine",
    "indictment.separatedCaseHandlingLine",
    "indictment.article1Line",
    "indictment.replacementLine",
    "indictment.caseFileLine",
    "indictment.evidenceListLine",
    "indictment.summonedPersonsLine",
    "recipients.courtLine",
    "recipients.accusedLine",
    "recipients.defenseCounselLine",
    "recipients.investigatingAgencyLine",
    "recipients.otherRecipientLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-039": [
    "agency.parentNameUpper",
    "agency.nameUpper",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuingAuthorityLine",
    "legalBasis.procedureArticlesLine",
    "legalBasis.juvenileJusticeLine",
    "detentionArrest.caseDecisionLegalBasisLine",
    "detentionArrest.accusedDecisionLegalBasisLine",
    "detentionArrest.reasonLine",
    "detentionArrest.accusedName",
    "detentionArrest.genderLabel",
    "detentionArrest.otherName",
    "detentionArrest.birthDay",
    "detentionArrest.birthMonth",
    "detentionArrest.birthYear",
    "detentionArrest.placeOfBirth",
    "detentionArrest.nationality",
    "detentionArrest.ethnicity",
    "detentionArrest.religion",
    "detentionArrest.occupation",
    "detentionArrest.identityNo",
    "detentionArrest.identityIssuedDay",
    "detentionArrest.identityIssuedMonth",
    "detentionArrest.identityIssuedYear",
    "detentionArrest.identityIssuedPlace",
    "detentionArrest.permanentAddress",
    "detentionArrest.temporaryAddress",
    "detentionArrest.currentAddress",
    "detentionArrest.detentionDurationText",
    "detentionArrest.detentionToDateLine",
    "detentionArrest.detentionExecutionUnitName",
    "detentionArrest.detentionFacilityName",
    "recipients.executionAgencyLine",
    "recipients.detentionFacilityLine",
    "recipients.personLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-059": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "legalBasis.procedureArticlesLine",
    "legalBasis.juvenileJusticeLine",
    "caseDecision.legalBasisLine",
    "accusedDecision.legalBasisLine",
    "measure.detentionOrderLegalBasisLine",
    "measure.prosecutionExtensionDecisionLegalBasisLine",
    "measure.detentionExtensionReasonLine",
    "measure.detentionExtensionArticle1Line",
    "person.fullName",
    "person.genderLabel",
    "person.otherName",
    "person.birthDay",
    "person.birthMonth",
    "person.birthYear",
    "person.placeOfBirth",
    "person.nationality",
    "person.ethnicity",
    "person.religion",
    "person.occupation",
    "person.identityDocumentLine",
    "person.permanentAddress",
    "person.temporaryAddress",
    "person.currentAddress",
    "measure.detentionExtensionDurationText",
    "measure.detentionExtensionFromDateText",
    "measure.detentionExtensionToDateText",
    "measure.detentionExtensionArticle2Line",
    "recipients.personLine",
    "recipients.detentionExecutionUnitLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
    "delivery.deliveredAtText",
    "delivery.receiverTitle",
  ],
  "BM-058": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "legalBasis.procedureArticlesLine",
    "legalBasis.juvenileJusticeLine",
    "caseDecision.legalBasisLine",
    "accusedDecision.legalBasisLine",
    "measure.detentionReasonLine",
    "measure.detentionArticle1Line",
    "person.fullName",
    "person.genderLabel",
    "person.otherName",
    "person.dateOfBirthText",
    "person.placeOfBirth",
    "person.nationality",
    "person.ethnicity",
    "person.religion",
    "person.occupation",
    "person.identityDocumentLine",
    "person.permanentAddress",
    "person.temporaryAddress",
    "person.currentAddress",
    "measure.exitPostponementDurationText",
    "measure.exitPostponementFromDateText",
    "measure.exitPostponementToDateText",
    "measure.detentionArticle2Line",
    "recipients.personLine",
    "recipients.detentionExecutionUnitLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
    "delivery.deliveredAtText",
    "delivery.receiverTitle",
  ],
  "BM-047": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "legalBasis.procedureArticlesLine",
    "legalBasis.juvenileJusticeLine",
    "guaranteeApproval.caseInitiationLine",
    "guaranteeApproval.defendantInitiationLine",
    "guaranteeApproval.sufficientGroundsLine",
    "guaranteeApproval.assignmentLine",
    "defendant.fullName",
    "defendant.gender",
    "defendant.aliasName",
    "defendant.birthDateLine",
    "defendant.birthPlace",
    "defendant.nationality",
    "defendant.ethnicity",
    "defendant.religion",
    "defendant.occupation",
    "defendant.identityNumber",
    "defendant.identityIssueDateLine",
    "defendant.identityIssuePlace",
    "defendant.permanentResidence",
    "defendant.temporaryResidence",
    "defendant.currentResidence",
    "guaranteeApproval.guaranteePeriodLine",
    "guaranteeApproval.article2Line",
    "recipients.defendantLine",
    "recipients.guarantorLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-053": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "legalBasis.line1",
    "legalBasis.line2",
    "legalBasis.line3",
    "legalBasis.line4",
    "legalBasis.line5",
    "person.fullName",
    "person.genderLabel",
    "person.otherName",
    "person.dateOfBirthText",
    "person.placeOfBirth",
    "person.nationality",
    "person.ethnicity",
    "person.religion",
    "person.occupation",
    "person.identityDocumentLine",
    "person.permanentAddress",
    "person.temporaryAddress",
    "person.currentAddress",
    "measure.article2Line",
    "monitoring.unitName",
    "monitoring.article3Line",
    "recipients.monitoringUnitLine",
    "recipients.personLine",
    "recipients.archiveLine",
    "recipients.noteLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
    "delivery.deliveredAtText",
    "delivery.receiverTitle",
  ],
  "BM-171": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "legalBasis.procedureArticlesLine",
    "caseDecision.prosecutionDecisionLegalBasisLine",
    "accusedDecision.prosecutionDecisionLegalBasisLine",
    "assetReturn.investigationConclusionLegalBasisLine",
    "assetReturn.caseSuspensionDecisionLegalBasisLine",
    "assetReturn.accusedSuspensionDecisionLegalBasisLine",
    "assetReturn.considerationLine",
    "assetReturn.assetListLine",
    "assetOwner.fullName",
    "assetOwner.genderText",
    "assetOwner.otherName",
    "assetOwner.dateOfBirthText",
    "assetOwner.placeOfBirth",
    "assetOwner.nationality",
    "assetOwner.ethnicity",
    "assetOwner.religion",
    "assetOwner.occupation",
    "assetOwner.identityNo",
    "assetOwner.identityIssuedDateText",
    "assetOwner.identityIssuedPlace",
    "assetOwner.permanentResidence",
    "assetOwner.temporaryResidence",
    "assetOwner.currentResidence",
    "assetReturn.executionRequestLine",
    "recipients.line1",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-172": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "legalBasis.procedureArticlesLine",
    "propertyReturnCancellation.caseInitiationLine",
    "propertyReturnCancellation.defendantInitiationLine",
    "propertyReturnCancellation.propertyReturnDecisionReviewLine",
    "propertyReturnCancellation.unlawfulReasonLine",
    "propertyReturnCancellation.article1Line",
    "propertyReturnCancellation.article2Line",
    "propertyReturnCancellation.article3RequestLine",
    "propertyRecipient.gender",
    "propertyRecipient.aliasName",
    "propertyRecipient.birthDateLine",
    "propertyRecipient.birthPlace",
    "propertyRecipient.nationality",
    "propertyRecipient.ethnicity",
    "propertyRecipient.religion",
    "propertyRecipient.occupation",
    "propertyRecipient.identityNumber",
    "propertyRecipient.identityIssueDateLine",
    "propertyRecipient.identityIssuePlace",
    "propertyRecipient.permanentResidence",
    "propertyRecipient.temporaryResidence",
    "propertyRecipient.currentResidence",
    "propertyReturnCancellation.article3ExecutionLine",
    "recipients.primaryLine",
    "recipients.propertyRecipientLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-055": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "measure.preventiveMeasureOrderLegalBasisLine",
    "accusedDecision.legalBasisLine",
    "measure.cancelReasonLine",
    "measure.cancellationArticle1Line",
    "person.fullName",
    "person.genderLabel",
    "person.otherName",
    "person.dateOfBirthText",
    "person.placeOfBirth",
    "person.nationality",
    "person.ethnicity",
    "person.religion",
    "person.occupation",
    "person.identityDocumentLine",
    "person.permanentAddress",
    "person.temporaryAddress",
    "person.currentAddress",
    "offense.offenseName",
    "offense.legalArticle",
    "offense.criminalCodeText",
    "measure.cancellationArticle2Line",
    "recipients.investigationUnitLine",
    "recipients.monitoringUnitLine",
    "recipients.personLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-097": [
    "agency.parentName",
    "agency.name",
    "document.fullDocumentCode",
    "document.issuePlaceDateLine",
    "official.issuerTitle",
    "legalBasis.procedureArticlesLine",
    "legalBasis.juvenileJusticeLine",
    "caseDecision.legalBasisLine",
    "accusedDecision.sufficientGroundsLine",
    "person.fullName",
    "person.genderLabel",
    "person.otherName",
    "person.birthInfoLine",
    "person.nationality",
    "person.ethnicity",
    "person.religion",
    "person.occupation",
    "person.identityDocumentLine",
    "person.permanentAddress",
    "person.temporaryAddress",
    "person.currentAddress",
    "person.criminalRecordLine",
    "offense.actDescriptionLine",
    "accusedDecision.article1Line",
    "accusedDecision.article2Line",
    "recipients.personLine",
    "recipients.investigationUnitLine",
    "recipients.archiveLine",
    "recipients.noteLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-145": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "prosecutionSupplementReturn.returnRoundLine",
    "official.issuerTitle",
    "prosecutionSupplementReturn.procedureArticlesLine",
    "prosecutionSupplementReturn.investigationConclusionLegalBasisLine",
    "prosecutionSupplementReturn.courtReturnDecisionLegalBasisLine",
    "prosecutionSupplementReturn.reasonLine",
    "prosecutionSupplementReturn.article1IntroLine",
    "prosecutionSupplementReturn.supplementIssue1Line",
    "prosecutionSupplementReturn.supplementIssue2Line",
    "prosecutionSupplementReturn.supplementIssue3Line",
    "prosecutionSupplementReturn.article2Line",
    "prosecutionSupplementReturn.article3Line",
    "prosecutionSupplementReturn.investigationAuthorityRecipientLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-146": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "prosecutionCaseSuspension.procedureArticlesLine",
    "prosecutionCaseSuspension.caseDecisionLegalBasisLine",
    "prosecutionCaseSuspension.reasonLine",
    "prosecutionCaseSuspension.article1Line",
    "prosecutionCaseSuspension.article2Line",
    "prosecutionCaseSuspension.article3Line",
    "prosecutionCaseSuspension.article4Line",
    "prosecutionCaseSuspension.investigationAuthorityRecipientLine",
    "recipients.otherRecipientsLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-057": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "measure.exitPostponementDecisionLegalBasisLine",
    "measure.exitPostponementCancelReasonLine",
    "person.fullName",
    "person.genderLabel",
    "person.otherName",
    "person.dateOfBirthText",
    "person.placeOfBirth",
    "person.nationality",
    "person.ethnicity",
    "person.religion",
    "person.occupation",
    "person.identityDocumentLine",
    "person.permanentAddress",
    "person.temporaryAddress",
    "person.currentAddress",
    "measure.immigrationAgencyName",
    "recipients.immigrationUnitLine",
    "recipients.personLine",
    "recipients.investigationUnitLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-169": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "legalBasis.procedureArticlesLine",
    "caseDecision.prosecutionDecisionLegalBasisLine",
    "accusedDecision.prosecutionDecisionLegalBasisLine",
    "evidenceHandling.investigationConclusionLegalBasisLine",
    "evidenceHandling.caseSuspensionDecisionLegalBasisLine",
    "evidenceHandling.accusedSuspensionDecisionLegalBasisLine",
    "evidenceHandling.considerationLine",
    "evidenceHandling.evidenceListLine",
    "evidenceHandling.handlingMethodLine",
    "evidenceHandling.executionRequestLine",
    "recipients.line1",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-148": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "legalBasis.procedureArticlesLine",
    "legalBasis.juvenileJusticeLine",
    "caseDecision.prosecutionDecisionLegalBasisLine",
    "accusedDecision.prosecutionDecisionLegalBasisLine",
    "suspension.reasonLine",
    "suspension.article1Line",
    "person.fullName",
    "person.genderText",
    "person.otherName",
    "person.birthDateLine",
    "person.nationalityEthnicityReligionLine",
    "person.occupation",
    "person.identityNo",
    "person.identityIssueLine",
    "person.permanentResidence",
    "person.temporaryResidence",
    "person.currentResidence",
    "suspension.article2ActionLine",
    "suspension.executionRequestLine",
    "recipients.line1",
    "recipients.line2",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-056": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "measure.exitPostponementReasonLine",
    "person.fullName",
    "person.genderLabel",
    "person.otherName",
    "person.dateOfBirthText",
    "person.placeOfBirth",
    "person.nationality",
    "person.ethnicity",
    "person.religion",
    "person.occupation",
    "person.identityDocumentLine",
    "person.permanentAddress",
    "person.temporaryAddress",
    "person.currentAddress",
    "measure.exitPostponementDurationText",
    "measure.exitPostponementFromDateText",
    "measure.exitPostponementToDateText",
    "measure.exitPostponementArticle2Line",
    "recipients.personLine",
    "recipients.immigrationUnitLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-085": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "caseInvestigationTransfer.procedureArticlesLine",
    "caseInvestigationTransfer.reasonLine",
    "caseInvestigationTransfer.article1Line",
    "caseInvestigationTransfer.article2Line",
    "caseInvestigationTransfer.fromInvestigationAuthorityRecipientLine",
    "caseInvestigationTransfer.toInvestigationAuthorityRecipientLine",
    "caseInvestigationTransfer.toProcuracyRecipientLine",
    "caseInvestigationTransfer.accusedOrRepresentativeRecipientLine",
    "caseInvestigationTransfer.defenderRecipientLine",
    "caseInvestigationTransfer.otherParticipantRecipientLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-173": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "legalBasis.procedureArticlesLine",
    "evidenceTransfer.prosecutionDecisionLegalBasisLine",
    "evidenceTransfer.considerationLine",
    "evidenceTransfer.article1Line",
    "evidenceTransfer.article2Line",
    "recipients.line1",
    "recipients.line2",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-159": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "legalBasis.procedureArticlesLine",
    "subordinateProcuracyTrialAssignment.indictmentLine",
    "subordinateProcuracyTrialAssignment.article1Line",
    "subordinateProcuracyTrialAssignment.article2Line",
    "recipients.assignedProcuracyLine",
    "recipients.courtLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-054": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "monitoring.unitName",
    "agency.nameBody",
    "person.fullName",
    "person.genderLabel",
    "person.otherName",
    "person.dateOfBirthText",
    "person.placeOfBirth",
    "person.nationality",
    "person.ethnicity",
    "person.religion",
    "person.occupation",
    "person.identityDocumentLine",
    "person.permanentAddress",
    "person.temporaryAddress",
    "person.currentAddress",
    "offense.offenseName",
    "offense.legalArticle",
    "offense.criminalCodeText",
    "notification.preventiveMeasureOrderLine",
    "monitoring.article3Line",
    "recipients.personLine",
    "recipients.archiveLine",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-038": [
    "agency.parentNameUpper",
    "agency.nameUpper",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuingAuthorityLine",
    "legalBasis.procedureArticlesLine",
    "legalBasis.juvenileJusticeLine",
    "arrestNonApproval.caseDecisionLegalBasisLine",
    "arrestNonApproval.accusedDecisionLegalBasisLine",
    "arrestNonApproval.proposalLine",
    "arrestNonApproval.proposalAgencyLine",
    "arrestNonApproval.reasonLine",
    "arrestNonApproval.article1Line",
    "arrestNonApproval.article2Line",
    "recipients.executionAgencyLine",
    "recipients.personLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-040": [
    "agency.parentName",
    "agency.name",
    "document.documentCodeLine",
    "document.issuePlaceAndDateLine",
    "agency.bodyName",
    "legalBasis.baseProcedureLine",
    "legalBasis.juvenileLegalBasisLine",
    "caseDecision.legalBasisLine",
    "accusedDecision.legalBasisLine",
    "legalBasis.requestApprovalLine",
    "measure.reasonLine",
    "measure.article1Line",
    "measure.detentionDurationLine",
    "measure.article2Line",
    "recipients.detentionExecutionUnitLine",
    "recipients.personLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-042": [
    "agency.parentName",
    "agency.name",
    "document.documentCodeLine",
    "document.issuePlaceAndDateLine",
    "measure.extensionRoundText",
    "official.issuerTitle",
    "legalBasis.baseProcedureLine",
    "legalBasis.juvenileLegalBasisLine",
    "measure.detentionOrderLegalBasisLine",
    "measure.previousExtensionDecisionLegalBasisLine",
    "legalBasis.requestExtensionLine",
    "measure.reasonLine",
    "measure.article1Line",
    "measure.article2Line",
    "measure.article3Line",
    "recipients.superiorProcuracyLine",
    "recipients.investigationUnitLine",
    "recipients.personLine",
    "recipients.detentionFacilityLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-037": [
    "agency.parentName",
    "agency.name",
    "document.documentCodeLine",
    "document.issuePlaceAndDateLine",
    "agency.bodyName",
    "legalBasis.juvenileLegalBasisLine",
    "caseDecision.legalBasisLine",
    "accusedDecision.legalBasisLine",
    "legalBasis.requestApprovalLine",
    "measure.reasonLine",
    "measure.article1Line",
    "measure.detentionDurationLine",
    "measure.article2Line",
    "recipients.investigationUnitLine",
    "recipients.personLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-043": [
    "agency.parentName",
    "agency.name",
    "document.documentCodeLine",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "legalBasis.baseProcedureLine",
    "legalBasis.juvenileLegalBasisLine",
    "measure.detentionOrderLegalBasisLine",
    "measure.previousExtensionDecisionLegalBasisLine",
    "measure.cancelReasonLine",
    "measure.article1Line",
    "measure.article2Line",
    "measure.article3Line",
    "recipients.detentionExecutionUnitLine",
    "recipients.personLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-141": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "prosecutionTransfer.procedureArticlesLine",
    "prosecutionTransfer.caseDecisionLegalBasisLine",
    "prosecutionTransfer.accusedDecisionLegalBasisLine",
    "prosecutionTransfer.investigationConclusionLegalBasisLine",
    "prosecutionTransfer.transferReasonLine",
    "prosecutionTransfer.article1Line",
    "recipients.investigatingAgencyLine",
    "recipients.accusedLine",
    "prosecutionTransfer.toProcuracyRecipientLine",
    "prosecutionTransfer.detentionFacilityRecipientLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-070": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "legalBasis.assignmentProcedureArticlesLine",
    "caseDecision.caseProsecutionDecisionLine",
    "assignment.deputyChiefName",
    "assignment.deputyChiefTitle",
    "assignment.deputyChiefAgencyName",
    "assignment.responsibilityLine",
    "recipients.investigationAuthorityLine",
    "recipients.assignedPersonLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-144": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "prosecutionExtension.procedureArticlesLine",
    "prosecutionExtension.caseDecisionLegalBasisLine",
    "prosecutionExtension.accusedDecisionLegalBasisLine",
    "prosecutionExtension.investigationConclusionLegalBasisLine",
    "prosecutionExtension.reasonLine",
    "prosecutionExtension.article1Line",
    "recipients.investigatingAgencyLine",
    "recipients.accusedLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-166": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "legalBasis.procedureArticlesLine",
    "returnInvestigation.courtDecisionLegalBasisLine",
    "returnInvestigation.article1Line",
    "returnInvestigation.article2Line",
    "recipients.line1",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-150": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "prosecutionCaseTermination.procedureArticlesLine",
    "prosecutionCaseTermination.caseDecisionLegalBasisLine",
    "prosecutionCaseTermination.accusedDecisionLegalBasisLine",
    "prosecutionCaseTermination.reasonLine",
    "prosecutionCaseTermination.article1Line",
    "prosecutionCaseTermination.article2Line",
    "prosecutionCaseTermination.article3Line",
    "prosecutionCaseTermination.article4Line",
    "prosecutionCaseTermination.superiorProcuracyRecipientLine",
    "recipients.otherRecipientsLine",
    "prosecutionCaseTermination.accusedOrRepresentativeRecipientLine",
    "prosecutionCaseTermination.investigationAuthorityRecipientLine",
    "prosecutionCaseTermination.defenseCounselRecipientLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-103": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "recipients.superiorProcuracyName",
    "legalBasis.procedureArticlesLine",
    "caseDecision.prosecutionDecisionLegalBasisLine",
    "investigationExtension.previousDecisionLegalBasisLine",
    "proposal.requestingDocumentLine",
    "proposal.proposingProcuracyName",
    "investigationExtension.requestRoundText",
    "caseDecision.prosecutionDecisionSummaryLine",
    "investigationExtension.durationText",
    "investigationExtension.fromDateText",
    "investigationExtension.toDateText",
    "recipients.superiorProcuracyLine",
    "recipients.investigatingAgencyLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-045": [
    "agency.parentNameUpper",
    "agency.nameUpper",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuingAuthorityLine",
    "legalBasis.procedureArticlesLine",
    "legalBasis.juvenileJusticeLine",
    "bailApproval.caseDecisionLegalBasisLine",
    "bailApproval.accusedDecisionLegalBasisLine",
    "bailApproval.proposalLine",
    "bailApproval.reasonLine",
    "bailApproval.article1Line",
    "bailApproval.article2Line",
    "recipients.executionAgencyLine",
    "recipients.personRepresentativeLine",
    "recipients.bailReceiverLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-046": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "legalBasis.procedureArticlesLine",
    "legalBasis.juvenileJusticeLine",
    "guaranteeNonApproval.caseInitiationLine",
    "guaranteeNonApproval.defendantInitiationLine",
    "guaranteeNonApproval.proposalReviewLine",
    "guaranteeNonApproval.insufficientGroundsLine",
    "guaranteeNonApproval.article1Line",
    "guaranteeNonApproval.article2Line",
    "recipients.investigationAuthorityLine",
    "recipients.defendantRepresentativeLine",
    "recipients.guarantorLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-071": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "assignment.assignedRoleText",
    "official.issuerTitle",
    "legalBasis.staffAssignmentProcedureArticlesLine",
    "caseDecision.caseProsecutionDecisionLine",
    "assignment.assignedOfficerName",
    "assignment.assignedOfficerTitle",
    "assignment.assignedOfficerAgencyName",
    "assignment.additionalAssignedOfficersLine",
    "assignment.responsibilityLine",
    "recipients.investigationAuthorityLine",
    "recipients.assignedPersonLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-086": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "legalBasis.procedureArticlesLine",
    "legalBasis.jurisdictionCircularLine",
    "prosecutionJurisdictionTransfer.considerationLine",
    "prosecutionJurisdictionTransfer.article1Line",
    "prosecutionJurisdictionTransfer.article2Line",
    "recipients.sourceProcuracyLine",
    "recipients.targetProcuracyLine",
    "recipients.investigationAuthorityLine",
    "recipients.detentionFacilityLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-090": [
    "agency.parentName",
    "agency.name",
    "document.fullDocumentCode",
    "document.issuePlaceDateLine",
    "official.issuerTitle",
    "legalBasis.procedureArticlesLine",
    "legalBasis.juvenileJusticeLine",
    "caseDecision.legalBasisLine",
    "accusedDecision.requestLine",
    "approval.assessmentLine",
    "accusedDecision.approvalArticle1Line",
    "accusedDecision.investigationRequestLine",
    "recipients.investigationUnitLine",
    "recipients.personLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-170": [
    "agency.parentName",
    "agency.name",
    "document.documentCode",
    "document.issuePlaceAndDateLine",
    "official.issuerTitle",
    "legalBasis.procedureArticlesLine",
    "evidenceHandlingCancellation.caseInitiationLine",
    "evidenceHandlingCancellation.defendantInitiationLine",
    "evidenceHandlingCancellation.evidenceHandlingDecisionReviewLine",
    "evidenceHandlingCancellation.unlawfulReasonLine",
    "evidenceHandlingCancellation.article1Line",
    "evidenceHandlingCancellation.article2Line",
    "recipients.primaryLine",
    "recipients.archiveLine",
    "signature.signMode",
    "signature.positionTitle",
    "signature.signerName",
  ],
  "BM-168": [
    "agency.parentName",
    "agency.name",
    "caseFileHandover.startedAtLine",
    "caseFileHandover.giverName",
    "caseFileHandover.giverPositionTitle",
    "caseFileHandover.receiverName",
    "caseFileHandover.receiverPositionTitle",
    "caseFileHandover.caseFileTitle",
    "caseFileHandover.handoverReasonLine",
    "caseFileHandover.fileStatsLine",
    "caseFileHandover.evidenceLine",
    "caseFileHandover.endedAtLine",
    "caseFileHandover.receiverSignerName",
    "caseFileHandover.giverSignerName",
  ],
});

let refinement = null;
if (existsSync(modulePath)) {
  refinement = await import(pathToFileURL(modulePath));
}

function requireRefinement() {
  assert.ok(
    refinement,
    "normalized contract refinement module must exist before these tests can pass",
  );
  return refinement;
}

function loadContract(code) {
  const fileName = refinement.findContractFile(repoRoot, code);
  return JSON.parse(readFileSync(join(contractsDir, fileName), "utf8"));
}

test("normalized contract refinement module exists", () => {
  requireRefinement();
});

test("selected-code parsing is deterministic and rejects malformed codes", () => {
  const api = requireRefinement();
  assert.deepEqual(api.parseSelectedCodes(["--codes", "BM-010,BM-005 BM-010"]), [
    "BM-005",
    "BM-010",
  ]);
  assert.throws(
    () => api.parseSelectedCodes(["--codes", "BM-5"]),
    /Invalid BM code/u,
  );
});

test("contract preparation is a side-effect-free dry run", () => {
  const api = requireRefinement();
  const contractPath = join(contractsDir, api.findContractFile(repoRoot, "BM-005"));
  const before = readFileSync(contractPath, "utf8");
  const prepared = api.prepareContractRefinement(repoRoot, "BM-005");
  const after = readFileSync(contractPath, "utf8");

  assert.equal(prepared.code, "BM-005");
  assert.ok(prepared.original.canonicalFields.length > 0);
  assert.equal(prepared.refined.canonicalFields.length, 16);
  assert.equal(after, before);
});

test("refinement evidence markdown ends with exactly one newline", () => {
  const api = requireRefinement();
  const markdown = api.formatRefinementEvidenceMarkdown({
    codes: ["BM-011"],
    overallStatus: "PASS",
    results: [
      {
        code: "BM-011",
        status: "PASS",
        normalizedDocxPath:
          "storage/templates/normalized-docx/BM-011/BM-011_normalized.docx",
        normalizedDocxSha256: "abc123",
        fields: 15,
        bindings: 15,
        compile: { ok: true },
        packageIntegrity: { status: "pass" },
        unresolvedPlaceholders: [],
        missingSampleValues: [],
        literalLeakage: [],
      },
    ],
  });

  assert.match(markdown, /\n$/u);
  assert.doesNotMatch(markdown, /\n\n$/u);
});

test("normalized placeholder evidence contains visible Word text but not drawing coordinates", () => {
  const api = requireRefinement();
  const discovery = api.discoverNormalizedPlaceholders(repoRoot, "BM-031");
  const headerContext = discovery.occurrencesByPath.get("agency.parentName")?.[0]
    ?.context;

  assert.equal(headerContext, "{{agency.parentName}}");
  assert.doesNotMatch(
    [...discovery.occurrencesByPath.values()]
      .flat()
      .map((occurrence) => occurrence.context)
      .join("\n"),
    /735965|32385|813435|25400|3724275|349250/u,
  );
});

test("preview artifacts are persisted as complete DOCX packages with deterministic metadata", () => {
  const api = requireRefinement();
  assert.equal(typeof api.writeRefinementPreviewArtifact, "function");
  const profile = api.loadRefinementProfile(repoRoot, "BM-023");
  const preview = api.renderRefinementPreview({
    repoRoot,
    code: "BM-023",
    profile,
  });
  const outputRoot = mkdtempSync(join(tmpdir(), "qllaw-form-preview-"));

  try {
    const artifact = api.writeRefinementPreviewArtifact({
      repoRoot,
      outputRoot,
      batchName: "BM-023",
      code: "BM-023",
      renderedBuffer: preview.renderedBuffer,
    });
    const persisted = readFileSync(artifact.filePath);
    const zip = new PizZip(persisted);

    assert.equal(artifact.byteSize, persisted.length);
    assert.match(artifact.sha256, /^[a-f0-9]{64}$/u);
    assert.ok(artifact.relativePath.endsWith("/BM-023-preview.docx"));
    assert.ok(zip.file("word/document.xml"));
  } finally {
    rmSync(outputRoot, { recursive: true, force: true });
  }
});

test("every refinement profile uses a registered field taxonomy namespace", () => {
  const api = requireRefinement();
  const taxonomy = JSON.parse(
    readFileSync(join(repoRoot, "docs", "contracts", "field-taxonomy.json"), "utf8"),
  );
  const namespaces = new Set(Object.keys(taxonomy.namespaces));

  for (const code of Object.keys(EXPECTED_FIELDS)) {
    const profile = api.loadRefinementProfile(repoRoot, code);
    for (const path of Object.keys(profile.fields)) {
      assert.ok(
        namespaces.has(path.split(".")[0]),
        `${code} uses unregistered namespace in ${path}`,
      );
    }
  }
});

for (const [code, expectedFields] of Object.entries(EXPECTED_FIELDS)) {
  test(`${code} normalized DOCX placeholders exactly match its reviewed profile`, () => {
    const api = requireRefinement();
    const profile = api.loadRefinementProfile(repoRoot, code);
    const discovery = api.discoverNormalizedPlaceholders(repoRoot, code);

    assert.deepEqual(discovery.orderedPaths, expectedFields);
    assert.deepEqual(Object.keys(profile.fields), expectedFields);
    assert.deepEqual(api.validateProfileParity(profile, discovery), []);
  });

  test(`${code} builds a semantic review-required draft that compiles`, () => {
    const api = requireRefinement();
    const profile = api.loadRefinementProfile(repoRoot, code);
    const discovery = api.discoverNormalizedPlaceholders(repoRoot, code);
    const refined = api.buildRefinedContract({
      repoRoot,
      code,
      profile,
      discovery,
      contract: loadContract(code),
    });

    assert.equal(refined.status, "draft");
    assert.equal(refined.docxSlots.length, expectedFields.length);
    assert.equal(refined.canonicalFields.length, expectedFields.length);
    assert.equal(refined.renderBindings.length, expectedFields.length);
    assert.deepEqual(
      refined.canonicalFields.map((field) => field.path),
      expectedFields,
    );
    assert.deepEqual(
      refined.canonicalFields.filter((field) => field.source !== "unknown"),
      [],
    );
    assert.deepEqual(
      [
        ...refined.docxSlots,
        ...refined.canonicalFields,
        ...refined.renderBindings,
      ].filter((item) => item.reviewRequired !== true),
      [],
    );
    assert.deepEqual(
      refined.canonicalFields.filter((field) => /\.field\d+$/u.test(field.path)),
      [],
    );
    assert.equal(
      refined.warnings.some((warning) => warning.startsWith("Clx parse error:")),
      false,
      `${code} normalized-DOCX refinement must not retain an obsolete legacy .doc parser warning`,
    );
    assert.ok(
      refined.warnings.some((warning) =>
        warning.includes("human semantic/legal review is still required"),
      ),
      `${code} must retain the human-review warning`,
    );

    const requireFromContracts = createRequire(
      join(repoRoot, "packages", "form-contracts", "package.json"),
    );
    const { adaptV1Contract, compileContract } =
      requireFromContracts("@qllaw/form-contracts");
    const adapted = adaptV1Contract(refined);
    adapted.templateHash = discovery.sha256;
    adapted.normalizedDocxPath = discovery.relativePath;
    const compiled = compileContract(adapted);
    assert.equal(
      compiled.ok,
      true,
      compiled.issues.map((issue) => `${issue.code}:${issue.path}`).join(", "),
    );
  });

  test(`${code} sample preview resolves fields without damaging the DOCX package`, () => {
    const api = requireRefinement();
    const profile = api.loadRefinementProfile(repoRoot, code);
    const preview = api.renderRefinementPreview({ repoRoot, code, profile });

    assert.equal(preview.packageIntegrity.status, "pass");
    assert.deepEqual(preview.unresolvedPlaceholders, []);
    assert.deepEqual(preview.missingSampleValues, []);
    assert.deepEqual(preview.literalLeakage, []);
    assert.ok(preview.renderedBuffer.length > 0);
  });
}
