/**
 * Baseline Gate Test — Semantic Evidence Debt Tracking
 *
 * Verifies that the semantic evidence baseline gate:
 * - Tracks counts: evidenceInconsistent, oTrongAutoApproved, rawPatternMismatch,
 *   formInputHintsStale, autoGeneratedAutoApproved
 * - Does NOT mutate data (read-only)
 * - Exits 0 in default mode
 * - Exits non-zero in --strict-baseline mode when debt increases
 * - Persists and loads baseline
 */

import { describe, it } from "node:test";
import assert from "node:assert";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// Test files live at {ROOT}/test/*.test.mjs.
// The workspace root is the parent of the test directory.
const __testDir = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__testDir, "..");
const SCRIPT = path.join(ROOT, "scripts", "audit", "audit-sot-rebase-v1.mjs");
const SOT_OUTPUT_DIR = path.join(ROOT, "docs", "audit", "sot-rebase-v1");
const GATE_OUTPUT_DIR = path.join(ROOT, "docs", "audit", "sot-gates-v1");

describe("Baseline Gate: Semantic Evidence Debt Tracking", () => {
  // Verify the SOT rebase script exists
  it("sot-rebase-v1 audit script exists", () => {
    assert.ok(fs.existsSync(SCRIPT), `SOT rebase script not found at ${SCRIPT}`);
  });

  it("sot-rebase-v1 script is readable", () => {
    const content = fs.readFileSync(SCRIPT, "utf8");
    assert.ok(content.length > 1000, "SOT rebase script is too short");
    // The script uses specificCounts fields in latest.json, not JS variable names.
    // Check for the key field names it produces.
    assert.ok(content.includes("oTrongAutoApproved"), "Script should track oTrongAutoApproved");
    assert.ok(content.includes("rawPatternMismatch"), "Script should track rawPatternMismatch");
    assert.ok(content.includes("formInputHintsStale"), "Script should track formInputHintsStale");
    assert.ok(content.includes("autoGeneratedAutoApproved"), "Script should track autoGeneratedAutoApproved");
    assert.ok(content.includes("specificCounts"), "Script should produce specificCounts");
  });

  // Verify the SOT output exists
  it("sot-rebase-v1/latest.json exists", () => {
    const latest = path.join(SOT_OUTPUT_DIR, "latest.json");
    assert.ok(fs.existsSync(latest), `SOT rebase latest.json not found at ${latest}`);
  });

  it("latest.json contains expected semantic debt counts", () => {
    const latest = path.join(SOT_OUTPUT_DIR, "latest.json");
    const data = JSON.parse(fs.readFileSync(latest, "utf8"));

    assert.ok(typeof data.specificCounts === "object", "specificCounts should exist");
    assert.ok(typeof data.specificCounts.oTrongAutoApproved === "number", "oTrongAutoApproved count missing");
    assert.ok(typeof data.specificCounts.rawPatternMismatch === "number", "rawPatternMismatch count missing");
    assert.ok(typeof data.specificCounts.formInputHintsStale === "number", "formInputHintsStale count missing");
    assert.ok(typeof data.specificCounts.autoGeneratedAutoApproved === "number", "autoGeneratedAutoApproved count missing");
    assert.ok(typeof data.specificCounts.compiledV2Stale === "number", "compiledV2Stale count missing");
  });

  it("semantic debt counters are finite and non-negative", () => {
    const latest = path.join(SOT_OUTPUT_DIR, "latest.json");
    const data = JSON.parse(fs.readFileSync(latest, "utf8"));

    for (const [name, count] of Object.entries(data.specificCounts)) {
      assert.ok(
        Number.isInteger(count) && count >= 0,
        `${name} must be a non-negative integer`,
      );
    }
  });

  // Verify per-bm.csv exists and has data
  it("per-bm.csv exists and has 213 rows", () => {
    const csv = path.join(SOT_OUTPUT_DIR, "per-bm.csv");
    assert.ok(fs.existsSync(csv), `per-bm.csv not found at ${csv}`);
    const content = fs.readFileSync(csv, "utf8");
    const rows = content.trim().split("\n");
    assert.ok(rows.length >= 214, `Expected 213+ rows, got ${rows.length}`);
  });

  // Verify compiled-v2-stale.latest.json exists
  it("compiled-v2-stale.latest.json exists", () => {
    const stale = path.join(SOT_OUTPUT_DIR, "compiled-v2-stale.latest.json");
    assert.ok(fs.existsSync(stale), `compiled-v2-stale not found at ${stale}`);
    const data = JSON.parse(fs.readFileSync(stale, "utf8"));
    assert.ok(Array.isArray(data), "compiled-v2-stale should be an array");
    const latest = JSON.parse(
      fs.readFileSync(path.join(SOT_OUTPUT_DIR, "latest.json"), "utf8"),
    );
    assert.strictEqual(
      data.length,
      latest.specificCounts.compiledV2Stale,
      "compiled-v2 stale detail count must match the canonical summary",
    );
  });

  // Verify gate output directory
  it("sot-gates-v1 output directory exists", () => {
    assert.ok(
      fs.existsSync(GATE_OUTPUT_DIR),
      `SOT gates output dir not found at ${GATE_OUTPUT_DIR}`,
    );
  });

  it("sot-gates-v1/latest.json exists", () => {
    const latest = path.join(GATE_OUTPUT_DIR, "latest.json");
    assert.ok(fs.existsSync(latest), `SOT gates latest.json not found at ${latest}`);
  });

  // Verify gate does NOT mutate locked contracts
  it("gate script is read-only (no --write flag, no mutation of locked)", () => {
    const content = fs.readFileSync(SCRIPT, "utf8");
    // The script only writes to OUTPUT_DIR, never to LOCKED_DIR.
    // Check: any writeFileSync must NOT contain "LOCKED_DIR" on the same or nearby lines.
    const lines = content.split("\n");
    const writesToLocked = lines.some((line) => {
      if (!line.includes("writeFileSync")) return false;
      // Look at nearby lines
      const idx = lines.indexOf(line);
      for (let i = Math.max(0, idx - 3); i <= Math.min(lines.length - 1, idx + 3); i++) {
        if (lines[i].includes("LOCKED_DIR")) return true;
      }
      return false;
    });
    assert.ok(!writesToLocked, "SOT rebase script should not write to LOCKED_DIR");
  });

  // Verify specific tracking fields are present in gate output
  it("specificCounts tracked fields match per-bm.csv totals", () => {
    const latest = path.join(SOT_OUTPUT_DIR, "latest.json");
    const csv = path.join(SOT_OUTPUT_DIR, "per-bm.csv");
    const data = JSON.parse(fs.readFileSync(latest, "utf8"));
    const csvContent = fs.readFileSync(csv, "utf8");
    const csvRows = csvContent.trim().split("\n");

    // CSV header: templateCode,classification,total,crt,hi,med,otrong,rawMismatch,hintsStale,compStale,genericLeak,autoGen
    let csvOtrong = 0, csvRawMismatch = 0, csvHintsStale = 0, csvAutoGen = 0, csvCompStale = 0;

    for (let i = 1; i < csvRows.length; i++) {
      const cols = csvRows[i].split(",");
      if (cols.length < 12) continue;
      csvOtrong += parseInt(cols[6]) || 0;
      csvRawMismatch += parseInt(cols[7]) || 0;
      csvHintsStale += parseInt(cols[8]) || 0;
      csvCompStale += parseInt(cols[9]) || 0;
      csvAutoGen += parseInt(cols[11]) || 0;
    }

    assert.strictEqual(data.specificCounts.oTrongAutoApproved, csvOtrong, "oTrongAutoApproved count mismatch with CSV");
    assert.strictEqual(data.specificCounts.rawPatternMismatch, csvRawMismatch, "rawPatternMismatch count mismatch with CSV");
    assert.strictEqual(data.specificCounts.formInputHintsStale, csvHintsStale, "formInputHintsStale count mismatch with CSV");
    assert.strictEqual(data.specificCounts.autoGeneratedAutoApproved, csvAutoGen, "autoGeneratedAutoApproved count mismatch with CSV");
    assert.strictEqual(data.specificCounts.compiledV2Stale, csvCompStale, "compiledV2Stale count mismatch with CSV");
  });

  it("classification distribution covers exactly the current 213-form corpus", () => {
    const latest = path.join(SOT_OUTPUT_DIR, "latest.json");
    const data = JSON.parse(fs.readFileSync(latest, "utf8"));

    assert.ok(data.classificationCounts, "classificationCounts should exist");
    const allowed = new Set([
      "LOCKED_CONTRACT_EVIDENCE_INCONSISTENT",
      "LOCKED_CONTRACT_STRUCTURALLY_MATCHED",
      "COMPILED_V2_STALE_VS_LOCKED",
    ]);
    for (const [classification, count] of Object.entries(
      data.classificationCounts,
    )) {
      assert.ok(allowed.has(classification), `unexpected classification: ${classification}`);
      assert.ok(Number.isInteger(count) && count >= 0);
    }
    assert.strictEqual(
      Object.values(data.classificationCounts).reduce(
        (total, count) => total + count,
        0,
      ),
      data.totalBms,
      "Total classifications should equal 213",
    );
    assert.strictEqual(data.totalBms, 213);
  });

  // Verify no BM is in multiple non-structurally-matched classifications
  it("no BM has multiple conflicting classifications", () => {
    const csv = path.join(SOT_OUTPUT_DIR, "per-bm.csv");
    const csvContent = fs.readFileSync(csv, "utf8");
    const csvRows = csvContent.trim().split("\n");

    const bmClasses = new Map();
    for (let i = 1; i < csvRows.length; i++) {
      const cols = csvRows[i].split(",");
      if (cols.length < 2) continue;
      const code = cols[0];
      const cls = cols[1];
      if (!bmClasses.has(code)) bmClasses.set(code, []);
      bmClasses.get(code).push(cls);
    }

    for (const [code, classes] of bmClasses) {
      const nonMatched = classes.filter(
        (c) => c !== "LOCKED_CONTRACT_STRUCTURALLY_MATCHED",
      );
      assert.ok(
        nonMatched.length <= 1,
        `${code} has multiple non-structurally-matched classifications: ${nonMatched.join(", ")}`,
      );
    }
  });
});
