import json
import pathlib
import subprocess
import datetime

ROOT = pathlib.Path(r"d:\Study\Project\QLLaw-main")
OUT = ROOT / "docs" / "audit" / "final-213-customer-ready" / "release-integration"

ts = datetime.datetime.utcnow().isoformat() + "Z"

# Get current state
status_proc = subprocess.run(
    ["git", "status", "--short"],
    cwd=str(ROOT), capture_output=True, text=True, shell=True
)
status_lines = [l for l in status_proc.stdout.splitlines() if l.strip()]

# Categorize
untracked = [l for l in status_lines if l.startswith("??")]
modified = [l for l in status_lines if l.startswith(" M")]
deleted = [l for l in status_lines if l.startswith(" D")]

# What is mine
mine_untracked = [
    l[3:] for l in untracked
    if l[3:].startswith("scripts/local/")
    or l[3:].startswith("scripts/release/audit-")
    or l[3:].startswith("docs/CUSTOMER_LOCAL_")
    or l[3:].startswith("docs/LOCAL_RELEASE_NOTES.md")
    or l[3:].startswith("docs/audit/final-213-customer-ready/release-integration/")
    or l[3:].startswith("test/release-repository-hygiene.spec.mjs")
]

plan = {
    "phase": "Phase 14 — Commit Plan and Index Review",
    "executedAt": ts,
    "working_tree_status": {
        "total_lines": len(status_lines),
        "modified_count": len(modified),
        "deleted_count": len(deleted),
        "untracked_count": len(untracked),
    },
    "phase_15_authored_untracked_files": sorted(mine_untracked),
    "phase_15_authored_untracked_count": len(mine_untracked),
    "prior_phase_uncommitted_work": {
        "modified_files": len(modified),
        "untracked_files_other": len(untracked) - len(mine_untracked),
        "rationale": "Pre-existing dirty worktree from prior phases per safety rule 'Do NOT reset, clean, stash, stage, commit, push, or bulk-restore the worktree. The live dirty worktree is authoritative.'",
        "decision": "This phase DOES NOT commit prior-phase uncommitted work. Only Phase-15-authored files (audit scripts, scripts/local toolkit, customer docs, audit evidence, security overrides) are eligible for logical commits."
    },
    "commit_plan": [
        {
            "commit_index": 1,
            "type": "chore(repo)",
            "subject": "chore(repo): remove obsolete local artifacts and harden hygiene",
            "scope_files_intent": "scripts/release/_tmp_*.py (deleted during this phase), .gitignore hardening (if present in authored files). Note: most prior-phase cleanup already done in prior turns; this commit captures only net new hygiene additions.",
            "depends_on_existing_commits": True,
            "note": "Most cleanup from earlier turns is already in prior commits on the branch."
        },
        {
            "commit_index": 2,
            "type": "chore(security)",
            "subject": "chore(security): remediate customer-local dependency advisories",
            "scope_files_intent": [
                "package.json (added 5 pnpm.overrides: shell-quote@1.9.0, postcss@8.5.18, brace-expansion@5.0.8, form-data@4.0.6, next@16.2.11)",
                "pnpm-lock.yaml (regenerated by pnpm install --frozen-lockfile=false)",
                "docs/audit/final-213-customer-ready/release-integration/security-audit.json"
            ],
            "merge_gate_evidence": "critical=0, high=0 (verified by pnpm audit)"
        },
        {
            "commit_index": 3,
            "type": "feat(local)",
            "subject": "feat(local): add customer local operations toolkit",
            "scope_files_intent": [
                "scripts/local/doctor.ps1",
                "scripts/local/setup.ps1",
                "scripts/local/start.ps1",
                "scripts/local/stop.ps1",
                "scripts/local/status.ps1",
                "scripts/local/backup.ps1",
                "scripts/local/restore.ps1",
                "scripts/local/smoke.ps1",
                "scripts/release/audit-repository-hygiene.mjs",
                "test/release-repository-hygiene.spec.mjs"
            ]
        },
        {
            "commit_index": 4,
            "type": "docs(local)",
            "subject": "docs(local): add customer installation and operations handbook",
            "scope_files_intent": [
                "docs/CUSTOMER_LOCAL_INSTALLATION.md",
                "docs/CUSTOMER_LOCAL_OPERATIONS.md",
                "docs/CUSTOMER_LOCAL_BACKUP_RESTORE.md",
                "docs/CUSTOMER_LOCAL_TROUBLESHOOTING.md",
                "docs/CUSTOMER_LOCAL_ACCEPTANCE_CHECKLIST.md",
                "docs/CUSTOMER_LOCAL_DELIVERY_PLAN.md",
                "docs/LOCAL_RELEASE_NOTES.md"
            ]
        },
        {
            "commit_index": 5,
            "type": "chore(release)",
            "subject": "chore(release): finalize customer-ready local baseline",
            "scope_files_intent": [
                "docs/audit/final-213-customer-ready/release-integration/safety-snapshot.json",
                "docs/audit/final-213-customer-ready/release-integration/remote-reconciliation.json",
                "docs/audit/final-213-customer-ready/release-integration/worktree-inventory.json",
                "docs/audit/final-213-customer-ready/release-integration/worktree-inventory.md",
                "docs/audit/final-213-customer-ready/release-integration/cleanup-candidates.json",
                "docs/audit/final-213-customer-ready/release-integration/release-blockers.json",
                "docs/audit/final-213-customer-ready/release-integration/scratch-forensics.json",
                "docs/audit/final-213-customer-ready/release-integration/secret-audit.json",
                "docs/audit/final-213-customer-ready/release-integration/sensitive-data-audit.json",
                "docs/audit/final-213-customer-ready/release-integration/large-file-audit.json",
                "docs/audit/final-213-customer-ready/release-integration/cleanup-manifest-dry-run.json",
                "docs/audit/final-213-customer-ready/release-integration/cleanup-manifest-dry-run.md",
                "docs/audit/final-213-customer-ready/release-integration/cleanup-applied.json",
                "docs/audit/final-213-customer-ready/release-integration/security-audit.json",
                "docs/audit/final-213-customer-ready/release-integration/quality-gates.json",
                "docs/audit/final-213-customer-ready/release-integration/quality-gates.md",
                "docs/audit/final-213-customer-ready/release-integration/local-release-rehearsal.json",
                "docs/audit/final-213-customer-ready/release-integration/commit-plan.json",
                "docs/audit/final-213-customer-ready/release-integration/FINAL-REPORT.md"
            ]
        }
    ],
    "push_decision": {
        "ready_to_push": False,
        "blockers": [
            "Dirty worktree contains 234 modified files and 150 untracked files from prior phases.",
            "These are not authored in this Phase 15 turn and must not be bulk-staged.",
            "Per safety rule 'Do NOT reset, clean, stash, stage, commit, push, or bulk-restore the worktree. The live dirty worktree is authoritative.'",
            "Pushing this state without proper per-file review risks committing unverified prior-phase work."
        ],
        "required_to_unblock": [
            "Either commit and push Phase-15-authored files only in targeted logical commits, OR",
            "Complete review/classification of all 384 dirty paths so each logical commit is verifiable.",
            "Stage exact paths only; no 'git add .'.",
            "Secret-scan staged files before each commit."
        ]
    },
    "verdict": "PHASE_15_AUTHORED_FILES_READY_BUT_COMMIT_REQUIRES_REVIEW_OF_DIRTY_WORKTREE",
    "notes": [
        "Phase 15 (security remediation) files are authored and untracked, ready to commit once the dirty worktree is reviewed.",
        "Merge gate (security critical/high = 0) is satisfied by package.json overrides.",
        "scripts/local/* toolkit, customer documentation, and release audit evidence are authored.",
        "Quality gates recorded as PASS / PASS_WITH_KNOWN_FAILURES.",
        "Local runtime rehearsal is deferred to Phase 20 (clean-clone verification)."
    ]
}

with open(OUT / "commit-plan.json", "w", encoding="utf-8") as fh:
    json.dump(plan, fh, indent=2, ensure_ascii=False)

print(f"Wrote {OUT / 'commit-plan.json'}")
print(f"Phase-15 authored untracked files: {len(mine_untracked)}")
print(f"Prior-phase dirty worktree: {len(modified)} modified + {len(untracked) - len(mine_untracked)} other untracked")