/**
 * GENERATED by scripts/audit/browser-visibility-source-render-only.mjs (PHASE 2).
 *
 * Authenticated routing/visibility smoke for source/render-only INPUT_CONNECTED_PASS
 * forms that have not yet had browser evidence. Codes are emitted from
 * docs/audit/unified-bm-workspace/QLLAW_SOURCE_RENDER_ONLY_BROWSER_VISIBILITY_CANDIDATES.latest.json
 * (data-driven; no hardcoded list).
 *
 * Asserts per code:
 *   - not redirected to /sign-in or /sign-up
 *   - page URL stays on /templates/<code> (does NOT redirect to /documents/...)
 *   - "BM-NNN" is visible somewhere on the page
 *   - at least one <h3> section heading is visible
 *   - at least one <input> or <textarea> or <select> is visible
 *   - "Xem trước bản in" button is visible
 *   - page does not show the "Không tìm thấy trang" boundary
 *   - no "Lịch sử xử lý" history UI visible
 *   - no fatal console errors
 *
 * Does NOT click preview, does NOT click demo, does NOT exercise the
 * preview-session API, does NOT download DOCX.
 */
import { expect, test } from "@playwright/test";

const CODES: string[] = ["BM-002","BM-003","BM-004","BM-013","BM-016","BM-021","BM-025","BM-026","BM-027","BM-028","BM-029","BM-032","BM-034","BM-101","BM-102","BM-103","BM-104","BM-105","BM-106","BM-107","BM-108","BM-109","BM-110","BM-111","BM-112","BM-113","BM-114","BM-115","BM-116","BM-117","BM-118","BM-119","BM-120","BM-121","BM-122","BM-123","BM-124","BM-125","BM-126","BM-127","BM-128","BM-129","BM-130","BM-131","BM-132","BM-133","BM-134","BM-135","BM-136","BM-137","BM-138","BM-139","BM-140","BM-141","BM-142","BM-143","BM-144","BM-145","BM-146","BM-147","BM-148","BM-149","BM-150","BM-151","BM-152","BM-153","BM-154","BM-155","BM-156","BM-157","BM-158","BM-159","BM-160","BM-161","BM-162","BM-163","BM-164","BM-165","BM-166","BM-167","BM-168","BM-169","BM-170","BM-172","BM-173","BM-174","BM-175","BM-176","BM-177","BM-178","BM-179","BM-180","BM-181","BM-182","BM-183","BM-184","BM-185","BM-186","BM-187","BM-188","BM-189","BM-190","BM-191","BM-192","BM-193","BM-194","BM-195","BM-196","BM-197","BM-198","BM-199","BM-201","BM-202","BM-203","BM-204","BM-205","BM-206","BM-207","BM-208","BM-209","BM-210","BM-211","BM-212","BM-213"];

test.describe("Source/Render-Only Browser Visibility Smoke (auth)", () => {
  for (const templateCode of CODES) {
    test(`${templateCode} loads authenticated with runtime-ux shell`, async ({ page }) => {
      const consoleErrors: string[] = [];
      const pageErrors: string[] = [];

      page.on("console", (msg) => {
        if (msg.type() === "error") consoleErrors.push(msg.text());
      });
      page.on("pageerror", (err) => {
        pageErrors.push(String(err));
      });

      await page.goto(`/templates/${templateCode}`);

      await expect(page).not.toHaveURL(/sign-in|sign-up|\/documents\//, {
        timeout: 20_000,
      });

      await expect(
        page.getByText(new RegExp(templateCode, "i")).first(),
      ).toBeVisible({ timeout: 20_000 });

      const sectionHeadings = page.locator("h3");
      await expect(sectionHeadings.first()).toBeVisible({ timeout: 20_000 });
      const sectionCount = await sectionHeadings.count();
      expect(sectionCount).toBeGreaterThanOrEqual(1);

      const inputs = page.locator("input, textarea, select");
      await expect(inputs.first()).toBeVisible({ timeout: 20_000 });
      const inputCount = await inputs.count();
      expect(inputCount).toBeGreaterThanOrEqual(1);

      const previewBtn = page
        .getByRole("button", { name: /Xem trước bản in/i })
        .first();
      await expect(previewBtn).toBeVisible();

      await expect(page.locator("text=Không tìm thấy trang")).toHaveCount(0);

      await expect(page.locator("text=Lịch sử xử lý")).toHaveCount(0);

      const fatal = [...consoleErrors, ...pageErrors].filter(
        (m) =>
          !/Clerk has been loaded with development keys/i.test(m) &&
          !/infinite redirect loop/i.test(m) &&
          !/Download the React DevTools/i.test(m) &&
          !/Failed to load resource: the server responded with a status of 429/i.test(m) &&
          !/ThrottlerException/i.test(m) &&
          !/Too Many Requests/i.test(m),
      );
      expect(fatal, `console/page errors: ${fatal.join(" | ")}`).toHaveLength(0);
    });
  }
});
