/**
 * F1 — DOCX slot inventory + placeholder syntax audit (focused jest test).
 *
 * Companion to scripts/audit/audit-docx-slot-inventory.mjs. Reads the
 * machine-readable latest.json report (regenerated by the script in CI)
 * and asserts the audit's invariants from the jest side. This is the
 * CI gate that fails when a triple-brace (or split-run, or truncated)
 * template defect creeps back into the normalized DOCX corpus.
 *
 * Why both a script and a jest spec:
 *  - The script is the audit itself: it walks 213 contracts + DOCX and
 *    writes docs/audit/docx-slot-inventory/latest.{json,md}. It exits
 *    1 on FAIL.
 *  - This jest spec is the CI regression: it asserts the report
 *    surface that an operator/PM needs to see in a CI dashboard. It
 *    fails loudly if the report goes stale (e.g. shape changed),
 *    shrinks (corpus dropped), or regresses back to malformed
 *    placeholders.
 *
 * Historical context (F1_FIX):
 *  - Prior to F1_FIX_TRIPLE_BRACE_TEMPLATES this spec asserted BM-051
 *    was FAIL and overall status was FAIL. After the repair (89
 *    replacements across 13 BMs: 87 TRIPLE_IN_RUN + 2 TRUNCATED_AT_END
 *    + 1 UNBALANCED_IN_RUN merge), the corpus is fully clean. The spec
 *    below now asserts the post-FIX invariants: 213/213 PASS, zero
 *    malformed placeholders.
 *
 * Scope guard (do NOT extend without a separate task):
 *  - This spec does NOT run the audit itself. It only reads latest.json
 *    produced by the script. If latest.json is missing, the test fails
 *    with a clear "run pnpm audit:docx-slot-inventory first" message.
 *  - This spec does NOT remediate defects. Remediation is the
 *    `scripts/docx-contract/repair-triple-brace-placeholders.mjs`
 *    script's job (Path A).
 *  - This spec does NOT render DOCX. The audit script doesn't either.
 */

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const REPO_ROOT = join(process.cwd(), '..', '..');
const REPORT_JSON = join(
  REPO_ROOT,
  'docs',
  'audit',
  'docx-slot-inventory',
  'latest.json',
);

interface MalformedPlaceholder {
  part: string;
  kind: string;
  offset?: number;
  preview?: string;
  templateCode?: string;
}

interface PerBmReport {
  templateCode: string;
  sourceId: string | null;
  fileName: string;
  docxPresent: boolean;
  totalDocxSlots: number;
  canonicalPaths: string[];
  renderBindings: string[];
  duplicateCanonicalPaths: Array<{ path: string; count: number }>;
  orphanRenderBindings: Array<{ slotId: string; from?: string }>;
  slotsWithoutBinding: string[];
  rejectedWithoutReason: string[];
  malformedPlaceholders: MalformedPlaceholder[];
  status: 'PASS' | 'FAIL';
}

interface SlotInventoryReport {
  generatedAt: string;
  status: 'PASS' | 'FAIL';
  summary: {
    totalContracts: number;
    totalTemplatesFound: number;
    totalTemplatesMissing: number;
    totalDocxSlots: number;
    totalRenderBindings: number;
    totalCanonicalFields: number;
    malformedPlaceholdersCount: number;
    passCount: number;
    failCount: number;
    statusByBm: Record<string, 'PASS' | 'FAIL'>;
    malformedSamples: MalformedPlaceholder[];
  };
  perBm: PerBmReport[];
}

const loadReport = (): SlotInventoryReport => {
  if (!existsSync(REPORT_JSON)) {
    throw new Error(
      `F1 audit report missing at ${REPORT_JSON}. Run \`pnpm audit:docx-slot-inventory\` (or with --report-only) before running this test.`,
    );
  }
  return JSON.parse(readFileSync(REPORT_JSON, 'utf8')) as SlotInventoryReport;
};

describe('F1 — DOCX slot inventory + placeholder syntax audit', () => {
  const report = loadReport();
  const bm051 = report.perBm.find((r) => r.templateCode === 'BM-051');

  it('produces a recent report (within the last 24h)', () => {
    const generated = new Date(report.generatedAt).getTime();
    const ageMs = Date.now() - generated;
    // Allow up to 24h staleness so a CI run that schedules the audit
    // before the test does not fail by clock drift alone.
    expect(ageMs).toBeLessThan(24 * 60 * 60 * 1000);
  });

  it('covers all 213 locked contracts', () => {
    expect(report.summary.totalContracts).toBe(213);
    expect(report.perBm).toHaveLength(213);
  });

  it('every locked contract has a matching normalized DOCX template', () => {
    expect(report.summary.totalTemplatesMissing).toBe(0);
  });

  it('reports 2497 docxSlots / 2497 canonicalFields / 2497 renderBindings', () => {
    // These mirror E1's contract-level totals — the F1 audit walks the
    // same corpus and must agree on the shape. If this fails, either the
    // corpus shrank or the audit walked a subset.
    expect(report.summary.totalDocxSlots).toBe(2497);
    expect(report.summary.totalCanonicalFields).toBe(2497);
    expect(report.summary.totalRenderBindings).toBe(2497);
  });

  it('no duplicate canonical paths across the corpus', () => {
    for (const r of report.perBm) {
      expect(r.duplicateCanonicalPaths).toEqual([]);
    }
  });

  it('no docxSlot is left without renderBinding or rejected-reason', () => {
    for (const r of report.perBm) {
      expect(r.slotsWithoutBinding).toEqual([]);
      expect(r.rejectedWithoutReason).toEqual([]);
    }
  });

  it('BM-051 is PASS after F1_FIX_TRIPLE_BRACE_TEMPLATES repair', () => {
    expect(bm051).toBeDefined();
    expect(bm051?.status).toBe('PASS');
    expect(bm051?.malformedPlaceholders).toEqual([]);
  });

  it('all 213 contracts are PASS with zero malformed placeholders', () => {
    // Post-F1_FIX: the repair script removed 89 defect occurrences
    // across 13 BMs (TRIPLE_IN_RUN, TRUNCATED_AT_END, UNBALANCED_IN_RUN
    // merge). F1 audit must now report full corpus green.
    expect(report.status).toBe('PASS');
    expect(report.summary.failCount).toBe(0);
    expect(report.summary.passCount).toBe(report.summary.totalContracts);
    expect(report.summary.malformedPlaceholdersCount).toBe(0);
    // Sanity: every perBm entry must report PASS and zero findings.
    for (const r of report.perBm) {
      expect(r.status).toBe('PASS');
      expect(r.malformedPlaceholders).toEqual([]);
    }
  });

  it('logged the malformedPlaceholdersCount for the corpus report', () => {
    // Useful for SUMMARY.md updates — F1 reports the exact count so an
    // operator can spot regressions (e.g. a new contract adds a
    // malformed placeholder and this number grows from 0 back up).
    expect(report.summary.malformedPlaceholdersCount).toBe(0);
    // The count must match the sum across perBm.
    const sumAcrossBm = report.perBm.reduce(
      (sum, r) => sum + r.malformedPlaceholders.length,
      0,
    );
    expect(report.summary.malformedPlaceholdersCount).toBe(sumAcrossBm);
  });
});
