/**
 * F1 — DOCX slot inventory + placeholder syntax audit (focused jest test).
 *
 * Companion to scripts/audit/audit-docx-slot-inventory.mjs. Reads the
 * machine-readable latest.json report (regenerated by the script in CI)
 * and asserts the audit's invariants from the jest side. This is the
 * CI gate that fails when BM-051 (and any other triple-brace template)
 * is found.
 *
 * Why both a script and a jest spec:
 *  - The script is the audit itself: it walks 213 contracts + DOCX and
 *    writes docs/audit/docx-slot-inventory/latest.{json,md}. It exits
 *    1 on FAIL.
 *  - This jest spec is the CI regression: it asserts the report
 *    surface that an operator/PM needs to see in a CI dashboard. It
 *    fails loudly if the report goes stale (e.g. shape changed),
 *    shrinks (corpus dropped), or fails to flag BM-051.
 *
 * Scope guard (do NOT extend without a separate task):
 *  - This spec does NOT run the audit itself. It only reads latest.json
 *    produced by the script. If latest.json is missing, the test fails
 *    with a clear "run pnpm audit:docx-slot-inventory first" message.
 *  - This spec does NOT remediate defects. Per the F1 brief, BM-051's
 *    triple-brace syntax is a real template defect owned by F2 — this
 *    spec surfaces it, doesn't fix it.
 *  - This spec does NOT render DOCX. The audit script doesn't either.
 */

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const REPO_ROOT = join(process.cwd(), '..', '..');
const REPORT_JSON = join(
  REPO_ROOT,
  'docs',
  'audit',
  'docx-slot-inventory',
  'latest.json',
);

interface MalformedPlaceholder {
  part: string;
  kind: string;
  offset?: number;
  preview?: string;
  templateCode?: string;
}

interface PerBmReport {
  templateCode: string;
  sourceId: string | null;
  fileName: string;
  docxPresent: boolean;
  totalDocxSlots: number;
  canonicalPaths: string[];
  renderBindings: string[];
  duplicateCanonicalPaths: Array<{ path: string; count: number }>;
  orphanRenderBindings: Array<{ slotId: string; from?: string }>;
  slotsWithoutBinding: string[];
  rejectedWithoutReason: string[];
  malformedPlaceholders: MalformedPlaceholder[];
  status: 'PASS' | 'FAIL';
}

interface SlotInventoryReport {
  generatedAt: string;
  status: 'PASS' | 'FAIL';
  summary: {
    totalContracts: number;
    totalTemplatesFound: number;
    totalTemplatesMissing: number;
    totalDocxSlots: number;
    totalRenderBindings: number;
    totalCanonicalFields: number;
    malformedPlaceholdersCount: number;
    passCount: number;
    failCount: number;
    statusByBm: Record<string, 'PASS' | 'FAIL'>;
    malformedSamples: MalformedPlaceholder[];
  };
  perBm: PerBmReport[];
}

const loadReport = (): SlotInventoryReport => {
  if (!existsSync(REPORT_JSON)) {
    throw new Error(
      `F1 audit report missing at ${REPORT_JSON}. Run \`pnpm audit:docx-slot-inventory\` (or with --report-only) before running this test.`,
    );
  }
  return JSON.parse(readFileSync(REPORT_JSON, 'utf8')) as SlotInventoryReport;
};

describe('F1 — DOCX slot inventory + placeholder syntax audit', () => {
  const report = loadReport();
  const bm051 = report.perBm.find((r) => r.templateCode === 'BM-051');

  it('produces a recent report (within the last 24h)', () => {
    const generated = new Date(report.generatedAt).getTime();
    const ageMs = Date.now() - generated;
    // Allow up to 24h staleness so a CI run that schedules the audit
    // before the test does not fail by clock drift alone.
    expect(ageMs).toBeLessThan(24 * 60 * 60 * 1000);
  });

  it('covers all 213 locked contracts', () => {
    expect(report.summary.totalContracts).toBe(213);
    expect(report.perBm).toHaveLength(213);
  });

  it('every locked contract has a matching normalized DOCX template', () => {
    expect(report.summary.totalTemplatesMissing).toBe(0);
  });

  it('reports 2453 docxSlots / 2453 canonicalFields / 2453 renderBindings', () => {
    // These mirror E1's contract-level totals — the F1 audit walks the
    // same corpus and must agree on the shape. If this fails, either the
    // corpus shrank or the audit walked a subset.
    expect(report.summary.totalDocxSlots).toBe(2453);
    expect(report.summary.totalCanonicalFields).toBe(2453);
    expect(report.summary.totalRenderBindings).toBe(2453);
  });

  it('no duplicate canonical paths across the corpus', () => {
    for (const r of report.perBm) {
      expect(r.duplicateCanonicalPaths).toEqual([]);
    }
  });

  it('no docxSlot is left without renderBinding or rejected-reason', () => {
    for (const r of report.perBm) {
      expect(r.slotsWithoutBinding).toEqual([]);
      expect(r.rejectedWithoutReason).toEqual([]);
    }
  });

  it('reports BM-051 as FAIL with malformed placeholders (the E2 blocker)', () => {
    expect(bm051).toBeDefined();
    expect(bm051?.status).toBe('FAIL');
    expect(bm051?.malformedPlaceholders.length ?? 0).toBeGreaterThan(0);
    const kinds = new Set(bm051?.malformedPlaceholders.map((m) => m.kind));
    // BM-051 is the canonical case where literal "}}}" or unbalanced
    // braces appear in the DOCX. Either ORPHAN_CLOSING or TRIPLE_BRACE
    // is acceptable as the classifier; both indicate the same defect
    // class — malformed placeholder syntax that DocxTemplater cannot
    // compile.
    expect(
      kinds.has('ORPHAN_CLOSING') || kinds.has('TRIPLE_BRACE'),
    ).toBe(true);
  });

  it('overall audit status is FAIL until F2 fixes the template defect', () => {
    // This is the signal F1 is meant to surface: the audit cannot pass
    // because at least one BM has malformed placeholder syntax. F2 owns
    // the fix; until then the audit must remain FAIL.
    expect(report.status).toBe('FAIL');
    expect(report.summary.failCount).toBeGreaterThan(0);
    // Sanity: passCount + failCount === totalContracts.
    expect(report.summary.passCount + report.summary.failCount).toBe(
      report.summary.totalContracts,
    );
  });

  it('logs the malformedPlaceholdersCount for the corpus report', () => {
    // Useful for SUMMARY.md updates — F1 reports the exact count so an
    // operator can spot regressions (e.g. a new contract adds a malformed
    // placeholder and this number grows).
    expect(report.summary.malformedPlaceholdersCount).toBeGreaterThan(0);
    // The count must match the sum across perBm.
    const sumAcrossBm = report.perBm.reduce(
      (sum, r) => sum + r.malformedPlaceholders.length,
      0,
    );
    expect(report.summary.malformedPlaceholdersCount).toBe(sumAcrossBm);
  });
});
