/**
 * Auto-generated by scripts/generate-bm-panel-registry.mjs
 * Regenerate with: node scripts/generate-bm-panel-registry.mjs
 *
 * Maps each BM template code to its form-inputs panel component.
 * Any code not in this map falls back to PublishedContractFormInputsPanel
 * (V2 renderer) if a published DB contract exists, or GenericTemplateFormInputsPanel.
 */

import { Bm001FormInputsPanel } from "./bm-001-form-inputs";
import { Bm002FormInputsPanel } from "./bm-002-form-inputs";
import { Bm003FormInputsPanel } from "./bm-003-form-inputs";
import { Bm004FormInputsPanel } from "./bm-004-form-inputs";
import { Bm005FormInputsPanel } from "./bm-005-form-inputs";
import { Bm006FormInputsPanel } from "./bm-006-form-inputs";
import { Bm007FormInputsPanel } from "./bm-007-form-inputs";
import { Bm008FormInputsPanel } from "./bm-008-form-inputs";
import { Bm009FormInputsPanel } from "./bm-009-form-inputs";
import { Bm010FormInputsPanel } from "./bm-010-form-inputs";
import { Bm011FormInputsPanel } from "./bm-011-form-inputs";
import { Bm012FormInputsPanel } from "./bm-012-form-inputs";
import { Bm013FormInputsPanel } from "./bm-013-form-inputs";
import { Bm014FormInputsPanel } from "./bm-014-form-inputs";
import { Bm015FormInputsPanel } from "./bm-015-form-inputs";
import { Bm016FormInputsPanel } from "./bm-016-form-inputs";
import { Bm017FormInputsPanel } from "./bm-017-form-inputs";
import { Bm018FormInputsPanel } from "./bm-018-form-inputs";
import { Bm019FormInputsPanel } from "./bm-019-form-inputs";
import { Bm020FormInputsPanel } from "./bm-020-form-inputs";
import { Bm021FormInputsPanel } from "./bm-021-form-inputs";
import { Bm022FormInputsPanel } from "./bm-022-form-inputs";
import { Bm023FormInputsPanel } from "./bm-023-form-inputs";
import { Bm024FormInputsPanel } from "./bm-024-form-inputs";
import { Bm025FormInputsPanel } from "./bm-025-form-inputs";
import { Bm026FormInputsPanel } from "./bm-026-form-inputs";
import { Bm027FormInputsPanel } from "./bm-027-form-inputs";
import { Bm028FormInputsPanel } from "./bm-028-form-inputs";
import { Bm029FormInputsPanel } from "./bm-029-form-inputs";
import { Bm030FormInputsPanel } from "./bm-030-form-inputs";
import { Bm031FormInputsPanel } from "./bm-031-form-inputs";
import { Bm032FormInputsPanel } from "./bm-032-form-inputs";
import { Bm033FormInputsPanel } from "./bm-033-form-inputs";
import { Bm034FormInputsPanel } from "./bm-034-form-inputs";
import { Bm035FormInputsPanel } from "./bm-035-form-inputs";
import { Bm036FormInputsPanel } from "./bm-036-form-inputs";
import { Bm037FormInputsPanel } from "./bm-037-form-inputs";
import { Bm038FormInputsPanel } from "./bm-038-form-inputs";
import { Bm039FormInputsPanel } from "./bm-039-form-inputs";
import { Bm040FormInputsPanel } from "./bm-040-form-inputs";
import { Bm041FormInputsPanel } from "./bm-041-form-inputs";
import { Bm042FormInputsPanel } from "./bm-042-form-inputs";
import { Bm043FormInputsPanel } from "./bm-043-form-inputs";
import { Bm044FormInputsPanel } from "./bm-044-form-inputs";
import { Bm045FormInputsPanel } from "./bm-045-form-inputs";
import { Bm046FormInputsPanel } from "./bm-046-form-inputs";
import { Bm047FormInputsPanel } from "./bm-047-form-inputs";
import { Bm048FormInputsPanel } from "./bm-048-form-inputs";
import { Bm049FormInputsPanel } from "./bm-049-form-inputs";
import { Bm050FormInputsPanel } from "./bm-050-form-inputs";
import { Bm051FormInputsPanel } from "./bm-051-form-inputs";
import { Bm052FormInputsPanel } from "./bm-052-form-inputs";
import { Bm053FormInputsPanel } from "./bm-053-form-inputs";
import { Bm054FormInputsPanel } from "./bm-054-form-inputs";
import { Bm055FormInputsPanel } from "./bm-055-form-inputs";
import { Bm056FormInputsPanel } from "./bm-056-form-inputs";
import { Bm057FormInputsPanel } from "./bm-057-form-inputs";
import { Bm058FormInputsPanel } from "./bm-058-form-inputs";
import { Bm059FormInputsPanel } from "./bm-059-form-inputs";
import { Bm060FormInputsPanel } from "./bm-060-form-inputs";
import { Bm061FormInputsPanel } from "./bm-061-form-inputs";
import { Bm062FormInputsPanel } from "./bm-062-form-inputs";
import { Bm063FormInputsPanel } from "./bm-063-form-inputs";
import { Bm064FormInputsPanel } from "./bm-064-form-inputs";
import { Bm065FormInputsPanel } from "./bm-065-form-inputs";
import { Bm066FormInputsPanel } from "./bm-066-form-inputs";
import { Bm067FormInputsPanel } from "./bm-067-form-inputs";
import { Bm068FormInputsPanel } from "./bm-068-form-inputs";
import { Bm069FormInputsPanel } from "./bm-069-form-inputs";
import { Bm070FormInputsPanel } from "./bm-070-form-inputs";
import { Bm071FormInputsPanel } from "./bm-071-form-inputs";
import { Bm072FormInputsPanel } from "./bm-072-form-inputs";
import { Bm073FormInputsPanel } from "./bm-073-form-inputs";
import { Bm074FormInputsPanel } from "./bm-074-form-inputs";
import { Bm075FormInputsPanel } from "./bm-075-form-inputs";
import { Bm076FormInputsPanel } from "./bm-076-form-inputs";
import { Bm077FormInputsPanel } from "./bm-077-form-inputs";
import { Bm078FormInputsPanel } from "./bm-078-form-inputs";
import { Bm079FormInputsPanel } from "./bm-079-form-inputs";
import { Bm080FormInputsPanel } from "./bm-080-form-inputs";
import { Bm081FormInputsPanel } from "./bm-081-form-inputs";
import { Bm082FormInputsPanel } from "./bm-082-form-inputs";
import { Bm083FormInputsPanel } from "./bm-083-form-inputs";
import { Bm084FormInputsPanel } from "./bm-084-form-inputs";
import { Bm085FormInputsPanel } from "./bm-085-form-inputs";
import { Bm086FormInputsPanel } from "./bm-086-form-inputs";
import { Bm087FormInputsPanel } from "./bm-087-form-inputs";
import { Bm088FormInputsPanel } from "./bm-088-form-inputs";
import { Bm089FormInputsPanel } from "./bm-089-form-inputs";
import { Bm090FormInputsPanel } from "./bm-090-form-inputs";
import { Bm091FormInputsPanel } from "./bm-091-form-inputs";
import { Bm092FormInputsPanel } from "./bm-092-form-inputs";
import { Bm093FormInputsPanel } from "./bm-093-form-inputs";
import { Bm094FormInputsPanel } from "./bm-094-form-inputs";
import { Bm095FormInputsPanel } from "./bm-095-form-inputs";
import { Bm096FormInputsPanel } from "./bm-096-form-inputs";
import { Bm097FormInputsPanel } from "./bm-097-form-inputs";
import { Bm098FormInputsPanel } from "./bm-098-form-inputs";
import { Bm099FormInputsPanel } from "./bm-099-form-inputs";
import { Bm100FormInputsPanel } from "./bm-100-form-inputs";
import { Bm101FormInputsPanel } from "./bm-101-form-inputs";
import { Bm102FormInputsPanel } from "./bm-102-form-inputs";
import { Bm103FormInputsPanel } from "./bm-103-form-inputs";
import { Bm104FormInputsPanel } from "./bm-104-form-inputs";
import { Bm105FormInputsPanel } from "./bm-105-form-inputs";
import { Bm106FormInputsPanel } from "./bm-106-form-inputs";
import { Bm107FormInputsPanel } from "./bm-107-form-inputs";
import { Bm108FormInputsPanel } from "./bm-108-form-inputs";
import { Bm109FormInputsPanel } from "./bm-109-form-inputs";
import { Bm110FormInputsPanel } from "./bm-110-form-inputs";
import { Bm111FormInputsPanel } from "./bm-111-form-inputs";
import { Bm112FormInputsPanel } from "./bm-112-form-inputs";
import { Bm113FormInputsPanel } from "./bm-113-form-inputs";
import { Bm114FormInputsPanel } from "./bm-114-form-inputs";
import { Bm115FormInputsPanel } from "./bm-115-form-inputs";
import { Bm116FormInputsPanel } from "./bm-116-form-inputs";
import { Bm117FormInputsPanel } from "./bm-117-form-inputs";
import { Bm118FormInputsPanel } from "./bm-118-form-inputs";
import { Bm119FormInputsPanel } from "./bm-119-form-inputs";
import { Bm120FormInputsPanel } from "./bm-120-form-inputs";
import { Bm121FormInputsPanel } from "./bm-121-form-inputs";
import { Bm122FormInputsPanel } from "./bm-122-form-inputs";
import { Bm123FormInputsPanel } from "./bm-123-form-inputs";
import { Bm124FormInputsPanel } from "./bm-124-form-inputs";
import { Bm125FormInputsPanel } from "./bm-125-form-inputs";
import { Bm126FormInputsPanel } from "./bm-126-form-inputs";
import { Bm127FormInputsPanel } from "./bm-127-form-inputs";
import { Bm128FormInputsPanel } from "./bm-128-form-inputs";
import { Bm129FormInputsPanel } from "./bm-129-form-inputs";
import { Bm130FormInputsPanel } from "./bm-130-form-inputs";
import { Bm131FormInputsPanel } from "./bm-131-form-inputs";
import { Bm132FormInputsPanel } from "./bm-132-form-inputs";
import { Bm133FormInputsPanel } from "./bm-133-form-inputs";
import { Bm134FormInputsPanel } from "./bm-134-form-inputs";
import { Bm135FormInputsPanel } from "./bm-135-form-inputs";
import { Bm136FormInputsPanel } from "./bm-136-form-inputs";
import { Bm137FormInputsPanel } from "./bm-137-form-inputs";
import { Bm138FormInputsPanel } from "./bm-138-form-inputs";
import { Bm139FormInputsPanel } from "./bm-139-form-inputs";
import { Bm140FormInputsPanel } from "./bm-140-form-inputs";
import { Bm141FormInputsPanel } from "./bm-141-form-inputs";
import { Bm142FormInputsPanel } from "./bm-142-form-inputs";
import { Bm143FormInputsPanel } from "./bm-143-form-inputs";
import { Bm144FormInputsPanel } from "./bm-144-form-inputs";
import { Bm145FormInputsPanel } from "./bm-145-form-inputs";
import { Bm146FormInputsPanel } from "./bm-146-form-inputs";
import { Bm147FormInputsPanel } from "./bm-147-form-inputs";
import { Bm148FormInputsPanel } from "./bm-148-form-inputs";
import { Bm149FormInputsPanel } from "./bm-149-form-inputs";
import { Bm150FormInputsPanel } from "./bm-150-form-inputs";
import { Bm151FormInputsPanel } from "./bm-151-form-inputs";
import { Bm152FormInputsPanel } from "./bm-152-form-inputs";
import { Bm153FormInputsPanel } from "./bm-153-form-inputs";
import { Bm154FormInputsPanel } from "./bm-154-form-inputs";
import { Bm155FormInputsPanel } from "./bm-155-form-inputs";
import { Bm156FormInputsPanel } from "./bm-156-form-inputs";
import { Bm157FormInputsPanel } from "./bm-157-form-inputs";
import { Bm158FormInputsPanel } from "./bm-158-form-inputs";
import { Bm159FormInputsPanel } from "./bm-159-form-inputs";
import { Bm160FormInputsPanel } from "./bm-160-form-inputs";
import { Bm161FormInputsPanel } from "./bm-161-form-inputs";
import { Bm162FormInputsPanel } from "./bm-162-form-inputs";
import { Bm163FormInputsPanel } from "./bm-163-form-inputs";
import { Bm164FormInputsPanel } from "./bm-164-form-inputs";
import { Bm165FormInputsPanel } from "./bm-165-form-inputs";
import { Bm166FormInputsPanel } from "./bm-166-form-inputs";
import { Bm167FormInputsPanel } from "./bm-167-form-inputs";
import { Bm168FormInputsPanel } from "./bm-168-form-inputs";
import { Bm169FormInputsPanel } from "./bm-169-form-inputs";
import { Bm170FormInputsPanel } from "./bm-170-form-inputs";
import { Bm171FormInputsPanel } from "./bm-171-form-inputs";
import { Bm173FormInputsPanel } from "./bm-173-form-inputs";
import { Bm174FormInputsPanel } from "./bm-174-form-inputs";
import { Bm175FormInputsPanel } from "./bm-175-form-inputs";
import { Bm176FormInputsPanel } from "./bm-176-form-inputs";
import { Bm177FormInputsPanel } from "./bm-177-form-inputs";
import { Bm178FormInputsPanel } from "./bm-178-form-inputs";
import { Bm179FormInputsPanel } from "./bm-179-form-inputs";
import { Bm180FormInputsPanel } from "./bm-180-form-inputs";
import { Bm181FormInputsPanel } from "./bm-181-form-inputs";
import { Bm182FormInputsPanel } from "./bm-182-form-inputs";
import { Bm183FormInputsPanel } from "./bm-183-form-inputs";
import { Bm184FormInputsPanel } from "./bm-184-form-inputs";
import { Bm185FormInputsPanel } from "./bm-185-form-inputs";
import { Bm186FormInputsPanel } from "./bm-186-form-inputs";
import { Bm187FormInputsPanel } from "./bm-187-form-inputs";
import { Bm188FormInputsPanel } from "./bm-188-form-inputs";
import { Bm189FormInputsPanel } from "./bm-189-form-inputs";
import { Bm190FormInputsPanel } from "./bm-190-form-inputs";
import { Bm191FormInputsPanel } from "./bm-191-form-inputs";
import { Bm192FormInputsPanel } from "./bm-192-form-inputs";
import { Bm193FormInputsPanel } from "./bm-193-form-inputs";
import { Bm194FormInputsPanel } from "./bm-194-form-inputs";
import { Bm195FormInputsPanel } from "./bm-195-form-inputs";
import { Bm196FormInputsPanel } from "./bm-196-form-inputs";
import { Bm197FormInputsPanel } from "./bm-197-form-inputs";
import { Bm198FormInputsPanel } from "./bm-198-form-inputs";
import { Bm199FormInputsPanel } from "./bm-199-form-inputs";
import { Bm200FormInputsPanel } from "./bm-200-form-inputs";
import { Bm201FormInputsPanel } from "./bm-201-form-inputs";
import { Bm202FormInputsPanel } from "./bm-202-form-inputs";
import { Bm203FormInputsPanel } from "./bm-203-form-inputs";
import { Bm204FormInputsPanel } from "./bm-204-form-inputs";
import { Bm205FormInputsPanel } from "./bm-205-form-inputs";
import { Bm206FormInputsPanel } from "./bm-206-form-inputs";
import { Bm207FormInputsPanel } from "./bm-207-form-inputs";
import { Bm208FormInputsPanel } from "./bm-208-form-inputs";
import { Bm209FormInputsPanel } from "./bm-209-form-inputs";
import { Bm210FormInputsPanel } from "./bm-210-form-inputs";
import { Bm211FormInputsPanel } from "./bm-211-form-inputs";
import { Bm212FormInputsPanel } from "./bm-212-form-inputs";
import { Bm213FormInputsPanel } from "./bm-213-form-inputs";

export const BM_PANEL_REGISTRY: Record<string, React.ComponentType<{
  documentId: string;
  onSaved?: () => void;
}>> = {
  "BM-001": Bm001FormInputsPanel,
  "BM-002": Bm002FormInputsPanel,
  "BM-003": Bm003FormInputsPanel,
  "BM-004": Bm004FormInputsPanel,
  "BM-005": Bm005FormInputsPanel,
  "BM-006": Bm006FormInputsPanel,
  "BM-007": Bm007FormInputsPanel,
  "BM-008": Bm008FormInputsPanel,
  "BM-009": Bm009FormInputsPanel,
  "BM-010": Bm010FormInputsPanel,
  "BM-011": Bm011FormInputsPanel,
  "BM-012": Bm012FormInputsPanel,
  "BM-013": Bm013FormInputsPanel,
  "BM-014": Bm014FormInputsPanel,
  "BM-015": Bm015FormInputsPanel,
  "BM-016": Bm016FormInputsPanel,
  "BM-017": Bm017FormInputsPanel,
  "BM-018": Bm018FormInputsPanel,
  "BM-019": Bm019FormInputsPanel,
  "BM-020": Bm020FormInputsPanel,
  "BM-021": Bm021FormInputsPanel,
  "BM-022": Bm022FormInputsPanel,
  "BM-023": Bm023FormInputsPanel,
  "BM-024": Bm024FormInputsPanel,
  "BM-025": Bm025FormInputsPanel,
  "BM-026": Bm026FormInputsPanel,
  "BM-027": Bm027FormInputsPanel,
  "BM-028": Bm028FormInputsPanel,
  "BM-029": Bm029FormInputsPanel,
  "BM-030": Bm030FormInputsPanel,
  "BM-031": Bm031FormInputsPanel,
  "BM-032": Bm032FormInputsPanel,
  "BM-033": Bm033FormInputsPanel,
  "BM-034": Bm034FormInputsPanel,
  "BM-035": Bm035FormInputsPanel,
  "BM-036": Bm036FormInputsPanel,
  "BM-037": Bm037FormInputsPanel,
  "BM-038": Bm038FormInputsPanel,
  "BM-039": Bm039FormInputsPanel,
  "BM-040": Bm040FormInputsPanel,
  "BM-041": Bm041FormInputsPanel,
  "BM-042": Bm042FormInputsPanel,
  "BM-043": Bm043FormInputsPanel,
  "BM-044": Bm044FormInputsPanel,
  "BM-045": Bm045FormInputsPanel,
  "BM-046": Bm046FormInputsPanel,
  "BM-047": Bm047FormInputsPanel,
  "BM-048": Bm048FormInputsPanel,
  "BM-049": Bm049FormInputsPanel,
  "BM-050": Bm050FormInputsPanel,
  "BM-051": Bm051FormInputsPanel,
  "BM-052": Bm052FormInputsPanel,
  "BM-053": Bm053FormInputsPanel,
  "BM-054": Bm054FormInputsPanel,
  "BM-055": Bm055FormInputsPanel,
  "BM-056": Bm056FormInputsPanel,
  "BM-057": Bm057FormInputsPanel,
  "BM-058": Bm058FormInputsPanel,
  "BM-059": Bm059FormInputsPanel,
  "BM-060": Bm060FormInputsPanel,
  "BM-061": Bm061FormInputsPanel,
  "BM-062": Bm062FormInputsPanel,
  "BM-063": Bm063FormInputsPanel,
  "BM-064": Bm064FormInputsPanel,
  "BM-065": Bm065FormInputsPanel,
  "BM-066": Bm066FormInputsPanel,
  "BM-067": Bm067FormInputsPanel,
  "BM-068": Bm068FormInputsPanel,
  "BM-069": Bm069FormInputsPanel,
  "BM-070": Bm070FormInputsPanel,
  "BM-071": Bm071FormInputsPanel,
  "BM-072": Bm072FormInputsPanel,
  "BM-073": Bm073FormInputsPanel,
  "BM-074": Bm074FormInputsPanel,
  "BM-075": Bm075FormInputsPanel,
  "BM-076": Bm076FormInputsPanel,
  "BM-077": Bm077FormInputsPanel,
  "BM-078": Bm078FormInputsPanel,
  "BM-079": Bm079FormInputsPanel,
  "BM-080": Bm080FormInputsPanel,
  "BM-081": Bm081FormInputsPanel,
  "BM-082": Bm082FormInputsPanel,
  "BM-083": Bm083FormInputsPanel,
  "BM-084": Bm084FormInputsPanel,
  "BM-085": Bm085FormInputsPanel,
  "BM-086": Bm086FormInputsPanel,
  "BM-087": Bm087FormInputsPanel,
  "BM-088": Bm088FormInputsPanel,
  "BM-089": Bm089FormInputsPanel,
  "BM-090": Bm090FormInputsPanel,
  "BM-091": Bm091FormInputsPanel,
  "BM-092": Bm092FormInputsPanel,
  "BM-093": Bm093FormInputsPanel,
  "BM-094": Bm094FormInputsPanel,
  "BM-095": Bm095FormInputsPanel,
  "BM-096": Bm096FormInputsPanel,
  "BM-097": Bm097FormInputsPanel,
  "BM-098": Bm098FormInputsPanel,
  "BM-099": Bm099FormInputsPanel,
  "BM-100": Bm100FormInputsPanel,
  "BM-101": Bm101FormInputsPanel,
  "BM-102": Bm102FormInputsPanel,
  "BM-103": Bm103FormInputsPanel,
  "BM-104": Bm104FormInputsPanel,
  "BM-105": Bm105FormInputsPanel,
  "BM-106": Bm106FormInputsPanel,
  "BM-107": Bm107FormInputsPanel,
  "BM-108": Bm108FormInputsPanel,
  "BM-109": Bm109FormInputsPanel,
  "BM-110": Bm110FormInputsPanel,
  "BM-111": Bm111FormInputsPanel,
  "BM-112": Bm112FormInputsPanel,
  "BM-113": Bm113FormInputsPanel,
  "BM-114": Bm114FormInputsPanel,
  "BM-115": Bm115FormInputsPanel,
  "BM-116": Bm116FormInputsPanel,
  "BM-117": Bm117FormInputsPanel,
  "BM-118": Bm118FormInputsPanel,
  "BM-119": Bm119FormInputsPanel,
  "BM-120": Bm120FormInputsPanel,
  "BM-121": Bm121FormInputsPanel,
  "BM-122": Bm122FormInputsPanel,
  "BM-123": Bm123FormInputsPanel,
  "BM-124": Bm124FormInputsPanel,
  "BM-125": Bm125FormInputsPanel,
  "BM-126": Bm126FormInputsPanel,
  "BM-127": Bm127FormInputsPanel,
  "BM-128": Bm128FormInputsPanel,
  "BM-129": Bm129FormInputsPanel,
  "BM-130": Bm130FormInputsPanel,
  "BM-131": Bm131FormInputsPanel,
  "BM-132": Bm132FormInputsPanel,
  "BM-133": Bm133FormInputsPanel,
  "BM-134": Bm134FormInputsPanel,
  "BM-135": Bm135FormInputsPanel,
  "BM-136": Bm136FormInputsPanel,
  "BM-137": Bm137FormInputsPanel,
  "BM-138": Bm138FormInputsPanel,
  "BM-139": Bm139FormInputsPanel,
  "BM-140": Bm140FormInputsPanel,
  "BM-141": Bm141FormInputsPanel,
  "BM-142": Bm142FormInputsPanel,
  "BM-143": Bm143FormInputsPanel,
  "BM-144": Bm144FormInputsPanel,
  "BM-145": Bm145FormInputsPanel,
  "BM-146": Bm146FormInputsPanel,
  "BM-147": Bm147FormInputsPanel,
  "BM-148": Bm148FormInputsPanel,
  "BM-149": Bm149FormInputsPanel,
  "BM-150": Bm150FormInputsPanel,
  "BM-151": Bm151FormInputsPanel,
  "BM-152": Bm152FormInputsPanel,
  "BM-153": Bm153FormInputsPanel,
  "BM-154": Bm154FormInputsPanel,
  "BM-155": Bm155FormInputsPanel,
  "BM-156": Bm156FormInputsPanel,
  "BM-157": Bm157FormInputsPanel,
  "BM-158": Bm158FormInputsPanel,
  "BM-159": Bm159FormInputsPanel,
  "BM-160": Bm160FormInputsPanel,
  "BM-161": Bm161FormInputsPanel,
  "BM-162": Bm162FormInputsPanel,
  "BM-163": Bm163FormInputsPanel,
  "BM-164": Bm164FormInputsPanel,
  "BM-165": Bm165FormInputsPanel,
  "BM-166": Bm166FormInputsPanel,
  "BM-167": Bm167FormInputsPanel,
  "BM-168": Bm168FormInputsPanel,
  "BM-169": Bm169FormInputsPanel,
  "BM-170": Bm170FormInputsPanel,
  "BM-171": Bm171FormInputsPanel,
  "BM-173": Bm173FormInputsPanel,
  "BM-174": Bm174FormInputsPanel,
  "BM-175": Bm175FormInputsPanel,
  "BM-176": Bm176FormInputsPanel,
  "BM-177": Bm177FormInputsPanel,
  "BM-178": Bm178FormInputsPanel,
  "BM-179": Bm179FormInputsPanel,
  "BM-180": Bm180FormInputsPanel,
  "BM-181": Bm181FormInputsPanel,
  "BM-182": Bm182FormInputsPanel,
  "BM-183": Bm183FormInputsPanel,
  "BM-184": Bm184FormInputsPanel,
  "BM-185": Bm185FormInputsPanel,
  "BM-186": Bm186FormInputsPanel,
  "BM-187": Bm187FormInputsPanel,
  "BM-188": Bm188FormInputsPanel,
  "BM-189": Bm189FormInputsPanel,
  "BM-190": Bm190FormInputsPanel,
  "BM-191": Bm191FormInputsPanel,
  "BM-192": Bm192FormInputsPanel,
  "BM-193": Bm193FormInputsPanel,
  "BM-194": Bm194FormInputsPanel,
  "BM-195": Bm195FormInputsPanel,
  "BM-196": Bm196FormInputsPanel,
  "BM-197": Bm197FormInputsPanel,
  "BM-198": Bm198FormInputsPanel,
  "BM-199": Bm199FormInputsPanel,
  "BM-200": Bm200FormInputsPanel,
  "BM-201": Bm201FormInputsPanel,
  "BM-202": Bm202FormInputsPanel,
  "BM-203": Bm203FormInputsPanel,
  "BM-204": Bm204FormInputsPanel,
  "BM-205": Bm205FormInputsPanel,
  "BM-206": Bm206FormInputsPanel,
  "BM-207": Bm207FormInputsPanel,
  "BM-208": Bm208FormInputsPanel,
  "BM-209": Bm209FormInputsPanel,
  "BM-210": Bm210FormInputsPanel,
  "BM-211": Bm211FormInputsPanel,
  "BM-212": Bm212FormInputsPanel,
  "BM-213": Bm213FormInputsPanel,
};

// Total: 212 BM panels (all 213 have dedicated panels)
export const BM_PANEL_COUNT = 212;

// Missing panels (212/213, these will use V2 renderer):
export const MISSING_BM_PANELS: string[] = ["BM-172"];