// AUTO-GENERATED by scripts/release/regenerate-authoritative-roster.mjs
// Source: phase15b1-authoritative-promotion-manifest.json (REAL_UI evidence policy)

export type PromotionStatus =
  | "ALREADY_READY"
  | "NEWLY_PROMOTED"
  | "PHASE14_BROWSER_PROMOTED"
  | "RUNTIME_CANDIDATE_WORD_VERIFIED"
  | "RUNTIME_CANDIDATE_PROVISIONAL";

export interface RUNTIME_READINESS_ENTRY {
  readonly formCode: string;
  readonly promotionStatus: PromotionStatus;
  readonly evidencePath: string;
  readonly evidenceSha256: string;
  readonly source: "baselineRuntimeReady" | "phase1-accounting.promoted" | "phase14-dual-browser-promotion";
}

export const RUNTIME_READINESS_ENTRIES = [
  {
    formCode: "BM-058",
    promotionStatus: "PHASE14_BROWSER_PROMOTED",
    evidencePath: "docs/audit/final-213-customer-ready/runtime-rollout/locked-authority-rebase/phase14-dual-browser-promotion/turn4-final-83-form-lifecycle-verdicts.json",
    evidenceSha256: "16d57333d4b95174ceb5415ed28039bcc17afaa51bad15e17e24155543fe7a40",
    source: "phase14-dual-browser-promotion",
  } as const,
  {
    formCode: "BM-093",
    promotionStatus: "PHASE14_BROWSER_PROMOTED",
    evidencePath: "docs/audit/final-213-customer-ready/runtime-rollout/locked-authority-rebase/phase14-dual-browser-promotion/turn4-final-83-form-lifecycle-verdicts.json",
    evidenceSha256: "32a98e38263ad1522ab9e7f36a8b136d63f754c8b39a421134d21b4ed8d72bd1",
    source: "phase14-dual-browser-promotion",
  } as const,
  {
    formCode: "BM-139",
    promotionStatus: "PHASE14_BROWSER_PROMOTED",
    evidencePath: "docs/audit/final-213-customer-ready/runtime-rollout/locked-authority-rebase/phase14-dual-browser-promotion/turn4-final-83-form-lifecycle-verdicts.json",
    evidenceSha256: "67f2561b937e012f6f94381a006e0f269b36448cee9c5f1aad05dffb45045baf",
    source: "phase14-dual-browser-promotion",
  } as const,
  {
    formCode: "BM-157",
    promotionStatus: "ALREADY_READY",
    evidencePath: "packages/form-contracts/src/bridge-eligibility.ts",
    evidenceSha256: "4fd92988f595c85d77bbfb5680dc99ecdfd8d9db96639534bd68f1c673d305b1",
    source: "baselineRuntimeReady",
  } as const,
  {
    formCode: "BM-168",
    promotionStatus: "ALREADY_READY",
    evidencePath: "packages/form-contracts/src/bridge-eligibility.ts",
    evidenceSha256: "bd63fe76417534a0c858c1491e38678c5cfa943790b25754ecb8a054e93e1a81",
    source: "baselineRuntimeReady",
  } as const,
  {
    formCode: "BM-174",
    promotionStatus: "ALREADY_READY",
    evidencePath: "packages/form-contracts/src/bridge-eligibility.ts",
    evidenceSha256: "78a586eafa381a0a0b442a5c3fee81ad58efeff953329e198c294913c89b8676",
    source: "baselineRuntimeReady",
  } as const,
  {
    formCode: "BM-177",
    promotionStatus: "PHASE14_BROWSER_PROMOTED",
    evidencePath: "docs/audit/final-213-customer-ready/runtime-rollout/locked-authority-rebase/phase14-dual-browser-promotion/turn4-final-83-form-lifecycle-verdicts.json",
    evidenceSha256: "272e1203dc3951d1e6d5cd7bed9033798c82d225461fbdce202ba8e3fa0552b6",
    source: "phase14-dual-browser-promotion",
  } as const,
  {
    formCode: "BM-179",
    promotionStatus: "PHASE14_BROWSER_PROMOTED",
    evidencePath: "docs/audit/final-213-customer-ready/runtime-rollout/locked-authority-rebase/phase14-dual-browser-promotion/turn4-final-83-form-lifecycle-verdicts.json",
    evidenceSha256: "a39f044ac18427e06e4f23e4ac4cdd4de84aa6b1edc508c6f32f2f59121508bf",
    source: "phase14-dual-browser-promotion",
  } as const,
  {
    formCode: "BM-181",
    promotionStatus: "ALREADY_READY",
    evidencePath: "packages/form-contracts/src/bridge-eligibility.ts",
    evidenceSha256: "244861bb3e41a8484344245d9795a3f03ac662b207b52876a4effe2a5dbaf3c6",
    source: "baselineRuntimeReady",
  } as const,
  {
    formCode: "BM-183",
    promotionStatus: "PHASE14_BROWSER_PROMOTED",
    evidencePath: "docs/audit/final-213-customer-ready/runtime-rollout/locked-authority-rebase/phase14-dual-browser-promotion/turn4-final-83-form-lifecycle-verdicts.json",
    evidenceSha256: "f78c4a3ec53cf00cfabc2d30c5ec7c556efcc1dd6ddb4bd66be4d36ba6b56788",
    source: "phase14-dual-browser-promotion",
  } as const,
  {
    formCode: "BM-186",
    promotionStatus: "PHASE14_BROWSER_PROMOTED",
    evidencePath: "docs/audit/final-213-customer-ready/runtime-rollout/locked-authority-rebase/phase14-dual-browser-promotion/turn4-final-83-form-lifecycle-verdicts.json",
    evidenceSha256: "3045ae85953a75b1f3f52831dc43e70a1c6fa173e0907057a562ed918020588d",
    source: "phase14-dual-browser-promotion",
  } as const,
  {
    formCode: "BM-187",
    promotionStatus: "PHASE14_BROWSER_PROMOTED",
    evidencePath: "docs/audit/final-213-customer-ready/runtime-rollout/locked-authority-rebase/phase14-dual-browser-promotion/turn4-final-83-form-lifecycle-verdicts.json",
    evidenceSha256: "0f66ea2d34e0a1ca44d09e04d8ef4aaf15a0cf7af44578e50e3b31b1185f80d1",
    source: "phase14-dual-browser-promotion",
  } as const,
  {
    formCode: "BM-189",
    promotionStatus: "PHASE14_BROWSER_PROMOTED",
    evidencePath: "docs/audit/final-213-customer-ready/runtime-rollout/locked-authority-rebase/phase14-dual-browser-promotion/turn4-final-83-form-lifecycle-verdicts.json",
    evidenceSha256: "090067f3e07ca4dfe826913be3891cb00cad71b9202dbadc2c9e2a9ae12232fa",
    source: "phase14-dual-browser-promotion",
  } as const,
  {
    formCode: "BM-190",
    promotionStatus: "PHASE14_BROWSER_PROMOTED",
    evidencePath: "docs/audit/final-213-customer-ready/runtime-rollout/locked-authority-rebase/phase14-dual-browser-promotion/turn4-final-83-form-lifecycle-verdicts.json",
    evidenceSha256: "13b6444ebf979ca8727c6f98205fb5ae3556421f032b004eab754a727a2bd011",
    source: "phase14-dual-browser-promotion",
  } as const,
  {
    formCode: "BM-192",
    promotionStatus: "PHASE14_BROWSER_PROMOTED",
    evidencePath: "docs/audit/final-213-customer-ready/runtime-rollout/locked-authority-rebase/phase14-dual-browser-promotion/turn4-final-83-form-lifecycle-verdicts.json",
    evidenceSha256: "ec606919ca7077e9e17049483cfb564b1ba2950b55b09aa44d1db6677f99ae94",
    source: "phase14-dual-browser-promotion",
  } as const,
  {
    formCode: "BM-193",
    promotionStatus: "PHASE14_BROWSER_PROMOTED",
    evidencePath: "docs/audit/final-213-customer-ready/runtime-rollout/locked-authority-rebase/phase14-dual-browser-promotion/turn4-final-83-form-lifecycle-verdicts.json",
    evidenceSha256: "a6f7893bac45691a49377a82ab411682a637b94b64c8fe1825d007bbef5f9263",
    source: "phase14-dual-browser-promotion",
  } as const,
  {
    formCode: "BM-194",
    promotionStatus: "PHASE14_BROWSER_PROMOTED",
    evidencePath: "docs/audit/final-213-customer-ready/runtime-rollout/locked-authority-rebase/phase14-dual-browser-promotion/turn4-final-83-form-lifecycle-verdicts.json",
    evidenceSha256: "9a86f649f75f3bffa1c9fa1bc2f89d82908b769cd7a0cce4fa2497c45edc4754",
    source: "phase14-dual-browser-promotion",
  } as const,
  {
    formCode: "BM-196",
    promotionStatus: "PHASE14_BROWSER_PROMOTED",
    evidencePath: "docs/audit/final-213-customer-ready/runtime-rollout/locked-authority-rebase/phase14-dual-browser-promotion/turn4-final-83-form-lifecycle-verdicts.json",
    evidenceSha256: "71760be6a0391a24de52bfc29f87cfe51603f27468a5a67ba5aabcf422ad6d4e",
    source: "phase14-dual-browser-promotion",
  } as const,
  {
    formCode: "BM-197",
    promotionStatus: "PHASE14_BROWSER_PROMOTED",
    evidencePath: "docs/audit/final-213-customer-ready/runtime-rollout/locked-authority-rebase/phase14-dual-browser-promotion/turn4-final-83-form-lifecycle-verdicts.json",
    evidenceSha256: "4afca58ccef4ef769febf8c45f49a60451057a41b893c93609c8a7026b61bd40",
    source: "phase14-dual-browser-promotion",
  } as const,
  {
    formCode: "BM-201",
    promotionStatus: "PHASE14_BROWSER_PROMOTED",
    evidencePath: "docs/audit/final-213-customer-ready/runtime-rollout/locked-authority-rebase/phase14-dual-browser-promotion/turn4-final-83-form-lifecycle-verdicts.json",
    evidenceSha256: "e3bedc6f2e7058bd394c33acdd6e8647eece7e8312e5587711c348f8461adee0",
    source: "phase14-dual-browser-promotion",
  } as const,
  {
    formCode: "BM-203",
    promotionStatus: "PHASE14_BROWSER_PROMOTED",
    evidencePath: "docs/audit/final-213-customer-ready/runtime-rollout/locked-authority-rebase/phase14-dual-browser-promotion/turn4-final-83-form-lifecycle-verdicts.json",
    evidenceSha256: "9221d88494d9e4d915307a1c7567451b5b01550b50d78554548c4ca4a37f356e",
    source: "phase14-dual-browser-promotion",
  } as const,
  {
    formCode: "BM-205",
    promotionStatus: "PHASE14_BROWSER_PROMOTED",
    evidencePath: "docs/audit/final-213-customer-ready/runtime-rollout/locked-authority-rebase/phase14-dual-browser-promotion/turn4-final-83-form-lifecycle-verdicts.json",
    evidenceSha256: "510071869fef05216cc58f5d39ee68792bf20562d5c2b9962d1bcce317ade299",
    source: "phase14-dual-browser-promotion",
  } as const,
  {
    formCode: "BM-206",
    promotionStatus: "ALREADY_READY",
    evidencePath: "packages/form-contracts/src/bridge-eligibility.ts",
    evidenceSha256: "ea45dd69b6370fc2753d50d0b85ae2f833ac137e9d872e0f9f3442dbd0ed9b47",
    source: "baselineRuntimeReady",
  } as const,
  {
    formCode: "BM-212",
    promotionStatus: "PHASE14_BROWSER_PROMOTED",
    evidencePath: "docs/audit/final-213-customer-ready/runtime-rollout/locked-authority-rebase/phase14-dual-browser-promotion/turn4-final-83-form-lifecycle-verdicts.json",
    evidenceSha256: "700742730af143def4b457d4ef4cf02b1439c0923ae33e469ca136ff0781a5f9",
    source: "phase14-dual-browser-promotion",
  } as const,
  {
    formCode: "BM-213",
    promotionStatus: "ALREADY_READY",
    evidencePath: "packages/form-contracts/src/bridge-eligibility.ts",
    evidenceSha256: "6ef3bf31602864723bc76b5131ad60fbcd13e7abb1c2042a4c48d320595520bb",
    source: "baselineRuntimeReady",
  } as const,
] as const;

export const RUNTIME_READY_FORM_CODES = [
  "BM-058",
  "BM-093",
  "BM-139",
  "BM-157",
  "BM-168",
  "BM-174",
  "BM-177",
  "BM-179",
  "BM-181",
  "BM-183",
  "BM-186",
  "BM-187",
  "BM-189",
  "BM-190",
  "BM-192",
  "BM-193",
  "BM-194",
  "BM-196",
  "BM-197",
  "BM-201",
  "BM-203",
  "BM-205",
  "BM-206",
  "BM-212",
  "BM-213",
] as const;

export const RUNTIME_READINESS_PROVENANCE = {
  generatedAt: "2026-07-27T19:08:54.260Z",
  sourceManifestSha256: "f07074edf97c9b0c311a4c0f4f2895fbb4ea5c48bfb0a8901431d2cafdf59adf",
  baselineRuntimeReady: [
    "BM-157",
    "BM-168",
    "BM-174",
    "BM-181",
    "BM-206",
    "BM-213",
  ],
  notes: [
    "Counts are derived from unique form codes only.",
    "BM-001 is NOT in the authoritative 25-form roster. The Turn 4 adversarial audit did not produce an evidence row for BM-001, BM-136, BM-148, BM-156, or BM-171. Per the Phase 15B.1 evidence policy, these are demoted to SKELETON until fresh per-form evidence is provided.",
    "BM-001, BM-136, BM-148, BM-156, BM-171, BM-002, BM-008, BM-010, BM-012, BM-172 are demoted. Their previous ALREADY_READY/NEWLY_PROMOTED status was test-driven, not evidence-driven.",
    "Roster count = 25 (6 STANDALONE_RUNTIME_PREVIEW baseline + 19 PHASE14_BROWSER_PROMOTED with REAL_UI).",
    "Skeleton count = 188. Total manifest entries = 213.",
    "Phase 15B.1 rollback artifacts in docs/audit/final-213-customer-ready/release-integration/phase15b1-rollback-*",
  ],
} as const;
