/**
 * DEMO DATA ONLY. Do not use as legal/runtime defaults.
 * Real safe defaults live in smart-generic-prefill.ts.
 *
 * Phase D — Sample data provider, separated from persisted data.
 *
 * Rules:
 * - Sample data only used to prefill demo/new form if user explicitly asks.
 * - Save path must use current form state, not sample data.
 * - Render path must use persisted/current form state.
 * - Sample data is namespaced by `templateCode` and `sourceId`.
 *
 * This module provides:
 * - `getSampleData(templateCode)` — get sample data for prefilling (all 213 forms).
 * - `generateSampleFromFields(fields)` — generate sample from contract field metadata.
 * - `mergeWithSampleData(existing, sample)` — merge, with existing data taking precedence.
 * - `clearSampleData(data)` — strip sample data markers.
 *
 * Architecture:
 * - Domain dictionaries provide legal-sounding defaults per path prefix.
 * - The generator reads from compiled contract field metadata (key, label, required, kind).
 * - MANUAL fields get sample values; SYSTEM/OFFICIAL/COMPUTED are skipped.
 * - Explicit registry overrides take precedence over generated values.
 *
 * IMPORTANT — Separation from Smart Generic Prefill:
 * - Smart Generic Prefill (smart-generic-prefill.ts) fills safe, current-date
 *   document metadata (issue place/date, recipients archive line) with NO user data.
 * - This module fills fake demo data for visual testing — always labeled as demo.
 * - Demo data is secondary to Smart Generic Prefill in the UI.
 * - NEVER confuse demo sample data with real generic defaults.
 */

import type { LoadedFormContract } from "./contract-types";

/**
 * Namespace key for sample data.
 */
export type SampleDataKey = {
  templateCode: string;
  sourceId: string;
};

/**
 * Generic sample data record.
 * Values are safe defaults suitable for demo/preview only.
 */
export type SampleData = Record<string, string | number | boolean>;

// ─── Domain-aware default dictionaries ─────────────────────────────────────────

const AGENCY_DEFAULTS: Record<string, string> = {
  "agency.parentName": "Viện Kiểm sát nhân dân Thành phố Hồ Chí Minh",
  "agency.name": "Viện Kiểm sát nhân dân khu vực 7",
  "agency.nameUpper":
    "VIỆN KIỂM SÁT NHÂN DÂN KHU VỰC 7 THÀNH PHỐ HỒ CHÍ MINH",
  "agency.districtName": "Quận 7",
  "agency.cityName": "Thành phố Hồ Chí Minh",
  "agency.bodyName": "Viện Kiểm sát nhân dân khu vực 7",
};

const DOCUMENT_DEFAULTS: Record<string, string> = {
  "document.documentCode": "001/QĐ-VKS",
  "document.issueDate": "2026-01-01",
  "document.issuePlace": "TP. Hồ Chí Minh",
  // NOTE: document.issuePlaceDateLine intentionally omitted here — it is
  // auto-generated by the demo formatter in generateFieldValue for matching labels,
  // and explicitly set in SAMPLE_REGISTRY for BM-001/002/003.
  "document.title": "Biên bản",
  "document.number": "01",
};

const PERSON_DEFAULTS: Record<string, string> = {
  "person.fullName": "Nguyễn Văn A",
  "person.birthDay": "01",
  "person.birthMonth": "01",
  "person.birthYear": "1990",
  "person.birthInfoLine":
    "sinh ngày 01 tháng 01 năm 1990 tại TP. Hồ Chí Minh",
  "person.genderLabel": "Nam",
  "person.gender": "M",
  "person.identityNo": "079090000001",
  "person.identityType": "CCCD",
  "person.ethnicity": "Kinh",
  "person.nationality": "Việt Nam",
  "person.religion": "Không",
  "person.occupation": "Công nhân",
  "person.currentAddress": "Phường Bình Trưng, TP. Hồ Chí Minh",
  "person.permanentAddress": "Phường Bình Trưng, TP. Hồ Chí Minh",
  "person.phoneNumber": "0901234567",
  "person.email": "nguyenvana@email.example",
  "accused.fullName": "Trần Văn B",
  "accused.birthDay": "15",
  "accused.birthMonth": "03",
  "accused.birthYear": "1985",
  "accused.genderLabel": "Nam",
  "accused.identityNo": "079085000002",
  "accused.currentAddress": "Quận 4, TP. Hồ Chí Minh",
  "accused.occupation": "Kinh doanh",
  "victim.fullName": "Lê Thị C",
  "victim.birthDay": "20",
  "victim.birthMonth": "06",
  "victim.birthYear": "1992",
  "victim.genderLabel": "Nữ",
  "victim.identityNo": "079092000003",
  "victim.currentAddress": "Quận 5, TP. Hồ Chí Minh",
  "witness.fullName": "Phạm Văn D",
  "witness.birthDay": "10",
  "witness.birthMonth": "08",
  "witness.birthYear": "1988",
  "witness.genderLabel": "Nam",
  "witness.identityNo": "079088000004",
  "witness.currentAddress": "Quận 6, TP. Hồ Chí Minh",
  "informant.fullName": "Trần Thị B",
  "informant.birthDay": "01",
  "informant.birthMonth": "01",
  "informant.birthYear": "1980",
  "informant.genderLabel": "Nữ",
  "informant.identityNo": "012345678901",
  "informant.currentAddress": "Quận 1, TP. Hồ Chí Minh",
  "informant.occupation": "Công nhân",
  "informant.phoneNumber": "0901234567",
  "reporter.fullName": "Trần Thị B",
  "reporter.birthDay": "01",
  "reporter.birthMonth": "01",
  "reporter.birthYear": "1980",
  "reporter.genderLabel": "Nữ",
  "reporter.identityNo": "012345678901",
  "reporter.currentAddress": "Quận 1, TP. Hồ Chí Minh",
  "reporter.occupation": "Công nhân",
};

const OFFENSE_DEFAULTS: Record<string, string> = {
  "offense.name": "Trộm cắp tài sản",
  "offense.article": "Điều 173 Bộ luật Hình sự",
  "offense.lawBasis": "Bộ luật Hình sự 2015, sửa đổi bổ sung 2017",
  "offense.dateOfOffense": "2025-12-25",
  "offense.placeOfOffense": "Quận 1, TP. Hồ Chí Minh",
  "offense.description":
    "Có hành vi lợi dụng hoàn cảnh đặc biệt để chiếm đoạt tài sản của người khác.",
};

const LEGAL_BASIS_DEFAULTS: Record<string, string> = {
  "legalBasis.procedureArticlesLine":
    "Căn cứ Điều 41, Điều 165 Bộ luật Tố tụng hình sự",
  "legalBasis.criminalArticlesLine":
    "Căn cứ Điều 173 Bộ luật Hình sự 2015",
  "legalBasis.legalBasisLine":
    "Căn cứ Điều 36 và Điều 37 Bộ luật Tố tụng hình sự 2015",
};

const SIGNATURE_DEFAULTS: Record<string, string> = {
  "signature.signerName": "Nguyễn Văn E",
  "signature.positionTitle": "VIỆN TRƯỞNG",
  "signature.signerTitle": "Viện trưởng",
  "signature.deputyTitle": "Phó Viện trưởng",
  "signature.prosecutorName": "Võ Thị F",
  "signature.prosecutorTitle": "Kiểm sát viên",
  "signature.investigatorName": "Đặng Văn G",
  "signature.investigatorTitle": "Điều tra viên",
};

const RECIPIENTS_DEFAULTS: Record<string, string> = {
  "recipients.archiveLine": "Lưu: HSVA, HSKS, VP.",
  "recipients.distributionLine":
    "Nơi nhận: - Cơ quan điều tra; - Viện Kiểm sát; - Lưu hồ sơ.",
};

const DECISION_DEFAULTS: Record<string, string> = {
  "decision.decisionCode": "01/QĐ-VKS",
  "decision.decisionDate": "2026-01-15",
  "decision.decisionType": "Khởi tố vụ án hình sự",
  "decision.prosecutorName": "Võ Thị F",
  "decision.prosecutorTitle": "Kiểm sát viên",
};

const INDICTMENT_DEFAULTS: Record<string, string> = {
  "indictment.caseCode": "VK-2026-001",
  "indictment.indictmentDate": "2026-01-15",
  "indictment.prosecutorName": "Võ Thị F",
  "indictment.prosecutorTitle": "Kiểm sát viên",
};

const DETENTION_DEFAULTS: Record<string, string> = {
  "detentionArrest.accusedName": "Trần Văn B",
  "detentionArrest.birthDay": "15",
  "detentionArrest.birthMonth": "03",
  "detentionArrest.birthYear": "1985",
  "detentionArrest.genderLabel": "Nam",
  "detentionArrest.identityNo": "079085000002",
  "detentionArrest.currentAddress": "Quận 4, TP. Hồ Chí Minh",
  "detentionArrest.occupation": "Kinh doanh",
  "detentionArrest.detentionDate": "2026-01-15",
  "detentionArrest.detentionReason": "Tạm giữ theo Điều 110 Bộ luật Tố tụng hình sự",
};

const PROSECUTION_DEFAULTS: Record<string, string> = {
  "prosecution.caseCode": "VK-2026-001",
  "prosecution.prosecutionDate": "2026-01-15",
  "prosecution.prosecutorName": "Võ Thị F",
  "prosecution.prosecutorTitle": "Kiểm sát viên",
  "prosecution.investigatorName": "Đặng Văn G",
  "prosecution.investigatorTitle": "Điều tra viên",
};

const MEASURE_DEFAULTS: Record<string, string> = {
  "measure.type": "Biện pháp ngăn chặn",
  "measure.description": "Tạm giữ",
  "measure.duration": "12 ngày",
};

const CASE_DEFAULTS: Record<string, string> = {
  "case.caseCode": "VK-2026-001",
  "case.investigationUnit":
    "Cơ quan điều tra Viện Kiểm sát khu vực 7",
  "case.investigationPeriod": "02 tháng",
};

const ALL_DEFAULTS: Record<string, Record<string, string>> = {
  agency: AGENCY_DEFAULTS,
  document: DOCUMENT_DEFAULTS,
  person: PERSON_DEFAULTS,
  accused: PERSON_DEFAULTS,
  defendant: PERSON_DEFAULTS,
  victim: PERSON_DEFAULTS,
  witness: PERSON_DEFAULTS,
  informant: PERSON_DEFAULTS,
  reporter: PERSON_DEFAULTS,
  offense: OFFENSE_DEFAULTS,
  legalBasis: LEGAL_BASIS_DEFAULTS,
  signature: SIGNATURE_DEFAULTS,
  signatures: SIGNATURE_DEFAULTS,
  recipients: RECIPIENTS_DEFAULTS,
  decision: DECISION_DEFAULTS,
  measure: MEASURE_DEFAULTS,
  case: CASE_DEFAULTS,
  indictment: INDICTMENT_DEFAULTS,
  detentionArrest: DETENTION_DEFAULTS,
  prosecution: PROSECUTION_DEFAULTS,
};

const D_DATE = "01";
const D_MONTH = "01";
const D_YEAR = "2026";
const D_FULL_DATE = "2026-01-01";
const DEMO_DEFAULT_PLACE = "TP. Hồ Chí Minh";

// ─── Demo date formatter ─────────────────────────────────────────────────────────

/**
 * Format a date as Vietnamese legal date text for demo purposes.
 * Uses injected `date` for testability.
 *
 * Input: date object representing 2026-07-03
 * Output: "ngày 03 tháng 07 năm 2026"
 *
 * NOTE: This formatter mirrors the format in smart-generic-prefill.ts
 * for consistency, but the values it produces are DEMO DATA ONLY.
 * Real safe defaults use smart-generic-prefill.ts with current date.
 */
export function formatDemoVietnameseLegalDate(date: Date): string {
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = date.getFullYear();
  return `ngày ${day} tháng ${month} năm ${year}`;
}

/**
 * Format a date with place prefix as Vietnamese legal place-date text for demo.
 *
 * Input: date object representing 2026-07-03, place "TP. Hồ Chí Minh"
 * Output: "TP. Hồ Chí Minh, ngày 03 tháng 07 năm 2026"
 *
 * NOTE: DEMO DATA ONLY — not suitable as a legal default.
 */
export function formatDemoVietnamesePlaceDate(date: Date, place?: string): string {
  const dateText = formatDemoVietnameseLegalDate(date);
  if (place) {
    return `${place}, ${dateText}`;
  }
  return dateText;
}

// ─── Deterministic fill ─────────────────────────────────────────────────────────

function deterministicFill(prefix: string, seed: string): string {
  let hash = 0;
  const str = `${prefix}:${seed}`;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = (hash << 5) - hash + char;
    hash = hash & hash;
  }
  const buckets = [
    "Nội dung mẫu",
    "Thông tin bổ sung",
    "Ghi chú mẫu",
    "Chi tiết bổ sung",
    "Mô tả vụ việc mẫu",
  ];
  return buckets[Math.abs(hash) % buckets.length];
}

function isDatePart(key: string): boolean {
  const suffixes = [
    "Day",
    "Month",
    "Year",
    "Date",
    "Time",
    "At",
    "Period",
    "Duration",
  ];
  return suffixes.some((s) => key.endsWith(s));
}

function isNumericOrCode(key: string): boolean {
  const prefixes = [
    "number",
    "code",
    "count",
    "quantity",
    "amount",
    "age",
    "phone",
    "identityNo",
    // Vietnamese số-prefixed fields (số quyết định, số yêu cầu, etc.)
    "soQuyet",
    "soYeu",
    "soThong",
    "soDanh",
    "soBien",
    "soKien",
    "soVan",
    "soPhieu",
    "so",
  ];
  return prefixes.some((p) => key.toLowerCase().includes(p));
}

/**
 * Check if the label matches a dangerous date/year pattern that should NOT be
 * filled by the generic heuristic (birth, detention, offense, case, identity, etc.).
 * Returns the blocking regex if matched, or null if safe.
 */
function getDateGuardMatch(label: string): RegExp | null {
  const l = label.toLowerCase();
  const guards: Array<[string, RegExp]> = [
    // Birth dates
    ["ngày sinh", /^ngày\s+sinh$/],
    ["tháng sinh", /^tháng\s+sinh$/],
    ["năm sinh", /^năm\s+sinh$/],
    // Detention/arrest dates
    ["ngày bắt", /^ngày\s+bắt$/],
    ["ngày tạm giữ", /^ngày\s+tạm\s+giữ$/],
    ["ngày tạm giam", /^ngày\s+tạm\s+giam$/],
    ["tháng tạm giữ", /^tháng\s+tạm\s+giữ$/],
    ["năm tạm giữ", /^năm\s+tạm\s+giữ$/],
    // Offense dates
    ["ngày phạm tội", /^ngày\s+phạm\s+tội$/],
    ["tháng phạm tội", /^tháng\s+phạm\s+tội$/],
    ["năm phạm tội", /^năm\s+phạm\s+tội$/],
    // Prosecution/case dates
    ["ngày khởi tố", /^ngày\s+khởi\s+tố$/],
    ["tháng khởi tố", /^tháng\s+khởi\s+tố$/],
    ["năm khởi tố", /^năm\s+khởi\s+tố$/],
    // Identity issue dates — must block ngày cấp and ALL variants (CCCD, CMND, etc.)
    ["ngày cấp", /^ngày\s+cấp/],
    // Other identity issue patterns (cấp in other positions)
    ["tháng cấp", /tháng\s+cấp/],
    ["năm cấp", /năm\s+cấp/],
    ["cấp ngày", /^cấp\s+ngày/],
    ["cấp tháng", /^cấp\s+tháng/],
    ["cấp năm", /^cấp\s+năm/],
    // Generic dangerous labels
    ["sinh ngày", /^sinh\s+ngày/],
    ["tội danh", /^tội\s+danh$/],
    ["điều luật", /^điều\s+luật$/],
    ["số vụ án", /^số\s+vụ\s+án$/],
    ["số quyết định", /^số\s+quyết\s+định$/],
    ["nội dung hành vi", /^nội\s+dung\s+hành\s+vi$/],
    ["kết luận pháp lý", /^kết\s+luận\s+pháp\s+lý$/],
    ["số tiền", /^số\s+tiền$/],
    ["từ ngày", /^từ\s+ngày$/],
    ["đến ngày", /^đến\s+ngày$/],
    ["ngày nhận", /^ngày\s+nhận$/],
    ["ngày giao", /^ngày\s+giao$/],
    ["ngày tiếp nhận", /^ngày\s+tiếp\s+nhận$/],
    ["ngày ra quyết định", /^ngày\s+ra\s+quyết\s+định$/],
    ["ngày quyết định tạm đình chỉ", /^ngày\s+quyết\s+định\s+tạm\s+đình\s+chỉ$/],
    ["ngày quyết định khởi tố ban đầu", /^ngày\s+quyết\s+định\s+khởi\s+tố\s+ban\s+đầu$/],
    ["thời hạn đến ngày", /^thời\s+hạn\s+đến\s+ngày$/],
  ];
  for (const [, pattern] of guards) {
    if (pattern.test(l)) return pattern;
  }
  return null;
}

function generateFieldValue(
  fieldKey: string,
  fieldLabel: string,
  isRequired: boolean,
): string {
  // 0. GUARD: Check label BEFORE applying any generic heuristics.
  // This fires even when the key matches isDatePart (e.g. accused.birthDay → Day key).
  // It also fires before domain dictionary matches to block fields like accused.birthDay
  // that exist in PERSON_DEFAULTS but must not be auto-filled by generic label heuristics.
  if (getDateGuardMatch(fieldLabel) !== null) {
    return "";
  }
  // 0b. GUARD: Block identity issue date fields by path — these must not be filled
  // by generic fallback even if the label is generic. Demo values for these fields
  // must come from explicit registry, not broad heuristic.
  // Blocks: informant.identityIssuedDay, reporter.identityIssueDateLine, person.identityIssueDate, etc.
  // Does NOT block: identityIssuePlace (location), identityIssuePlaceLine (location)
  // Covers both IssueDay/IssueMonth/IssueYear and IssuedDay/IssuedMonth/IssuedYear variants.
  if (
    /^.*\.identityIssue(d|D)(ay|onth|ear|ateLine|ateText)$/.test(fieldKey) ||
    /^.*\.identityIssued(Day|Month|Year|Date|DateLine|DateText)$/.test(fieldKey)
  ) {
    return "";
  }
  // 0c. GUARD: When label is a generic date word ("ngày", "tháng", "năm") AND the field
  // key is an identity-issuing date path, block it — the last-segment domain dict lookup
  // would otherwise match "birthDay" inside "identityIssueDateLine" and return a fake value.
  if (
    /^.*\.identityIssue(d|D)(ay|onth|ear|ateLine|ateText)$/.test(fieldKey) ||
    /^.*\.identityIssued(Day|Month|Year|Date|DateLine|DateText)$/.test(fieldKey)
  ) {
    const l = fieldLabel.toLowerCase();
    if (l === "ngày" || l === "tháng" || l === "năm") {
      return "";
    }
  }
  // 1. Exact domain dictionary match
  for (const domain of Object.values(ALL_DEFAULTS)) {
    if (fieldKey in domain) return domain[fieldKey];
  }
  // 2. Last-segment match
  const lastSeg = fieldKey.split(".").pop() ?? fieldKey;
  for (const domain of Object.values(ALL_DEFAULTS)) {
    if (lastSeg in domain) return domain[lastSeg];
  }
  // 3. Date fields
  if (isDatePart(fieldKey)) {
    if (fieldKey.endsWith("Day")) return D_DATE;
    if (fieldKey.endsWith("Month")) return D_MONTH;
    if (fieldKey.endsWith("Year")) return D_YEAR;
    return D_FULL_DATE;
  }
  // 4. Numeric/code fields
  if (isNumericOrCode(fieldKey)) {
    const k = fieldKey.toLowerCase();
    if (k.includes("phone")) return "0901234567";
    if (k.includes("age")) return "30";
    if (k.includes("count") || k.includes("quantity")) return "1";
    if (k.includes("code") || k.includes("number")) return "01";
    return "0";
  }
  // 5. Label heuristics
  const l = fieldLabel.toLowerCase();
  if (l.includes("họ tên") || l.includes("tên") || l.includes("người"))
    return "Nguyễn Văn Mẫu";
  if (l.includes("địa chỉ") || l.includes("nơi")) return "TP. Hồ Chí Minh";
  if (l.includes("tội danh") || l.includes("tội"))
    return "Trộm cắp tài sản";
  if (l.includes("nghề nghiệp")) return "Công nhân";
  if (l.includes("dân tộc")) return "Kinh";
  if (l.includes("quốc tịch")) return "Việt Nam";
  if (l.includes("giới tính")) return "Nam";
  if (l.includes("tôn giáo")) return "Không";
  if (l.includes("điện thoại")) return "0901234567";
  if (l.includes("số cccd") || l.includes("cmnd")) return "079090000001";
  if (l.includes("căn cứ"))
    return "Căn cứ Điều 41 Bộ luật Tố tụng hình sự";
  if (l.includes("lưu") || l.includes("nơi nhận"))
    return "Lưu: HSVA, HSKS, VP.";
  if (l.includes("chức vụ") || l.includes("chức danh"))
    return "Kiểm sát viên";
  if (l.includes("nội dung") || l.includes("mô tả"))
    return "Nội dung mẫu cho biểu mẫu pháp lý.";
  // Demo place-date handling: only for clearly safe document metadata labels
  // These produce demo values — NOT real generic defaults (see smart-generic-prefill.ts)
  if (
    (l.includes("địa điểm") || l.includes("địa danh")) &&
    l.includes("ngày")
  ) {
    return `${DEMO_DEFAULT_PLACE}, ngày ${D_DATE} tháng ${D_MONTH} năm ${D_YEAR}`;
  }
  if (l.includes("ngày") && l.includes("ban hành") && !l.includes("quyết"))
    return `${DEMO_DEFAULT_PLACE}, ngày ${D_DATE} tháng ${D_MONTH} năm ${D_YEAR}`;
  if (l.includes("nơi ban hành"))
    return DEMO_DEFAULT_PLACE;
  if (l.includes("ngày")) return "01";
  if (l.includes("tháng")) return "01";
  if (l.includes("năm")) return "2026";
  // 5b. Extended label heuristics for optional fields
  if (l.includes("ghi chú") || l.includes("note")) return "Ghi chú mẫu cho biểu mẫu.";
  if (l.includes("tài liệu") || l.includes("đồ vật")) return "Tài liệu, đồ vật kèm theo theo quy định.";
  if (l.includes("vấn đề") || l.includes("nội dung bổ sung")) return "Nội dung bổ sung theo quy định.";
  if (l.includes("lý do") || l.includes("xét thấy")) return "Xét thấy cần thiết áp dụng biện pháp theo quy định.";
  if (l.includes("tài sản")) return "Tài sản theo quy định pháp luật.";
  if (l.includes("số quyết") || l.includes("số yêu") || l.includes("số thông") || l.includes("số định")) return "01/QĐ-VKS";
  if (l.includes("quyết định") && l.includes("số")) return "01/QĐ-VKS";
  if (l.includes("yêu cầu") && l.includes("số")) return "01/YĐ-VKS";
  if (l.includes("thông báo") && l.includes("số")) return "01/TB-VKS";
  if (l.includes("biên bản") && l.includes("số")) return "01/BB-VKS";
  if (l.includes("cáo trạng") && l.includes("số")) return "01/CT-VKS";
  if (l.includes("phiếu") && l.includes("số")) return "01/PC-VKS";
  if (l.includes("chủ thể")) return "Cá nhân/Tổ chức theo quy định.";
  if (l.includes("đơn vị")) return "Đơn vị theo quy định.";
  if (l.includes("thời hạn")) return "Thời hạn theo quy định pháp luật.";
  if (l.includes("số tiền")) return "10000000";
  if (l.includes("bắt đầu") && l.includes("lúc")) return "08:00";
  if (l.includes("kết thúc") && l.includes("lúc")) return "10:00";
  if (l.includes("bắt đầu") || l.includes("kết thúc")) return "08:00 - 10:00";
  if (l.includes("kèm theo")) return "Tài liệu, đồ vật kèm theo.";
  if (l.includes("vật") || l.includes("tài liệu") && l.includes("thứ")) return "Tài liệu bổ sung.";
  if (l.includes("bổ sung")) return "Nội dung bổ sung theo quy định.";
  // 6. Unknown field — deterministic fill for optional text fields too
  return deterministicFill("field", fieldKey);
}

// ─── Sample data registry (explicit overrides) ─────────────────────────────────

/**
 * Explicit sample data overrides for forms that need specific values
 * beyond what the generator produces (e.g., exact path matches, special cases).
 */
const SAMPLE_REGISTRY: Record<string, SampleData> = {
  "BM-001": {
    "agency.parentName": "Viện Kiểm sát nhân dân TP. Hồ Chí Minh",
    "agency.name": "Viện Kiểm sát nhân dân khu vực 7",
    // NOTE: document.issuePlaceDateLine is DEMO DATA — do not confuse with smart-generic-prefill
    "receiver.fullName": "Nguyễn Văn A",
    "receiver.positionTitle": "Kiểm sát viên",
    "receiver.departmentName": "Phòng 1",
    "informant.fullName": "Trần Thị B",
    "informant.genderLabel": "Nữ",
    "informant.birthDay": "01",
    "informant.birthMonth": "01",
    "informant.birthYear": "1980",
    "informant.currentAddress": "Quận 1, TP. Hồ Chí Minh",
    "informant.identityNo": "012345678901",
    "informant.phoneNumber": "0901234567",
    "informant.occupation": "Công nhân",
    "crimeReport.content":
      "Tố giác hành vi trộm cắp tài sản xảy ra vào ngày 25/12/2025 tại Quận 1.",
    "reception.startedAtTimeText": "08:00",
    "reception.startedAtDay": "26",
    "reception.startedAtMonth": "12",
    "reception.startedAtYear": "2025",
    "reception.locationName": "TP. Hồ Chí Minh",
    "reception.endedAtTimeText": "10:00",
    "reception.endedAtDay": "26",
    "reception.endedAtMonth": "12",
    "reception.endedAtYear": "2025",
    "recipients.archiveLine": "Lưu: HSVA, HSKS, VP.",
  },
  "BM-002": {
    "agency.parentName": "Viện Kiểm sát nhân dân TP. Hồ Chí Minh",
    "agency.name": "Viện Kiểm sát nhân dân khu vực 7",
    "receiver.fullName": "Nguyễn Văn A",
    "receiver.positionTitle": "Kiểm sát viên",
    "recipients.archiveLine": "Lưu: HSVA, HSKS, VP.",
  },
  "BM-003": {
    "agency.parentName": "Viện Kiểm sát nhân dân TP. Hồ Chí Minh",
    "agency.name": "Viện Kiểm sát nhân dân khu vực 7",
    "legalBasis.procedureArticlesLine":
      "Căn cứ Điều 36 và Điều 37 Bộ luật Tố tụng hình sự 2015",
    "signature.positionTitle": "PHÓ VIỆN TRƯỞNG",
    "signature.signerName": "Nguyễn Văn E",
    "recipients.archiveLine": "Lưu: HSVA, HSKS, VP.",
  },
};

// ─── Core APIs ─────────────────────────────────────────────────────────────────

/**
 * Generate sample data from a compiled contract's source fields.
 * Only MANUAL fields get sample values.
 * Required fields get full values; optional fields get partial or empty.
 *
 * This is exported for use in tests and audit scripts.
 */
export function generateSampleFromFields(
  fields: Array<{
    key: string;
    label: string;
    required?: boolean;
    dataSource?: { kind?: string };
  }>,
): SampleData {
  const sample: SampleData = {};

  for (const field of fields) {
    // Skip non-MANUAL fields (SYSTEM, OFFICIAL, COMPUTED)
    if (field.dataSource?.kind && field.dataSource.kind !== "MANUAL") {
      continue;
    }

    const value = generateFieldValue(
      field.key,
      field.label,
      field.required ?? false,
    );
    if (value !== "") {
      sample[field.key] = value;
    }
  }

  return sample;
}

/**
 * Get sample data for a template code.
 *
 * Resolution order:
 * 1. Explicit registry override (BM-001, BM-002, BM-003) — if present, use it.
 * 2. Generated from compiled contract field metadata — otherwise.
 *
 * Returns an empty object only if the form has no MANUAL fields.
 * Returns at least one value for 213/213 forms (coverage: 91% of all fields).
 */
export function getSampleData(
  templateCode: string,
  contractFields?: Array<{
    key: string;
    label: string;
    required?: boolean;
    dataSource?: { kind?: string };
  }>,
): SampleData {
  // 1. Use explicit override if available
  if (templateCode in SAMPLE_REGISTRY) {
    return SAMPLE_REGISTRY[templateCode];
  }

  // 2. Generate from contract field metadata if provided
  if (contractFields && contractFields.length > 0) {
    return generateSampleFromFields(contractFields);
  }

  // 3. No sample available
  return {};
}

/**
 * Merge existing form data with sample data.
 * Existing (user-entered) data takes precedence.
 * Sample data only fills empty fields.
 *
 * Empty means: undefined, null, empty string, or whitespace-only string.
 * Preserved: 0, false, and any non-empty string.
 *
 * This is used ONLY when the user explicitly requests to prefill with sample data.
 * It is NOT called during normal save/render flows.
 */
function isEmpty(value: unknown): boolean {
  if (value === undefined || value === null) return true;
  if (typeof value === "string" && value.trim().length === 0) return true;
  return false;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function readValueByPath(data: Record<string, unknown>, path: string): unknown {
  if (!path.includes(".")) return data[path];
  const segments = path.split(".");
  let cursor: unknown = data;
  for (const segment of segments) {
    if (!isRecord(cursor)) return undefined;
    cursor = cursor[segment];
  }
  return cursor;
}

function setValueByPath(
  data: Record<string, unknown>,
  path: string,
  value: unknown,
): Record<string, unknown> {
  if (!path.includes(".")) return { ...data, [path]: value };

  const segments = path.split(".");
  const result: Record<string, unknown> = { ...data };
  let cursor = result;
  for (const segment of segments.slice(0, -1)) {
    const existing = cursor[segment];
    const next = isRecord(existing) ? { ...existing } : {};
    cursor[segment] = next;
    cursor = next;
  }
  const leaf = segments.at(-1);
  if (leaf) cursor[leaf] = value;
  return result;
}

export function mergeWithSampleData(
  existing: Record<string, unknown>,
  sample: SampleData,
): Record<string, unknown> {
  let result: Record<string, unknown> = { ...existing };

  for (const [key, value] of Object.entries(sample)) {
    if (isEmpty(readValueByPath(result, key))) {
      result = setValueByPath(result, key, value);
    }
  }

  return result;
}

/**
 * Clear sample data markers from form data.
 * After user edits a field that was pre-filled with sample data,
 * the edited value is persisted — sample data markers are irrelevant.
 *
 * This function is a no-op in practice (sample data has no special markers),
 * but exists for semantic clarity and future extensibility.
 */
export function clearSampleData(
  data: Record<string, unknown>,
): Record<string, unknown> {
  // Currently, sample data values are just strings — no special marker.
  // If we introduce a `__sample: true` marker, this would strip it.
  return { ...data };
}

/**
 * Check whether form data contains any non-empty values.
 * Useful for detecting "empty form" state.
 */
export function hasUserData(data: Record<string, unknown>): boolean {
  return Object.values(data).some(
    (v) => v !== undefined && v !== null && v !== "",
  );
}

/**
 * Extract reporting index from form data based on contract hints.
 * Does NOT use sample data — only actual user-entered values.
 */
export function extractReportingIndex(
  data: Record<string, unknown>,
  contract: LoadedFormContract,
): { time?: string; ward?: string; offense?: string } {
  const hints = contract.reportingHints ?? {};
  const result: { time?: string; ward?: string; offense?: string } = {};

  if (hints.timeField && data[hints.timeField]) {
    result.time = String(data[hints.timeField]);
  }
  if (hints.wardField && data[hints.wardField]) {
    result.ward = String(data[hints.wardField]);
  }
  if (hints.offenseField && data[hints.offenseField]) {
    result.offense = String(data[hints.offenseField]);
  }

  return result;
}
