/**
 * BM-003 runtime-ux remaining curated source-render profile.
 *
 * Generated by: scripts/audit/generate-runtime-ux-profiles.mjs
 * Generator phase: 213-form input linkage, conservative template.
 *
 * This profile lifts BM-003 from FIDELITY_PENDING (generic
 * getSampleData fallback) to INPUT_CONNECTED_PARTIAL (route opens,
 * sections labelled, safe synthetic demo, no smart controls).
 *
 * Boundaries honoured here:
 *   - No mutation of the locked contract, the normalized DOCX, or
 *     the compiled contract.
 *   - No DB row creation, no generatedDocumentId fabrication.
 *   - No call to the generated-document save endpoint.
 *   - No smart controls emitted. Hand-curated smart controls are
 *     added by a separate, code-by-code promotion (see BM-001 /
 *     BM-171 for the reference shape).
 *   - No legacy stale tokens in demo (Nguyễn Văn A / Trần Thị B /
 *     1980 / Ông  cung cấp / Nguyễn Thị Hồng Hạnh).
 *
 * Promotion to INPUT_CONNECTED_PASS requires:
 *   - Hand-curated labels for the high-importance fields,
 *   - Smart controls only where evidence permits,
 *   - Golden-render + browser smoke evidence.
 *
 * See `QLLAW_FORM_INPUT_LINKAGE_CONTRACT.latest.md` for the contract
 * status codex.
 */

import {
  type RuntimeUxProfile,
  registerRuntimeUxProfile,
} from "./runtime-ux-profile";

const BM003_SECTIONS = [
  {
    sectionId: "section-agency",
    title: "agency",
  },
  {
    sectionId: "section-document",
    title: "document",
  },
  {
    sectionId: "section-legalbasis",
    title: "legalBasis",
  },
  {
    sectionId: "section-official",
    title: "official",
  },
  {
    sectionId: "section-recipients",
    title: "recipients",
  },
  {
    sectionId: "section-signature",
    title: "signature",
  },
  {
    sectionId: "section-sourceassignment",
    title: "sourceAssignment",
  },
] as const;

const BM003_FIELDS = {
  "agency.parentName": {
    label: "Cơ quan cấp trên",
    placeholder: "Cơ quan cấp trên ",
  },
  "agency.name": {
    label: "Tên cơ quan",
    placeholder: "Tên cơ quan ",
  },
  "document.documentCode": {
    label: "Số văn bản",
    placeholder: "Số văn bản ",
  },
  "document.issuePlaceAndDateLine": {
    label: "Địa điểm, ngày lập văn bản",
    placeholder: "Địa điểm , ngày 04 tháng 3 năm 2026",
  },
  "legalBasis.procedureArticlesLine": {
    label: "Căn cứ pháp lý",
    placeholder: "Căn cứ pháp lý ",
  },
  "official.issuerTitle": {
    label: "Chủ thể ban hành",
    placeholder: "Chủ thể ban hành ",
  },
  "recipients.primaryLine": {
    label: "Nơi nhận",
    placeholder: "Nơi nhận ",
  },
  "recipients.archiveLine": {
    label: "Lưu hồ sơ",
    placeholder: "Lưu: HSVA, HSKS, VP.",
  },
  "signature.signMode": {
    label: "Phương thức ký",
    placeholder: "Phương thức ký ",
  },
  "signature.positionTitle": {
    label: "Chức vụ",
    placeholder: "Chức vụ ",
  },
  "signature.signerName": {
    label: "Người ký",
    placeholder: "Người ký ",
  },
  "sourceAssignment.article1Line": {
    label: "Điều 1",
    placeholder: "Điều 1 ",
  },
  "sourceAssignment.article2Line": {
    label: "Điều 2",
    placeholder: "Điều 2 ",
  },
  "sourceAssignment.article3Line": {
    label: "Điều 3",
    placeholder: "Điều 3 ",
  },
} as const;

const BM003_DEMO_RUNTIME_UX = {
  "agency.parentName": "Cơ quan cấp trên ",
  "agency.name": "Tên cơ quan ",
  "document.documentCode": "Số văn bản ",
  "document.issuePlaceAndDateLine": "Địa điểm , ngày 04 tháng 3 năm 2026",
  "legalBasis.procedureArticlesLine": "Căn cứ pháp lý ",
  "official.issuerTitle": "Chủ thể ban hành ",
  "recipients.primaryLine": "Nơi nhận ",
  "recipients.archiveLine": "Lưu: HSVA, HSKS, VP.",
  "signature.signMode": "Phương thức ký ",
  "signature.positionTitle": "Chức vụ ",
  "signature.signerName": "Người ký ",
  "sourceAssignment.article1Line": "Điều 1 ",
  "sourceAssignment.article2Line": "Điều 2 ",
  "sourceAssignment.article3Line": "Điều 3 ",
} as const;

const BM003_RUNTIME_UX_PROFILE: RuntimeUxProfile = {
  templateCode: "BM-003",
  // Stable version label, surfaced in audit artifacts.
  versionLabel: `BM-003 runtime-ux remaining curated source-render profile`,
  sections: BM003_SECTIONS,
  fields: BM003_FIELDS,
  demo: BM003_DEMO_RUNTIME_UX,
};

registerRuntimeUxProfile(BM003_RUNTIME_UX_PROFILE);
