/**
 * BM-002 runtime-ux remaining curated source-render profile.
 *
 * Generated by: scripts/audit/generate-runtime-ux-profiles.mjs
 * Generator phase: 213-form input linkage, conservative template.
 *
 * This profile lifts BM-002 from FIDELITY_PENDING (generic
 * getSampleData fallback) to INPUT_CONNECTED_PARTIAL (route opens,
 * sections labelled, safe synthetic demo, no smart controls).
 *
 * Boundaries honoured here:
 *   - No mutation of the locked contract, the normalized DOCX, or
 *     the compiled contract.
 *   - No DB row creation, no generatedDocumentId fabrication.
 *   - No call to the generated-document save endpoint.
 *   - No smart controls emitted. Hand-curated smart controls are
 *     added by a separate, code-by-code promotion (see BM-001 /
 *     BM-171 for the reference shape).
 *   - No legacy stale tokens in demo (Nguyễn Văn A / Trần Thị B /
 *     1980 / Ông  cung cấp / Nguyễn Thị Hồng Hạnh).
 *
 * Promotion to INPUT_CONNECTED_PASS requires:
 *   - Hand-curated labels for the high-importance fields,
 *   - Smart controls only where evidence permits,
 *   - Golden-render + browser smoke evidence.
 *
 * See `QLLAW_FORM_INPUT_LINKAGE_CONTRACT.latest.md` for the contract
 * status codex.
 */

import {
  type RuntimeUxProfile,
  registerRuntimeUxProfile,
} from "./runtime-ux-profile";

const BM002_SECTIONS = [
  {
    sectionId: "section-agency",
    title: "agency",
  },
  {
    sectionId: "section-document",
    title: "document",
  },
  {
    sectionId: "section-receiver",
    title: "receiver",
  },
  {
    sectionId: "section-sourcereport",
    title: "sourceReport",
  },
  {
    sectionId: "section-reporter",
    title: "reporter",
  },
  {
    sectionId: "section-recipients",
    title: "recipients",
  },
  {
    sectionId: "section-signature",
    title: "signature",
  },
  {
    sectionId: "section-chuyen-nguon-tin",
    title: "Chuyển nguồn tin",
  },
] as const;

const BM002_FIELDS = {
  "agency.parentName": {
    label: "Cơ quan cấp trên",
    placeholder: "Cơ quan cấp trên ",
  },
  "agency.name": {
    label: "Tên cơ quan",
    placeholder: "Tên cơ quan ",
  },
  "document.documentCode": {
    label: "Số văn bản",
    placeholder: "Số văn bản ",
  },
  "document.issuePlaceAndDateLine": {
    label: "Địa điểm, ngày tháng năm",
    placeholder: "Địa điểm , ngày 04 tháng 3 năm 2026",
  },
  "receiver.name": {
    label: "Tên người tiếp nhận",
    placeholder: "Tên người tiếp nhận ",
  },
  "sourceReport.receivedDateLine": {
    label: "Ngày tiếp nhận",
    placeholder: "Địa điểm , ngày 04 tháng 3 năm 2026",
  },
  "agency.bodyName": {
    label: "Tên cơ quan",
    placeholder: "Tên cơ quan ",
  },
  "reporter.fullName": {
    label: "Họ tên người báo tin",
    placeholder: "Họ tên người báo tin ",
  },
  "reporter.genderText": {
    label: "Giới tính",
    placeholder: "Nam",
  },
  "reporter.otherName": {
    label: "Tên gọi khác",
    placeholder: "Tên gọi khác ",
  },
  "reporter.birthDateLine": {
    label: "Sinh ngày",
    placeholder: "Địa điểm , ngày 04 tháng 3 năm 2026",
  },
  "reporter.birthPlace": {
    label: "Nơi sinh",
    placeholder: "Nơi sinh ",
  },
  "reporter.nationality": {
    label: "Quốc tịch",
    placeholder: "Quốc tịch ",
  },
  "reporter.ethnicity": {
    label: "Dân tộc",
    placeholder: "Dân tộc ",
  },
  "reporter.religion": {
    label: "Tôn giáo",
    placeholder: "Tôn giáo ",
  },
  "reporter.occupation": {
    label: "Nghề nghiệp",
    placeholder: "Nghề nghiệp ",
  },
  "reporter.identityNumber": {
    label: "Số CCCD/CMND",
    placeholder: "Số CCCD/CMND ",
  },
  "reporter.identityIssueDateLine": {
    label: "Cấp ngày",
    placeholder: "Địa điểm , ngày 04 tháng 3 năm 2026",
  },
  "reporter.identityIssuePlace": {
    label: "Nơi cấp",
    placeholder: "Nơi cấp ",
  },
  "reporter.permanentResidence": {
    label: "Nơi thường trú",
    placeholder: "Nơi thường trú ",
  },
  "reporter.temporaryResidence": {
    label: "Nơi tạm trú",
    placeholder: "Nơi tạm trú ",
  },
  "reporter.currentResidence": {
    label: "Nơi ở hiện tại",
    placeholder: "Nơi ở hiện tại ",
  },
  "reporter.phoneNumber": {
    label: "Số điện thoại",
    placeholder: "Số điện thoại ",
  },
  "reporter.organizationRepresentative": {
    label: "Người đại diện cơ quan, tổ chức",
    placeholder: "Người đại diện cơ quan, tổ chức ",
  },
  "sourceReport.content": {
    label: "Nội dung",
    placeholder: "Nội dung ",
  },
  "recipients.primaryLine": {
    label: "Nơi nhận",
    placeholder: "Nơi nhận ",
  },
  "recipients.archiveLine": {
    label: "Nơi lưu",
    placeholder: "Lưu: HSVA, HSKS, VP.",
  },
  "signature.positionTitle": {
    label: "Chức vụ",
    placeholder: "Chức vụ ",
  },
  "signature.signerName": {
    label: "Người ký",
    placeholder: "Người ký ",
  },
  "sourceTransfer.attachedItemsDescription": {
    label: "Tài liệu, đồ vật kèm theo",
    placeholder: "Tài liệu, đồ vật kèm theo ",
  },
} as const;

const BM002_DEMO_RUNTIME_UX = {
  "agency.parentName": "Cơ quan cấp trên ",
  "agency.name": "Tên cơ quan ",
  "document.documentCode": "Số văn bản ",
  "document.issuePlaceAndDateLine": "Địa điểm , ngày 04 tháng 3 năm 2026",
  "receiver.name": "Tên người tiếp nhận ",
  "sourceReport.receivedDateLine": "Địa điểm , ngày 04 tháng 3 năm 2026",
  "agency.bodyName": "Tên cơ quan ",
  "reporter.fullName": "Họ tên người báo tin ",
  "reporter.genderText": "Nam",
  "reporter.otherName": "Tên gọi khác ",
  "reporter.birthDateLine": "Địa điểm , ngày 04 tháng 3 năm 2026",
  "reporter.birthPlace": "Nơi sinh ",
  "reporter.nationality": "Quốc tịch ",
  "reporter.ethnicity": "Dân tộc ",
  "reporter.religion": "Tôn giáo ",
  "reporter.occupation": "Nghề nghiệp ",
  "reporter.identityNumber": "Số CCCD/CMND ",
  "reporter.identityIssueDateLine": "Địa điểm , ngày 04 tháng 3 năm 2026",
  "reporter.identityIssuePlace": "Nơi cấp ",
  "reporter.permanentResidence": "Nơi thường trú ",
  "reporter.temporaryResidence": "Nơi tạm trú ",
  "reporter.currentResidence": "Nơi ở hiện tại ",
  "reporter.phoneNumber": "Số điện thoại ",
  "reporter.organizationRepresentative": "Người đại diện cơ quan, tổ chức ",
  "sourceReport.content": "Nội dung ",
  "recipients.primaryLine": "Nơi nhận ",
  "recipients.archiveLine": "Lưu: HSVA, HSKS, VP.",
  "signature.positionTitle": "Chức vụ ",
  "signature.signerName": "Người ký ",
  "sourceTransfer.attachedItemsDescription": "Tài liệu, đồ vật kèm theo ",
} as const;

const BM002_RUNTIME_UX_PROFILE: RuntimeUxProfile = {
  templateCode: "BM-002",
  // Stable version label, surfaced in audit artifacts.
  versionLabel: `BM-002 runtime-ux remaining curated source-render profile`,
  sections: BM002_SECTIONS,
  fields: BM002_FIELDS,
  demo: BM002_DEMO_RUNTIME_UX,
};

registerRuntimeUxProfile(BM002_RUNTIME_UX_PROFILE);
