/**
 * BM-013 runtime-ux remaining curated source-render profile.
 *
 * Generated by: scripts/audit/generate-runtime-ux-profiles.mjs
 * Generator phase: 213-form input linkage, conservative template.
 *
 * This profile lifts BM-013 from FIDELITY_PENDING (generic
 * getSampleData fallback) to INPUT_CONNECTED_PARTIAL (route opens,
 * sections labelled, safe synthetic demo, no smart controls).
 *
 * Boundaries honoured here:
 *   - No mutation of the locked contract, the normalized DOCX, or
 *     the compiled contract.
 *   - No DB row creation, no generatedDocumentId fabrication.
 *   - No call to the generated-document save endpoint.
 *   - No smart controls emitted. Hand-curated smart controls are
 *     added by a separate, code-by-code promotion (see BM-001 /
 *     BM-171 for the reference shape).
 *   - No legacy stale tokens in demo (Nguyễn Văn A / Trần Thị B /
 *     1980 / Ông  cung cấp / Nguyễn Thị Hồng Hạnh).
 *
 * Promotion to INPUT_CONNECTED_PASS requires:
 *   - Hand-curated labels for the high-importance fields,
 *   - Smart controls only where evidence permits,
 *   - Golden-render + browser smoke evidence.
 *
 * See `QLLAW_FORM_INPUT_LINKAGE_CONTRACT.latest.md` for the contract
 * status codex.
 */

import {
  type RuntimeUxProfile,
  registerRuntimeUxProfile,
} from "./runtime-ux-profile";

const BM013_SECTIONS = [
  {
    sectionId: "section-thong-tin-bieu-mau",
    title: "Thông tin biểu mẫu",
  },
] as const;

const BM013_FIELDS = {
  "agency.vienKiem": {
    label: "Tên cơ quan",
    placeholder: "Tên cơ quan ",
  },
  "agency.tenCo": {
    label: "Tên cơ quan",
    placeholder: "Tên cơ quan ",
  },
  "document.vietTat": {
    label: "Tên viết tắt",
    placeholder: "Tên viết tắt ",
  },
  "agency.diaDanh": {
    label: "Địa danh",
    placeholder: "Địa danh ",
  },
  "document.ngayBan": {
    label: "Ngày ban hành",
    placeholder: "Ngày ban hành ",
  },
  "document.soVan": {
    label: "Số văn bản",
    placeholder: "Số văn bản ",
  },
} as const;

const BM013_DEMO_RUNTIME_UX = {
  "agency.vienKiem": "Tên cơ quan ",
  "agency.tenCo": "Tên cơ quan ",
  "document.vietTat": "Tên viết tắt ",
  "agency.diaDanh": "Địa danh ",
  "document.ngayBan": "Ngày ban hành ",
  "document.soVan": "Số văn bản ",
} as const;

const BM013_RUNTIME_UX_PROFILE: RuntimeUxProfile = {
  templateCode: "BM-013",
  // Stable version label, surfaced in audit artifacts.
  versionLabel: `BM-013 runtime-ux remaining curated source-render profile`,
  sections: BM013_SECTIONS,
  fields: BM013_FIELDS,
  demo: BM013_DEMO_RUNTIME_UX,
};

registerRuntimeUxProfile(BM013_RUNTIME_UX_PROFILE);
