/**
 * Auto-generated runtime-ux profile for BM-024.
 *
 * Generated by: scripts/audit/generate-runtime-ux-profiles.mjs
 * Generator phase: 213-form input linkage, conservative template.
 *
 * This profile lifts BM-024 from FIDELITY_PENDING (generic
 * getSampleData fallback) to INPUT_CONNECTED_PARTIAL (route opens,
 * sections labelled, safe synthetic demo, no smart controls).
 *
 * Boundaries honoured here:
 *   - No mutation of the locked contract, the normalized DOCX, or
 *     the compiled contract.
 *   - No DB row creation, no generatedDocumentId fabrication.
 *   - No call to the generated-document save endpoint.
 *   - No smart controls emitted. Hand-curated smart controls are
 *     added by a separate, code-by-code promotion (see BM-001 /
 *     BM-171 for the reference shape).
 *   - No legacy stale tokens in demo (Nguyễn Văn A / Trần Thị B /
 *     1980 / Ông  cung cấp / Nguyễn Thị Hồng Hạnh).
 *
 * Promotion to INPUT_CONNECTED_PASS requires:
 *   - Hand-curated labels for the high-importance fields,
 *   - Smart controls only where evidence permits,
 *   - Golden-render + browser smoke evidence.
 *
 * See `QLLAW_FORM_INPUT_LINKAGE_CONTRACT.latest.md` for the contract
 * status codex.
 */

import {
  type RuntimeUxProfile,
  registerRuntimeUxProfile,
} from "./runtime-ux-profile";

const BM024_SECTIONS = [
  {
    sectionId: "section-thong-tin-bieu-mau",
    title: "Thông tin biểu mẫu",
  },
] as const;

const BM024_FIELDS = {
  "agency.parentNameUpper": {
    label: "Tên cơ quan",
    placeholder: "Tên cơ quan (mẫu BM-024)",
  },
  "agency.issuePlace": {
    label: "Viện kiểm sát ban hành",
    placeholder: "Địa điểm (mẫu BM-024), ngày 04 tháng 3 năm 2026",
  },
  "document.issueDate": {
    label: "Số quyết định",
    placeholder: "Địa điểm (mẫu BM-024), ngày 04 tháng 3 năm 2026",
  },
  "document.issuePlaceAndDateLine": {
    label: "Địa danh, ngày ban hành",
    placeholder: "Địa điểm (mẫu BM-024), ngày 04 tháng 3 năm 2026",
  },
} as const;

const BM024_DEMO_RUNTIME_UX = {
  "agency.parentNameUpper": "Tên cơ quan (mẫu BM-024)",
  "agency.issuePlace": "Địa điểm (mẫu BM-024), ngày 04 tháng 3 năm 2026",
  "document.issueDate": "Địa điểm (mẫu BM-024), ngày 04 tháng 3 năm 2026",
  "document.issuePlaceAndDateLine": "Địa điểm (mẫu BM-024), ngày 04 tháng 3 năm 2026",
} as const;

const BM024_RUNTIME_UX_PROFILE: RuntimeUxProfile = {
  templateCode: "BM-024",
  // Stable version label, surfaced in audit artifacts.
  versionLabel: `BM-024 runtime-ux auto-generated conservative profile`,
  sections: BM024_SECTIONS,
  fields: BM024_FIELDS,
  demo: BM024_DEMO_RUNTIME_UX,
};

registerRuntimeUxProfile(BM024_RUNTIME_UX_PROFILE);
