/**
 * Auto-generated runtime-ux profile for BM-039.
 *
 * Generated by: scripts/audit/generate-runtime-ux-profiles.mjs
 * Generator phase: 213-form input linkage, conservative template.
 *
 * This profile lifts BM-039 from FIDELITY_PENDING (generic
 * getSampleData fallback) to INPUT_CONNECTED_PARTIAL (route opens,
 * sections labelled, safe synthetic demo, no smart controls).
 *
 * Boundaries honoured here:
 *   - No mutation of the locked contract, the normalized DOCX, or
 *     the compiled contract.
 *   - No DB row creation, no generatedDocumentId fabrication.
 *   - No call to the generated-document save endpoint.
 *   - No smart controls emitted. Hand-curated smart controls are
 *     added by a separate, code-by-code promotion (see BM-001 /
 *     BM-171 for the reference shape).
 *   - No legacy stale tokens in demo (Nguyễn Văn A / Trần Thị B /
 *     1980 / Ông  cung cấp / Nguyễn Thị Hồng Hạnh).
 *
 * Promotion to INPUT_CONNECTED_PASS requires:
 *   - Hand-curated labels for the high-importance fields,
 *   - Smart controls only where evidence permits,
 *   - Golden-render + browser smoke evidence.
 *
 * See `QLLAW_FORM_INPUT_LINKAGE_CONTRACT.latest.md` for the contract
 * status codex.
 */

import {
  type RuntimeUxProfile,
  registerRuntimeUxProfile,
} from "./runtime-ux-profile";

const BM039_SECTIONS = [
  {
    sectionId: "section-co-quan-va-van-ban",
    title: "Cơ quan và văn bản",
  },
  {
    sectionId: "section-can-cu-phap-ly",
    title: "Căn cứ pháp lý",
  },
  {
    sectionId: "section-thong-tin-nhan-than-bi-can",
    title: "Thông tin nhân thân bị can",
  },
  {
    sectionId: "section-noi-dung-quyet-inh",
    title: "Nội dung quyết định",
  },
  {
    sectionId: "section-noi-nhan",
    title: "Nơi nhận",
  },
  {
    sectionId: "section-chu-ky",
    title: "Chữ ký",
  },
] as const;

const BM039_FIELDS = {
  "agency.parentNameUpper": {
    label: "Cơ quan cấp trên (IN HOA)",
    placeholder: "Cơ quan cấp trên (IN HOA) (mẫu BM-039)",
  },
  "agency.nameUpper": {
    label: "Viện kiểm sát ban hành (IN HOA)",
    placeholder: "Viện kiểm sát ban hành (IN HOA) (mẫu BM-039)",
  },
  "document.documentCode": {
    label: "Số quyết định",
    placeholder: "Số quyết định (mẫu BM-039)",
  },
  "document.issuePlaceAndDateLine": {
    label: "Địa danh, ngày ban hành",
    placeholder: "Địa điểm (mẫu BM-039), ngày 04 tháng 3 năm 2026",
  },
  "official.issuingAuthorityLine": {
    label: "Cơ quan ban hành (dòng chữ in trên đầu)",
    placeholder: "Cơ quan ban hành (dòng chữ in trên đầu) (mẫu BM-039)",
  },
  "legalBasis.procedureArticlesLine": {
    label: "Căn cứ Bộ luật Tố tụng hình sự",
    placeholder: "Căn cứ Bộ luật Tố tụng hình sự (mẫu BM-039)",
  },
  "legalBasis.juvenileJusticeLine": {
    label: "Căn cứ pháp luật về vi phạm hành chính",
    placeholder: "Căn cứ pháp luật về vi phạm hành chính (mẫu BM-039)",
  },
  "detentionArrest.caseDecisionLegalBasisLine": {
    label: "Căn cứ quyết định khởi tố vụ án",
    placeholder: "Căn cứ quyết định khởi tố vụ án (mẫu BM-039)",
  },
  "detentionArrest.accusedDecisionLegalBasisLine": {
    label: "Căn cứ quyết định về bị can",
    placeholder: "Căn cứ quyết định về bị can (mẫu BM-039)",
  },
  "detentionArrest.reasonLine": {
    label: "Lý do phê chuẩn lệnh bắt và tạm giam",
    placeholder: "Lý do phê chuẩn lệnh bắt và tạm giam (mẫu BM-039)",
  },
  "detentionArrest.accusedName": {
    label: "Họ tên bị can",
    placeholder: "Họ tên bị can (mẫu BM-039)",
  },
  "detentionArrest.genderLabel": {
    label: "Giới tính",
    placeholder: "Giới tính (mẫu BM-039)",
  },
  "detentionArrest.otherName": {
    label: "Tên gọi khác",
    placeholder: "Tên gọi khác (mẫu BM-039)",
  },
  "detentionArrest.birthDay": {
    label: "Ngày sinh",
    placeholder: "01",
  },
  "detentionArrest.birthMonth": {
    label: "Tháng sinh",
    placeholder: "01",
  },
  "detentionArrest.birthYear": {
    label: "Năm sinh",
    placeholder: "1985",
  },
  "detentionArrest.placeOfBirth": {
    label: "Nơi sinh",
    placeholder: "Nơi sinh (mẫu BM-039)",
  },
  "detentionArrest.nationality": {
    label: "Quốc tịch",
    placeholder: "Quốc tịch (mẫu BM-039)",
  },
  "detentionArrest.ethnicity": {
    label: "Dân tộc",
    placeholder: "Dân tộc (mẫu BM-039)",
  },
  "detentionArrest.religion": {
    label: "Tôn giáo",
    placeholder: "Tôn giáo (mẫu BM-039)",
  },
  "detentionArrest.occupation": {
    label: "Nghề nghiệp",
    placeholder: "Nghề nghiệp (mẫu BM-039)",
  },
  "detentionArrest.identityNo": {
    label: "Số CMND/CCCD",
    placeholder: "Số CMND/CCCD (mẫu BM-039)",
  },
  "detentionArrest.identityIssuedDay": {
    label: "Ngày cấp CMND/CCCD",
    placeholder: "04",
  },
  "detentionArrest.identityIssuedMonth": {
    label: "Tháng cấp CMND/CCCD",
    placeholder: "03",
  },
  "detentionArrest.identityIssuedYear": {
    label: "Năm cấp CMND/CCCD",
    placeholder: "2026",
  },
  "detentionArrest.identityIssuedPlace": {
    label: "Nơi cấp CMND/CCCD",
    placeholder: "Nơi cấp CMND/CCCD (mẫu BM-039)",
  },
  "detentionArrest.permanentAddress": {
    label: "Nơi thường trú",
    placeholder: "Nơi thường trú (mẫu BM-039)",
  },
  "detentionArrest.temporaryAddress": {
    label: "Nơi tạm trú",
    placeholder: "Nơi tạm trú (mẫu BM-039)",
  },
  "detentionArrest.currentAddress": {
    label: "Nơi ở hiện tại",
    placeholder: "Nơi ở hiện tại (mẫu BM-039)",
  },
  "detentionArrest.detentionDurationText": {
    label: "Thời hạn tạm giam",
    placeholder: "Thời hạn tạm giam (mẫu BM-039)",
  },
  "detentionArrest.detentionToDateLine": {
    label: "Thời hạn đến ngày",
    placeholder: "Địa điểm (mẫu BM-039), ngày 04 tháng 3 năm 2026",
  },
  "detentionArrest.detentionExecutionUnitName": {
    label: "Đơn vị thi hành",
    placeholder: "Đơn vị thi hành (mẫu BM-039)",
  },
  "detentionArrest.detentionFacilityName": {
    label: "Cơ sở giam giữ",
    placeholder: "Cơ sở giam giữ (mẫu BM-039)",
  },
  "recipients.executionAgencyLine": {
    label: "Nơi nhận - Cơ quan thi hành",
    placeholder: "Nơi nhận - Cơ quan thi hành (mẫu BM-039)",
  },
  "recipients.detentionFacilityLine": {
    label: "Nơi nhận - Cơ sở giam giữ",
    placeholder: "Nơi nhận - Cơ sở giam giữ (mẫu BM-039)",
  },
  "recipients.personLine": {
    label: "Nơi nhận - Bị can",
    placeholder: "Nơi nhận - Bị can (mẫu BM-039)",
  },
  "recipients.archiveLine": {
    label: "Lưu hồ sơ",
    placeholder: "Lưu: HSVA, HSKS, VP.",
  },
  "signature.signMode": {
    label: "Chế độ ký",
    placeholder: "Chế độ ký (mẫu BM-039)",
  },
  "signature.positionTitle": {
    label: "Chức vụ người ký",
    placeholder: "Chức vụ người ký (mẫu BM-039)",
  },
  "signature.signerName": {
    label: "Người ký",
    placeholder: "Người ký (mẫu BM-039)",
  },
} as const;

const BM039_DEMO_RUNTIME_UX = {
  "agency.parentNameUpper": "Cơ quan cấp trên (IN HOA) (mẫu BM-039)",
  "agency.nameUpper": "Viện kiểm sát ban hành (IN HOA) (mẫu BM-039)",
  "document.documentCode": "Số quyết định (mẫu BM-039)",
  "document.issuePlaceAndDateLine": "Địa điểm (mẫu BM-039), ngày 04 tháng 3 năm 2026",
  "official.issuingAuthorityLine": "Cơ quan ban hành (dòng chữ in trên đầu) (mẫu BM-039)",
  "legalBasis.procedureArticlesLine": "Căn cứ Bộ luật Tố tụng hình sự (mẫu BM-039)",
  "legalBasis.juvenileJusticeLine": "Căn cứ pháp luật về vi phạm hành chính (mẫu BM-039)",
  "detentionArrest.caseDecisionLegalBasisLine": "Căn cứ quyết định khởi tố vụ án (mẫu BM-039)",
  "detentionArrest.accusedDecisionLegalBasisLine": "Căn cứ quyết định về bị can (mẫu BM-039)",
  "detentionArrest.reasonLine": "Lý do phê chuẩn lệnh bắt và tạm giam (mẫu BM-039)",
  "detentionArrest.accusedName": "Họ tên bị can (mẫu BM-039)",
  "detentionArrest.genderLabel": "Giới tính (mẫu BM-039)",
  "detentionArrest.otherName": "Tên gọi khác (mẫu BM-039)",
  "detentionArrest.birthDay": "01",
  "detentionArrest.birthMonth": "01",
  "detentionArrest.birthYear": "1985",
  "detentionArrest.placeOfBirth": "Nơi sinh (mẫu BM-039)",
  "detentionArrest.nationality": "Quốc tịch (mẫu BM-039)",
  "detentionArrest.ethnicity": "Dân tộc (mẫu BM-039)",
  "detentionArrest.religion": "Tôn giáo (mẫu BM-039)",
  "detentionArrest.occupation": "Nghề nghiệp (mẫu BM-039)",
  "detentionArrest.identityNo": "Số CMND/CCCD (mẫu BM-039)",
  "detentionArrest.identityIssuedDay": "04",
  "detentionArrest.identityIssuedMonth": "03",
  "detentionArrest.identityIssuedYear": "2026",
  "detentionArrest.identityIssuedPlace": "Nơi cấp CMND/CCCD (mẫu BM-039)",
  "detentionArrest.permanentAddress": "Nơi thường trú (mẫu BM-039)",
  "detentionArrest.temporaryAddress": "Nơi tạm trú (mẫu BM-039)",
  "detentionArrest.currentAddress": "Nơi ở hiện tại (mẫu BM-039)",
  "detentionArrest.detentionDurationText": "Thời hạn tạm giam (mẫu BM-039)",
  "detentionArrest.detentionToDateLine": "Địa điểm (mẫu BM-039), ngày 04 tháng 3 năm 2026",
  "detentionArrest.detentionExecutionUnitName": "Đơn vị thi hành (mẫu BM-039)",
  "detentionArrest.detentionFacilityName": "Cơ sở giam giữ (mẫu BM-039)",
  "recipients.executionAgencyLine": "Nơi nhận - Cơ quan thi hành (mẫu BM-039)",
  "recipients.detentionFacilityLine": "Nơi nhận - Cơ sở giam giữ (mẫu BM-039)",
  "recipients.personLine": "Nơi nhận - Bị can (mẫu BM-039)",
  "recipients.archiveLine": "Lưu: HSVA, HSKS, VP.",
  "signature.signMode": "Chế độ ký (mẫu BM-039)",
  "signature.positionTitle": "Chức vụ người ký (mẫu BM-039)",
  "signature.signerName": "Người ký (mẫu BM-039)",
} as const;

const BM039_RUNTIME_UX_PROFILE: RuntimeUxProfile = {
  templateCode: "BM-039",
  // Stable version label, surfaced in audit artifacts.
  versionLabel: `BM-039 runtime-ux auto-generated conservative profile`,
  sections: BM039_SECTIONS,
  fields: BM039_FIELDS,
  demo: BM039_DEMO_RUNTIME_UX,
};

registerRuntimeUxProfile(BM039_RUNTIME_UX_PROFILE);
