/**
 * Auto-generated runtime-ux profile for BM-041.
 *
 * Generated by: scripts/audit/generate-runtime-ux-profiles.mjs
 * Generator phase: 213-form input linkage, conservative template.
 *
 * This profile lifts BM-041 from FIDELITY_PENDING (generic
 * getSampleData fallback) to INPUT_CONNECTED_PARTIAL (route opens,
 * sections labelled, safe synthetic demo, no smart controls).
 *
 * Boundaries honoured here:
 *   - No mutation of the locked contract, the normalized DOCX, or
 *     the compiled contract.
 *   - No DB row creation, no generatedDocumentId fabrication.
 *   - No call to the generated-document save endpoint.
 *   - No smart controls emitted. Hand-curated smart controls are
 *     added by a separate, code-by-code promotion (see BM-001 /
 *     BM-171 for the reference shape).
 *   - No legacy stale tokens in demo (Nguyễn Văn A / Trần Thị B /
 *     1980 / Ông  cung cấp / Nguyễn Thị Hồng Hạnh).
 *
 * Note: BM-041's compiled contract carries only three fields
 * (agency.parentNameUpper, agency.issuePlace, document.documentCode)
 * with no `document.issuePlaceAndDateLine` slot. The canonical
 * `issue-place-date-line` smart cannot be applied. Promotion to
 * INPUT_CONNECTED_PASS would require either a contract amendment or
 * a custom smart mode — out of scope for this batch.
 */

import {
  type RuntimeUxProfile,
  registerRuntimeUxProfile,
} from "./runtime-ux-profile";

const BM041_SECTIONS = [
  {
    sectionId: "section-thong-tin-bieu-mau",
    title: "Thông tin biểu mẫu",
  },
] as const;

const BM041_FIELDS = {
  "agency.parentNameUpper": {
    label: "Tên cơ quan (viết hoa)",
    placeholder: "Tên cơ quan (mẫu BM-041)",
  },
  "agency.issuePlace": {
    label: "Địa điểm ban hành",
    placeholder: "Địa điểm ban hành (mẫu BM-041)",
  },
  "document.documentCode": {
    label: "Số văn bản",
    placeholder: "Số văn bản (mẫu BM-041)",
  },
} as const;

const BM041_DEMO_RUNTIME_UX = {
  "agency.parentNameUpper": "Tên cơ quan (mẫu BM-041)",
  "agency.issuePlace": "Địa điểm ban hành (mẫu BM-041)",
  "document.documentCode": "Số văn bản (mẫu BM-041)",
} as const;

const BM041_RUNTIME_UX_PROFILE: RuntimeUxProfile = {
  templateCode: "BM-041",
  // Stable version label, surfaced in audit artifacts.
  versionLabel: `BM-041 runtime-ux auto-generated conservative profile`,
  sections: BM041_SECTIONS,
  fields: BM041_FIELDS,
  demo: BM041_DEMO_RUNTIME_UX,
};

registerRuntimeUxProfile(BM041_RUNTIME_UX_PROFILE);
