/**
 * Auto-generated runtime-ux profile for BM-051.
 *
 * Generated by: scripts/audit/generate-runtime-ux-profiles.mjs
 * Generator phase: 213-form input linkage, conservative template.
 *
 * This profile lifts BM-051 from FIDELITY_PENDING (generic
 * getSampleData fallback) to INPUT_CONNECTED_PARTIAL (route opens,
 * sections labelled, safe synthetic demo, no smart controls).
 *
 * Boundaries honoured here:
 *   - No mutation of the locked contract, the normalized DOCX, or
 *     the compiled contract.
 *   - No DB row creation, no generatedDocumentId fabrication.
 *   - No call to the generated-document save endpoint.
 *   - No smart controls emitted. Hand-curated smart controls are
 *     added by a separate, code-by-code promotion (see BM-001 /
 *     BM-171 for the reference shape).
 *   - No legacy stale tokens in demo (Nguyễn Văn A / Trần Thị B /
 *     1980 / Ông  cung cấp / Nguyễn Thị Hồng Hạnh).
 *
 * Note: BM-051 carries only three fields and no separate day/month/year
 * targets, so the curated-batch smart-mandatory invariant does not
 * apply.
 */

import {
  type RuntimeUxProfile,
  registerRuntimeUxProfile,
} from "./runtime-ux-profile";

const BM051_SECTIONS = [
  {
    sectionId: "section-thong-tin-bieu-mau",
    title: "Thông tin biểu mẫu",
  },
] as const;

const BM051_FIELDS = {
  "agency.name": {
    label: "Tên cơ quan",
    placeholder: "Tên cơ quan (mẫu BM-051)",
  },
  "document.fullDocumentCode": {
    label: "Số văn bản",
    placeholder: "Số văn bản (mẫu BM-051)",
  },
  "decision.decisionLine3": {
    label: "Địa điểm, ngày lập",
    placeholder: "Địa điểm (mẫu BM-051), ngày 04 tháng 3 năm 2026",
  },
} as const;

const BM051_DEMO_RUNTIME_UX = {
  "agency.name": "Tên cơ quan (mẫu BM-051)",
  "document.fullDocumentCode": "Số văn bản (mẫu BM-051)",
  "decision.decisionLine3": "Địa điểm (mẫu BM-051), ngày 04 tháng 3 năm 2026",
} as const;

const BM051_RUNTIME_UX_PROFILE: RuntimeUxProfile = {
  templateCode: "BM-051",
  // Stable version label, surfaced in audit artifacts.
  versionLabel: `BM-051 runtime-ux auto-generated conservative profile`,
  sections: BM051_SECTIONS,
  fields: BM051_FIELDS,
  demo: BM051_DEMO_RUNTIME_UX,
};

registerRuntimeUxProfile(BM051_RUNTIME_UX_PROFILE);
