/**
 * Auto-generated runtime-ux profile for BM-050.
 *
 * Generated by: scripts/audit/generate-runtime-ux-profiles.mjs
 * Generator phase: 213-form input linkage, conservative template.
 *
 * This profile lifts BM-050 from FIDELITY_PENDING (generic
 * getSampleData fallback) to INPUT_CONNECTED_PARTIAL (route opens,
 * sections labelled, safe synthetic demo, no smart controls).
 *
 * Boundaries honoured here:
 *   - No mutation of the locked contract, the normalized DOCX, or
 *     the compiled contract.
 *   - No DB row creation, no generatedDocumentId fabrication.
 *   - No call to the generated-document save endpoint.
 *   - No smart controls emitted. Hand-curated smart controls are
 *     added by a separate, code-by-code promotion (see BM-001 /
 *     BM-171 for the reference shape).
 *   - No legacy stale tokens in demo (Nguyễn Văn A / Trần Thị B /
 *     1980 / Ông  cung cấp / Nguyễn Thị Hồng Hạnh).
 *
 * Promotion to INPUT_CONNECTED_PASS requires:
 *   - Hand-curated labels for the high-importance fields,
 *   - Smart controls only where evidence permits,
 *   - Golden-render + browser smoke evidence.
 *
 * See `QLLAW_FORM_INPUT_LINKAGE_CONTRACT.latest.md` for the contract
 * status codex.
 */

import {
  type RuntimeUxProfile,
  registerRuntimeUxProfile,
} from "./runtime-ux-profile";

const BM050_SECTIONS = [
  {
    sectionId: "section-thong-tin-bieu-mau",
    title: "Thông tin biểu mẫu",
  },
] as const;

const BM050_FIELDS = {
  "agency.tenVien": {
    label: "Tên cơ quan",
    placeholder: "Tên cơ quan (mẫu BM-050)",
  },
  "agency.coQuan": {
    label: "Cơ quan",
    placeholder: "Cơ quan (mẫu BM-050)",
  },
  "agency.diaDanh": {
    label: "Địa danh",
    placeholder: "Địa danh (mẫu BM-050)",
  },
} as const;

const BM050_DEMO_RUNTIME_UX = {
  "agency.tenVien": "Tên cơ quan (mẫu BM-050)",
  "agency.coQuan": "Cơ quan (mẫu BM-050)",
  "agency.diaDanh": "Địa danh (mẫu BM-050)",
} as const;

const BM050_RUNTIME_UX_PROFILE: RuntimeUxProfile = {
  templateCode: "BM-050",
  // Stable version label, surfaced in audit artifacts.
  versionLabel: `BM-050 runtime-ux auto-generated conservative profile`,
  sections: BM050_SECTIONS,
  fields: BM050_FIELDS,
  demo: BM050_DEMO_RUNTIME_UX,
};

registerRuntimeUxProfile(BM050_RUNTIME_UX_PROFILE);
