/**
 * Auto-generated runtime-ux profile for BM-103.
 *
 * Generated by: scripts/audit/generate-runtime-ux-profiles.mjs
 * Generator phase: 213-form input linkage, conservative template.
 *
 * This profile lifts BM-103 from FIDELITY_PENDING (generic
 * getSampleData fallback) to INPUT_CONNECTED_PARTIAL (route opens,
 * sections labelled, safe synthetic demo, no smart controls).
 *
 * Boundaries honoured here:
 *   - No mutation of the locked contract, the normalized DOCX, or
 *     the compiled contract.
 *   - No DB row creation, no generatedDocumentId fabrication.
 *   - No call to the generated-document save endpoint.
 *   - No smart controls emitted. Hand-curated smart controls are
 *     added by a separate, code-by-code promotion (see BM-001 /
 *     BM-171 for the reference shape).
 *   - No legacy stale tokens in demo (Nguyễn Văn A / Trần Thị B /
 *     1980 / Ông  cung cấp / Nguyễn Thị Hồng Hạnh).
 *
 * Promotion to INPUT_CONNECTED_PASS requires:
 *   - Hand-curated labels for the high-importance fields,
 *   - Smart controls only where evidence permits,
 *   - Golden-render + browser smoke evidence.
 *
 * See `QLLAW_FORM_INPUT_LINKAGE_CONTRACT.latest.md` for the contract
 * status codex.
 */

import {
  type RuntimeUxProfile,
  registerRuntimeUxProfile,
} from "./runtime-ux-profile";

const BM103_SECTIONS = [
  {
    sectionId: "section-co-quan-va-van-ban",
    title: "Cơ quan và văn bản",
  },
  {
    sectionId: "section-can-cu-phap-ly",
    title: "Căn cứ pháp lý",
  },
  {
    sectionId: "section-noi-nhan",
    title: "Nơi nhận",
  },
  {
    sectionId: "section-chu-ky",
    title: "Chữ ký",
  },
] as const;

const BM103_FIELDS = {
  "agency.parentName": {
    label: "Cơ quan cấp trên",
    placeholder: "Cơ quan cấp trên (mẫu BM-103)",
  },
  "agency.name": {
    label: "Viện kiểm sát ban hành",
    placeholder: "Viện kiểm sát ban hành (mẫu BM-103)",
  },
  "document.documentCode": {
    label: "Số quyết định",
    placeholder: "Số quyết định (mẫu BM-103)",
  },
  "document.issuePlaceAndDateLine": {
    label: "Địa danh, ngày ban hành",
    placeholder: "Địa điểm (mẫu BM-103), ngày 04 tháng 3 năm 2026",
  },
  "recipients.superiorProcuracyName": {
    label: "Tên Viện kiểm sát cấp trên",
    placeholder: "Tên Viện kiểm sát cấp trên (mẫu BM-103)",
  },
  "legalBasis.procedureArticlesLine": {
    label: "Căn cứ Bộ luật Tố tụng hình sự",
    placeholder: "Căn cứ Bộ luật Tố tụng hình sự (mẫu BM-103)",
  },
  "caseDecision.prosecutionDecisionLegalBasisLine": {
    label: "Căn cứ quyết định truy tố",
    placeholder: "Căn cứ quyết định truy tố (mẫu BM-103)",
  },
  "investigationExtension.previousDecisionLegalBasisLine": {
    label: "Căn cứ quyết định gia hạn trước",
    placeholder: "Căn cứ quyết định gia hạn trước (mẫu BM-103)",
  },
  "proposal.requestingDocumentLine": {
    label: "Đề nghị tại văn bản",
    placeholder: "Đề nghị tại văn bản (mẫu BM-103)",
  },
  "proposal.proposingProcuracyName": {
    label: "Tên Viện kiểm sát đề nghị",
    placeholder: "Tên Viện kiểm sát đề nghị (mẫu BM-103)",
  },
  "investigationExtension.requestRoundText": {
    label: "Lần đề nghị gia hạn",
    placeholder: "Lần đề nghị gia hạn (mẫu BM-103)",
  },
  "caseDecision.prosecutionDecisionSummaryLine": {
    label: "Tóm tắt quyết định truy tố",
    placeholder: "Tóm tắt quyết định truy tố (mẫu BM-103)",
  },
  "investigationExtension.durationText": {
    label: "Thời hạn gia hạn",
    placeholder: "Thời hạn gia hạn (mẫu BM-103)",
  },
  "investigationExtension.fromDateText": {
    label: "Từ ngày",
    placeholder: "Từ ngày (mẫu BM-103)",
  },
  "investigationExtension.toDateText": {
    label: "Đến ngày",
    placeholder: "Đến ngày (mẫu BM-103)",
  },
  "recipients.superiorProcuracyLine": {
    label: "Nơi nhận - VKS cấp trên",
    placeholder: "Nơi nhận - VKS cấp trên (mẫu BM-103)",
  },
  "recipients.investigatingAgencyLine": {
    label: "Nơi nhận - CQĐT",
    placeholder: "Nơi nhận - CQĐT (mẫu BM-103)",
  },
  "recipients.archiveLine": {
    label: "Lưu hồ sơ",
    placeholder: "Lưu: HSVA, HSKS, VP.",
  },
  "signature.signMode": {
    label: "Chế độ ký",
    placeholder: "Chế độ ký (mẫu BM-103)",
  },
  "signature.positionTitle": {
    label: "Chức vụ người ký",
    placeholder: "Chức vụ người ký (mẫu BM-103)",
  },
  "signature.signerName": {
    label: "Người ký",
    placeholder: "Người ký (mẫu BM-103)",
  },
} as const;

const BM103_DEMO_RUNTIME_UX = {
  "agency.parentName": "VIỆN KIỂM SÁT NHÂN DÂN THÀNH PHỐ HỒ CHÍ MINH",
  "agency.name": "Viện kiểm sát nhân dân khu vực 7",
  "document.documentCode": "12/QĐ-VKSKV7",
  "document.issuePlaceAndDateLine": "Thành phố Hồ Chí Minh, ngày 15 tháng 7 năm 2026",
  "recipients.superiorProcuracyName": "Viện kiểm sát nhân dân Thành phố Hồ Chí Minh",
  "legalBasis.procedureArticlesLine": "Căn cứ các điều 41, 236 và 240 Bộ luật Tố tụng hình sự",
  "caseDecision.prosecutionDecisionLegalBasisLine": "Căn cứ Quyết định truy tố số 08/QĐ-VKSKV7 ngày 10/07/2026",
  "investigationExtension.previousDecisionLegalBasisLine": "Căn cứ Quyết định gia hạn điều tra số 05/QĐ-VKSKV7 ngày 20/06/2026",
  "proposal.requestingDocumentLine": "Xét văn bản đề nghị số 18/CQĐT ngày 12/07/2026",
  "proposal.proposingProcuracyName": "Viện kiểm sát nhân dân khu vực 7",
  "investigationExtension.requestRoundText": "lần thứ nhất",
  "caseDecision.prosecutionDecisionSummaryLine": "Quyết định truy tố đối với bị can Lê Minh K về tội Lạm dụng tín nhiệm chiếm đoạt tài sản",
  "investigationExtension.durationText": "02 tháng",
  "investigationExtension.fromDateText": "từ ngày 16/07/2026",
  "investigationExtension.toDateText": "đến ngày 16/09/2026",
  "recipients.superiorProcuracyLine": "Viện kiểm sát nhân dân Thành phố Hồ Chí Minh",
  "recipients.investigatingAgencyLine": "Cơ quan Cảnh sát điều tra Công an Thành phố Hồ Chí Minh",
  "recipients.archiveLine": "Lưu: HSVA, HSKS, VP.",
  "signature.signMode": "KT. VIỆN TRƯỞNG",
  "signature.positionTitle": "PHÓ VIỆN TRƯỞNG",
  "signature.signerName": "Trần Minh Quang",
} as const;

const BM103_RUNTIME_UX_PROFILE: RuntimeUxProfile = {
  templateCode: "BM-103",
  // Stable version label, surfaced in audit artifacts.
  versionLabel: `BM-103 runtime-ux batch 5 curated source-render profile`,
  sections: BM103_SECTIONS,
  fields: BM103_FIELDS,
  demo: BM103_DEMO_RUNTIME_UX,
};

registerRuntimeUxProfile(BM103_RUNTIME_UX_PROFILE);
