/**
 * Auto-generated runtime-ux profile for BM-104.
 *
 * Generated by: scripts/audit/generate-runtime-ux-profiles.mjs
 * Generator phase: 213-form input linkage, conservative template.
 *
 * This profile lifts BM-104 from FIDELITY_PENDING (generic
 * getSampleData fallback) to INPUT_CONNECTED_PARTIAL (route opens,
 * sections labelled, safe synthetic demo, no smart controls).
 *
 * Boundaries honoured here:
 *   - No mutation of the locked contract, the normalized DOCX, or
 *     the compiled contract.
 *   - No DB row creation, no generatedDocumentId fabrication.
 *   - No call to the generated-document save endpoint.
 *   - No smart controls emitted. Hand-curated smart controls are
 *     added by a separate, code-by-code promotion (see BM-001 /
 *     BM-171 for the reference shape).
 *   - No legacy stale tokens in demo (Nguyễn Văn A / Trần Thị B /
 *     1980 / Ông  cung cấp / Nguyễn Thị Hồng Hạnh).
 *
 * Promotion to INPUT_CONNECTED_PASS requires:
 *   - Hand-curated labels for the high-importance fields,
 *   - Smart controls only where evidence permits,
 *   - Golden-render + browser smoke evidence.
 *
 * See `QLLAW_FORM_INPUT_LINKAGE_CONTRACT.latest.md` for the contract
 * status codex.
 */

import {
  type RuntimeUxProfile,
  registerRuntimeUxProfile,
} from "./runtime-ux-profile";

const BM104_SECTIONS = [
  {
    sectionId: "section-co-quan-va-van-ban",
    title: "Cơ quan và văn bản",
  },
  {
    sectionId: "section-can-cu-phap-ly",
    title: "Căn cứ pháp lý",
  },
  {
    sectionId: "section-noi-dung-quyet-inh",
    title: "Nội dung quyết định",
  },
  {
    sectionId: "section-noi-nhan",
    title: "Nơi nhận",
  },
  {
    sectionId: "section-chu-ky",
    title: "Chữ ký",
  },
] as const;

const BM104_FIELDS = {
  "agency.parentName": {
    label: "Cơ quan cấp trên",
    placeholder: "Cơ quan cấp trên (mẫu BM-104)",
  },
  "agency.name": {
    label: "Viện kiểm sát ban hành",
    placeholder: "Viện kiểm sát ban hành (mẫu BM-104)",
  },
  "document.documentCode": {
    label: "Số quyết định",
    placeholder: "Số quyết định (mẫu BM-104)",
  },
  "document.issuePlaceAndDateLine": {
    label: "Địa danh, ngày ban hành",
    placeholder: "Địa điểm (mẫu BM-104), ngày 04 tháng 3 năm 2026",
  },
  "investigationExtension.requestRoundText": {
    label: "Lần đề nghị thu hồi",
    placeholder: "Lần đề nghị thu hồi (mẫu BM-104)",
  },
  "official.issuerTitle": {
    label: "Chủ thể ban hành",
    placeholder: "Chủ thể ban hành (mẫu BM-104)",
  },
  "legalBasis.procedureArticlesLine": {
    label: "Căn cứ Bộ luật Tố tụng hình sự",
    placeholder: "Căn cứ Bộ luật Tố tụng hình sự (mẫu BM-104)",
  },
  "caseDecision.prosecutionDecisionLegalBasisLine": {
    label: "Căn cứ quyết định truy tố",
    placeholder: "Căn cứ quyết định truy tố (mẫu BM-104)",
  },
  "investigationRecovery.legalBasisLine": {
    label: "Căn cứ thu hồi điều tra",
    placeholder: "Căn cứ thu hồi điều tra (mẫu BM-104)",
  },
  "proposal.requestingDocumentLine": {
    label: "Đề nghị tại văn bản",
    placeholder: "Đề nghị tại văn bản (mẫu BM-104)",
  },
  "investigationExtension.reasonLine": {
    label: "Lý do thu hồi",
    placeholder: "Lý do thu hồi (mẫu BM-104)",
  },
  "investigationExtension.decisionArticle1Line": {
    label: "Điều 1 - Thu hồi điều tra",
    placeholder: "Điều 1 - Thu hồi điều tra (mẫu BM-104)",
  },
  "investigationExtension.decisionArticle2Line": {
    label: "Điều 2 - Thời hạn",
    placeholder: "Điều 2 - Thời hạn (mẫu BM-104)",
  },
  "recipients.investigatingAgencyLine": {
    label: "Nơi nhận - CQĐT",
    placeholder: "Nơi nhận - CQĐT (mẫu BM-104)",
  },
  "recipients.archiveLine": {
    label: "Lưu hồ sơ",
    placeholder: "Lưu: HSVA, HSKS, VP.",
  },
  "signature.signMode": {
    label: "Chế độ ký",
    placeholder: "Chế độ ký (mẫu BM-104)",
  },
  "signature.positionTitle": {
    label: "Chức vụ người ký",
    placeholder: "Chức vụ người ký (mẫu BM-104)",
  },
  "signature.signerName": {
    label: "Người ký",
    placeholder: "Người ký (mẫu BM-104)",
  },
} as const;

const BM104_DEMO_RUNTIME_UX = {
  "agency.parentName": "VIỆN KIỂM SÁT NHÂN DÂN THÀNH PHỐ HỒ CHÍ MINH",
  "agency.name": "Viện kiểm sát nhân dân khu vực 7",
  "document.documentCode": "12/QĐ-VKSKV7",
  "document.issuePlaceAndDateLine": "Thành phố Hồ Chí Minh, ngày 15 tháng 7 năm 2026",
  "investigationExtension.requestRoundText": "lần thứ nhất",
  "official.issuerTitle": "Viện trưởng Viện kiểm sát nhân dân khu vực 7",
  "legalBasis.procedureArticlesLine": "Căn cứ các điều 41, 236 và 240 Bộ luật Tố tụng hình sự",
  "caseDecision.prosecutionDecisionLegalBasisLine": "Căn cứ Quyết định truy tố số 08/QĐ-VKSKV7 ngày 10/07/2026",
  "investigationRecovery.legalBasisLine": "Căn cứ quyết định phục hồi điều tra theo Bộ luật Tố tụng hình sự",
  "proposal.requestingDocumentLine": "Xét văn bản đề nghị số 18/CQĐT ngày 12/07/2026",
  "investigationExtension.reasonLine": "do vụ án có nhiều tài liệu cần xác minh bổ sung",
  "investigationExtension.decisionArticle1Line": "Gia hạn thời hạn điều tra vụ án thêm 02 tháng.",
  "investigationExtension.decisionArticle2Line": "Cơ quan điều tra có trách nhiệm thi hành quyết định này.",
  "recipients.investigatingAgencyLine": "Cơ quan Cảnh sát điều tra Công an Thành phố Hồ Chí Minh",
  "recipients.archiveLine": "Lưu: HSVA, HSKS, VP.",
  "signature.signMode": "KT. VIỆN TRƯỞNG",
  "signature.positionTitle": "PHÓ VIỆN TRƯỞNG",
  "signature.signerName": "Trần Minh Quang",
} as const;

const BM104_RUNTIME_UX_PROFILE: RuntimeUxProfile = {
  templateCode: "BM-104",
  // Stable version label, surfaced in audit artifacts.
  versionLabel: `BM-104 runtime-ux batch 5 curated source-render profile`,
  sections: BM104_SECTIONS,
  fields: BM104_FIELDS,
  demo: BM104_DEMO_RUNTIME_UX,
};

registerRuntimeUxProfile(BM104_RUNTIME_UX_PROFILE);
