/**
 * Auto-generated runtime-ux profile for BM-116.
 *
 * Generated by: scripts/audit/generate-runtime-ux-profiles.mjs
 * Generator phase: 213-form input linkage, conservative template.
 *
 * This profile lifts BM-116 from FIDELITY_PENDING (generic
 * getSampleData fallback) to INPUT_CONNECTED_PARTIAL (route opens,
 * sections labelled, safe synthetic demo, no smart controls).
 *
 * Boundaries honoured here:
 *   - No mutation of the locked contract, the normalized DOCX, or
 *     the compiled contract.
 *   - No DB row creation, no generatedDocumentId fabrication.
 *   - No call to the generated-document save endpoint.
 *   - No smart controls emitted. Hand-curated smart controls are
 *     added by a separate, code-by-code promotion (see BM-001 /
 *     BM-171 for the reference shape).
 *   - No legacy stale tokens in demo (Nguyễn Văn A / Trần Thị B /
 *     1980 / Ông  cung cấp / Nguyễn Thị Hồng Hạnh).
 *
 * Promotion to INPUT_CONNECTED_PASS requires:
 *   - Hand-curated labels for the high-importance fields,
 *   - Smart controls only where evidence permits,
 *   - Golden-render + browser smoke evidence.
 *
 * See `QLLAW_FORM_INPUT_LINKAGE_CONTRACT.latest.md` for the contract
 * status codex.
 */

import {
  type RuntimeUxProfile,
  registerRuntimeUxProfile,
} from "./runtime-ux-profile";

const BM116_SECTIONS = [
  {
    sectionId: "section-thong-tin-bieu-mau",
    title: "Quyết định phục hồi điều tra vụ án hình sự",
    description:
      "Thông tin Viện kiểm sát, số quyết định, địa danh và ngày ban hành quyết định phục hồi điều tra vụ án.",
  },
] as const;

const BM116_PRESENTATION_SECTIONS = [
  {
    id: "decision-header",
    title: "Quyết định phục hồi điều tra vụ án hình sự",
    description: "Viện kiểm sát ban hành và số quyết định phục hồi điều tra vụ án.",
    fieldKeys: ["agency.vienKiem", "document.soQuyet"],
  },
  {
    id: "issue-line",
    title: "Địa danh và ngày ban hành",
    description: "Địa danh đặt trụ sở Viện kiểm sát và ngày ban hành quyết định.",
    fieldKeys: ["agency.diaDanh", "document.ngayBan"],
  },
] as const;

const BM116_FIELDS = {
  "agency.vienKiem": {
    label: "Viện kiểm sát ban hành quyết định",
    placeholder: "Nhập tên Viện kiểm sát ban hành",
  },
  "document.soQuyet": {
    label: "Số quyết định phục hồi điều tra vụ án",
    placeholder: "Ví dụ: 12/QĐ-VKS",
  },
  "agency.diaDanh": {
    label: "Địa danh ban hành quyết định",
    placeholder: "Nhập tỉnh hoặc thành phố nơi ban hành",
  },
  "document.ngayBan": {
    label: "Ngày ban hành quyết định",
    placeholder: "Nhập ngày ban hành quyết định",
    control: "DATE_TEXT",
  },
} as const;

const BM116_DEMO_RUNTIME_UX = {
  "agency.vienKiem": "Viện kiểm sát nhân dân khu vực 7",
  "document.soQuyet": "12/QĐ-VKSKV7",
  "agency.diaDanh": "Thành phố Hồ Chí Minh",
  "document.ngayBan": "15/07/2026",
} as const;

const BM116_RUNTIME_UX_PROFILE: RuntimeUxProfile = {
  templateCode: "BM-116",
  versionLabel: "BM-116 semantic-ui curated v1",
  sections: BM116_SECTIONS,
  presentationSections: BM116_PRESENTATION_SECTIONS,
  fields: BM116_FIELDS,
  demo: BM116_DEMO_RUNTIME_UX,
};

registerRuntimeUxProfile(BM116_RUNTIME_UX_PROFILE);
