/**
 * Auto-generated runtime-ux profile for BM-118.
 *
 * Generated by: scripts/audit/generate-runtime-ux-profiles.mjs
 * Generator phase: 213-form input linkage, conservative template.
 *
 * This profile lifts BM-118 from FIDELITY_PENDING (generic
 * getSampleData fallback) to INPUT_CONNECTED_PARTIAL (route opens,
 * sections labelled, safe synthetic demo, no smart controls).
 *
 * Boundaries honoured here:
 *   - No mutation of the locked contract, the normalized DOCX, or
 *     the compiled contract.
 *   - No DB row creation, no generatedDocumentId fabrication.
 *   - No call to the generated-document save endpoint.
 *   - No smart controls emitted. Hand-curated smart controls are
 *     added by a separate, code-by-code promotion (see BM-001 /
 *     BM-171 for the reference shape).
 *   - No legacy stale tokens in demo (Nguyễn Văn A / Trần Thị B /
 *     1980 / Ông  cung cấp / Nguyễn Thị Hồng Hạnh).
 *
 * Promotion to INPUT_CONNECTED_PASS requires:
 *   - Hand-curated labels for the high-importance fields,
 *   - Smart controls only where evidence permits,
 *   - Golden-render + browser smoke evidence.
 *
 * See `QLLAW_FORM_INPUT_LINKAGE_CONTRACT.latest.md` for the contract
 * status codex.
 */

import {
  type RuntimeUxProfile,
  registerRuntimeUxProfile,
} from "./runtime-ux-profile";

const BM118_SECTIONS = [
  {
    sectionId: "section-thong-tin-bieu-mau",
    title: "Thông tin quyết định và căn cứ",
  },
] as const;

const BM118_FIELDS = {
  "agency.vienKiem": {
    label: "Tên cơ quan",
    placeholder: "Tên cơ quan (mẫu BM-118)",
  },
  "document.soQuyet": {
    label: "Số quyết định",
    placeholder: "Số quyết định (mẫu BM-118)",
  },
  "agency.diaDanh": {
    label: "Địa danh",
    placeholder: "Địa danh (mẫu BM-118)",
  },
  "recipients.personLine": {
    label: "Người bị áp dụng",
    placeholder: "Người bị áp dụng (mẫu BM-118)",
  },
  "document.ngayBan": {
    label: "Ngày ban hành",
    placeholder: "Ngày ban hành (mẫu BM-118)",
  },
  "agency.dongDia": {
    label: "Dòng địa danh",
    placeholder: "Dòng địa danh (mẫu BM-118)",
  },
  "document.chuThe": {
    label: "Chủ thể liên quan",
    placeholder: "Chủ thể liên quan (mẫu BM-118)",
  },
  "document.tenVu": {
    label: "Tên vụ án / vụ việc",
    placeholder: "Tên vụ án / vụ việc (mẫu BM-118)",
  },
  "person.toiDanh": {
    label: "Tội danh",
    placeholder: "Tội danh (mẫu BM-118)",
  },
  "document.soQd": {
    label: "Số quyết định",
    placeholder: "Số quyết định (mẫu BM-118)",
  },
  "document.donVi": {
    label: "Đơn vị",
    placeholder: "Đơn vị (mẫu BM-118)",
  },
  "document.lyDo": {
    label: "Lý do",
    placeholder: "Lý do (mẫu BM-118)",
  },
} as const;

const BM118_DEMO_RUNTIME_UX = {
  "agency.vienKiem": "Viện kiểm sát nhân dân khu vực 7",
  "document.soQuyet": "12/QĐ-VKSKV7",
  "agency.diaDanh": "Thành phố Hồ Chí Minh",
  "recipients.personLine": "ông Lê Minh K, sinh năm 1992, trú tại phường Bến Nghé, Thành phố Hồ Chí Minh",
  "document.ngayBan": "15/07/2026",
  "agency.dongDia": "Thành phố Hồ Chí Minh, ngày 15 tháng 7 năm 2026",
  "document.chuThe": "bị can Lê Minh K",
  "document.tenVu": "vụ án Lạm dụng tín nhiệm chiếm đoạt tài sản",
  "person.toiDanh": "Lạm dụng tín nhiệm chiếm đoạt tài sản",
  "document.soQd": "05/QĐ-CQĐT",
  "document.donVi": "Cơ quan Cảnh sát điều tra Công an Thành phố Hồ Chí Minh",
  "document.lyDo": "cần tiếp tục xác minh tài liệu, chứng cứ liên quan",
} as const;

const BM118_RUNTIME_UX_PROFILE: RuntimeUxProfile = {
  templateCode: "BM-118",
  // Stable version label, surfaced in audit artifacts.
  versionLabel: `BM-118 runtime-ux batch 5 curated source-render profile`,
  sections: BM118_SECTIONS,
  fields: BM118_FIELDS,
  demo: BM118_DEMO_RUNTIME_UX,
};

registerRuntimeUxProfile(BM118_RUNTIME_UX_PROFILE);
