/**
 * Auto-generated runtime-ux profile for BM-117.
 *
 * Generated by: scripts/audit/generate-runtime-ux-profiles.mjs
 * Generator phase: 213-form input linkage, conservative template.
 *
 * This profile lifts BM-117 from FIDELITY_PENDING (generic
 * getSampleData fallback) to INPUT_CONNECTED_PARTIAL (route opens,
 * sections labelled, safe synthetic demo, no smart controls).
 *
 * Boundaries honoured here:
 *   - No mutation of the locked contract, the normalized DOCX, or
 *     the compiled contract.
 *   - No DB row creation, no generatedDocumentId fabrication.
 *   - No call to the generated-document save endpoint.
 *   - No smart controls emitted. Hand-curated smart controls are
 *     added by a separate, code-by-code promotion (see BM-001 /
 *     BM-171 for the reference shape).
 *   - No legacy stale tokens in demo (Nguyễn Văn A / Trần Thị B /
 *     1980 / Ông  cung cấp / Nguyễn Thị Hồng Hạnh).
 *
 * Promotion to INPUT_CONNECTED_PASS requires:
 *   - Hand-curated labels for the high-importance fields,
 *   - Smart controls only where evidence permits,
 *   - Golden-render + browser smoke evidence.
 *
 * See `QLLAW_FORM_INPUT_LINKAGE_CONTRACT.latest.md` for the contract
 * status codex.
 */

import {
  type RuntimeUxProfile,
  registerRuntimeUxProfile,
} from "./runtime-ux-profile";

const BM117_SECTIONS = [
  {
    sectionId: "section-thong-tin-bieu-mau",
    title: "Quyết định phục hồi điều tra bị can",
    description:
      "Căn cứ đình chỉ, lý do phục hồi, thông tin bị can và yêu cầu thi hành quyết định.",
  },
] as const;

const BM117_PRESENTATION_SECTIONS = [
  {
    id: "restoration-basis",
    title: "Căn cứ và lý do phục hồi điều tra bị can",
    description:
      "Viện kiểm sát ban hành, đối tượng trong Quyết định đình chỉ điều tra bị can và nội dung sau dòng “Xét thấy”.",
    fieldKeys: ["agency.vienKiem", "document.soQuyet", "agency.diaDanh"],
  },
  {
    id: "accused-details",
    title: "Bị can được phục hồi điều tra",
    description:
      "Các ô trong khối họ tên, thông tin nhân thân và nơi cư trú tại Điều 1 của quyết định.",
    fieldKeys: [
      "recipients.personLine",
      "document.ngayBan",
      "agency.dongDia",
      "document.chuThe",
      "document.tenVu",
      "person.toiDanh",
      "document.soQd",
    ],
  },
  {
    id: "execution-and-signature",
    title: "Thi hành và ký quyết định",
    description:
      "Cơ quan, người có thẩm quyền điều tra, bên liên quan và chức danh người ký.",
    fieldKeys: ["document.ngayQd", "document.donVi"],
  },
] as const;

const BM117_FIELDS = {
  "agency.vienKiem": {
    label: "Viện kiểm sát ban hành quyết định",
    placeholder: "Nhập tên Viện kiểm sát ban hành",
  },
  "document.soQuyet": {
    label: "Người hoặc pháp nhân trong Quyết định đình chỉ điều tra bị can",
    placeholder: "Nhập họ tên người hoặc tên pháp nhân theo quyết định đình chỉ",
  },
  "agency.diaDanh": {
    label: "Lý do, căn cứ phục hồi điều tra bị can",
    placeholder: "Nhập nội dung theo dòng “Xét thấy” và hướng dẫn chú thích 9",
    control: "TEXTAREA",
  },
  "recipients.personLine": {
    label: "Họ tên bị can hoặc tên pháp nhân",
    placeholder: "Nhập theo dòng Họ tên tại Điều 1",
  },
  "document.ngayBan": {
    label: "Thông tin tiếp theo dòng họ tên",
    placeholder: "Nhập nội dung đúng vị trí tương ứng trong biểu mẫu",
  },
  "agency.dongDia": {
    label: "Thông tin nhân thân tiếp theo",
    placeholder: "Nhập nội dung đúng vị trí tương ứng trong biểu mẫu",
  },
  "document.chuThe": {
    label: "Thông tin nhân thân bổ sung",
    placeholder: "Nhập nội dung đúng vị trí tương ứng trong biểu mẫu",
  },
  "document.tenVu": {
    label: "Nơi thường trú - phần thứ nhất",
    placeholder: "Nhập phần thứ nhất của nơi thường trú",
  },
  "person.toiDanh": {
    label: "Nơi thường trú - phần tiếp theo",
    placeholder: "Nhập phần tiếp theo của nơi thường trú",
  },
  "document.soQd": {
    label: "Nơi tạm trú",
    placeholder: "Nhập nơi tạm trú của bị can",
  },
  "document.ngayQd": {
    label: "Cơ quan, người thi hành và bên liên quan",
    placeholder: "Nhập đối tượng nhận yêu cầu thi hành quyết định",
  },
  "document.donVi": {
    label: "Chức danh người ký",
    placeholder: "Nhập chức danh người ký quyết định",
  },
} as const;

const BM117_DEMO_RUNTIME_UX = {
  "agency.vienKiem": "Viện kiểm sát nhân dân khu vực 7",
  "document.soQuyet": "12/QĐ-VKSKV7",
  "agency.diaDanh": "Thành phố Hồ Chí Minh",
  "recipients.personLine": "ông Lê Minh K, sinh năm 1992, trú tại phường Bến Nghé, Thành phố Hồ Chí Minh",
  "document.ngayBan": "15/07/2026",
  "agency.dongDia": "Thành phố Hồ Chí Minh, ngày 15 tháng 7 năm 2026",
  "document.chuThe": "bị can Lê Minh K",
  "document.tenVu": "vụ án Lạm dụng tín nhiệm chiếm đoạt tài sản",
  "person.toiDanh": "Lạm dụng tín nhiệm chiếm đoạt tài sản",
  "document.soQd": "05/QĐ-CQĐT",
  "document.ngayQd": "10/07/2026",
  "document.donVi": "Cơ quan Cảnh sát điều tra Công an Thành phố Hồ Chí Minh",
} as const;

const BM117_RUNTIME_UX_PROFILE: RuntimeUxProfile = {
  templateCode: "BM-117",
  versionLabel: "BM-117 semantic-ui curated v1",
  sections: BM117_SECTIONS,
  presentationSections: BM117_PRESENTATION_SECTIONS,
  fields: BM117_FIELDS,
  demo: BM117_DEMO_RUNTIME_UX,
};

registerRuntimeUxProfile(BM117_RUNTIME_UX_PROFILE);
