/**
 * BM-183 runtime-ux remaining curated source-render profile.
 *
 * Generated by: scripts/audit/generate-runtime-ux-profiles.mjs
 * Generator phase: 213-form input linkage, conservative template.
 *
 * This profile lifts BM-183 from FIDELITY_PENDING (generic
 * getSampleData fallback) to INPUT_CONNECTED_PARTIAL (route opens,
 * sections labelled, safe synthetic demo, no smart controls).
 *
 * Boundaries honoured here:
 *   - No mutation of the locked contract, the normalized DOCX, or
 *     the compiled contract.
 *   - No DB row creation, no generatedDocumentId fabrication.
 *   - No call to the generated-document save endpoint.
 *   - No smart controls emitted. Hand-curated smart controls are
 *     added by a separate, code-by-code promotion (see BM-001 /
 *     BM-171 for the reference shape).
 *   - No legacy stale tokens in demo (Nguyễn Văn A / Trần Thị B /
 *     1980 / Ông  cung cấp / Nguyễn Thị Hồng Hạnh).
 *
 * Promotion to INPUT_CONNECTED_PASS requires:
 *   - Hand-curated labels for the high-importance fields,
 *   - Smart controls only where evidence permits,
 *   - Golden-render + browser smoke evidence.
 *
 * See `QLLAW_FORM_INPUT_LINKAGE_CONTRACT.latest.md` for the contract
 * status codex.
 */

import {
  type RuntimeUxProfile,
  registerRuntimeUxProfile,
} from "./runtime-ux-profile";

const BM183_SECTIONS = [
  {
    sectionId: "section-thong-tin-bieu-mau",
    title: "Thông tin quyết định truy tố rút gọn",
    description: "Thông tin cơ quan, bị can, căn cứ pháp luật và nội dung quyết định truy tố theo thủ tục rút gọn.",
  },
] as const;

const BM183_FIELDS = {
  "agency.name": {
    label: "Tên Viện kiểm sát ban hành",
    placeholder: "Ghi tên Viện kiểm sát ban hành",
  },
  "person.dateOfBirth": {
    label: "Ngày sinh",
    placeholder: "Ghi ngày, tháng, năm sinh của bị can",
  },
  "person.personFullName": {
    label: "Họ và tên",
    placeholder: "Ghi họ tên bị can bị truy tố",
  },
  "legalBasis.statuteReference": {
    label: "Điểm, khoản, điều truy tố",
    placeholder: "Ghi điểm, khoản, điều của Bộ luật Hình sự",
  },
  "document.contentLine": {
    label: "Nội dung quyết định truy tố",
    placeholder: "Ghi nội dung truy tố theo khoản 2 Điều 461 Bộ luật Tố tụng hình sự",
  },
  "legalBasis.legalBasisLine2": {
    label: "Căn cứ quyết định đề nghị truy tố",
    placeholder: "Ghi quyết định đề nghị truy tố và cơ quan ban hành",
  },
  "legalBasis.legalBasisLine": {
    label: "Căn cứ áp dụng thủ tục rút gọn",
    placeholder: "Ghi quyết định áp dụng thủ tục rút gọn và cơ quan ban hành",
  },
  "document.issueDate": {
    label: "Ngày ban hành",
    placeholder: "Ngày, tháng, năm ban hành quyết định truy tố",
  },
  "document.fullDocumentCode": {
    label: "Số quyết định truy tố rút gọn",
    placeholder: ".../QĐ-VKS",
  },
} as const;

const BM183_DEMO_RUNTIME_UX = {} as const;

const BM183_RUNTIME_UX_PROFILE: RuntimeUxProfile = {
  templateCode: "BM-183",
  // Stable version label, surfaced in audit artifacts.
  versionLabel: `BM-183 runtime-ux remaining curated source-render profile`,
  sections: BM183_SECTIONS,
  fields: BM183_FIELDS,
  demo: BM183_DEMO_RUNTIME_UX,
};

registerRuntimeUxProfile(BM183_RUNTIME_UX_PROFILE);
