/**
 * BM-184 runtime-ux remaining curated source-render profile.
 *
 * Generated by: scripts/audit/generate-runtime-ux-profiles.mjs
 * Generator phase: 213-form input linkage, conservative template.
 *
 * This profile lifts BM-184 from FIDELITY_PENDING (generic
 * getSampleData fallback) to INPUT_CONNECTED_PARTIAL (route opens,
 * sections labelled, safe synthetic demo, no smart controls).
 *
 * Boundaries honoured here:
 *   - No mutation of the locked contract, the normalized DOCX, or
 *     the compiled contract.
 *   - No DB row creation, no generatedDocumentId fabrication.
 *   - No call to the generated-document save endpoint.
 *   - No smart controls emitted. Hand-curated smart controls are
 *     added by a separate, code-by-code promotion (see BM-001 /
 *     BM-171 for the reference shape).
 *   - No legacy stale tokens in demo (Nguyễn Văn A / Trần Thị B /
 *     1980 / Ông  cung cấp / Nguyễn Thị Hồng Hạnh).
 *
 * Promotion to INPUT_CONNECTED_PASS requires:
 *   - Hand-curated labels for the high-importance fields,
 *   - Smart controls only where evidence permits,
 *   - Golden-render + browser smoke evidence.
 *
 * See `QLLAW_FORM_INPUT_LINKAGE_CONTRACT.latest.md` for the contract
 * status codex.
 */

import {
  type RuntimeUxProfile,
  registerRuntimeUxProfile,
} from "./runtime-ux-profile";

const BM184_SECTIONS = [
  {
    sectionId: "section-thong-tin-bieu-mau",
    title: "Thông tin biểu mẫu",
  },
] as const;

const BM184_FIELDS = {
  "agency.name": {
    label: "Tên cơ quan",
    placeholder: "Tên cơ quan ",
  },
  "decision.decisionLine": {
    label: "Nội dung quyết định",
    placeholder: "Nội dung quyết định ",
  },
  "decision.decisionLine4": {
    label: "Cơ quan ra quyết định (dòng 4)",
    placeholder: "Cơ quan ra quyết định (dòng 4) ",
  },
  "document.summaryLine": {
    label: "Tóm tắt / liệt kê (dòng)",
    placeholder: "Tóm tắt / liệt kê (dòng) ",
  },
  "person.occupation": {
    label: "Nghề nghiệp",
    placeholder: "Nghề nghiệp ",
  },
  "decision.decisionLine3": {
    label: "Cơ quan ra quyết định (dòng 3)",
    placeholder: "Cơ quan ra quyết định (dòng 3) ",
  },
  "decision.decisionLine2": {
    label: "Cơ quan ra quyết định (dòng 2)",
    placeholder: "Cơ quan ra quyết định (dòng 2) ",
  },
  "person.currentAddress": {
    label: "Địa chỉ thường trú",
    placeholder: "Địa chỉ thường trú ",
  },
  "person.dateOfBirth": {
    label: "Ngày sinh",
    placeholder: "Ngày sinh ",
  },
  "person.personFullName": {
    label: "Họ và tên",
    placeholder: "Họ và tên ",
  },
  "document.issuePlace": {
    label: "Nơi ban hành",
    placeholder: "Địa điểm , ngày 04 tháng 3 năm 2026",
  },
  "document.issueDate": {
    label: "Ngày ban hành",
    placeholder: "Địa điểm , ngày 04 tháng 3 năm 2026",
  },
  "document.fullDocumentCode": {
    label: "Số văn bản / quyết định",
    placeholder: "Số văn bản / quyết định ",
  },
} as const;

const BM184_DEMO_RUNTIME_UX = {
  "agency.name": "Tên cơ quan ",
  "decision.decisionLine": "Nội dung quyết định ",
  "decision.decisionLine4": "Cơ quan ra quyết định (dòng 4) ",
  "document.summaryLine": "Tóm tắt / liệt kê (dòng) ",
  "person.occupation": "Nghề nghiệp ",
  "decision.decisionLine3": "Cơ quan ra quyết định (dòng 3) ",
  "decision.decisionLine2": "Cơ quan ra quyết định (dòng 2) ",
  "person.currentAddress": "Địa chỉ thường trú ",
  "person.dateOfBirth": "Ngày sinh ",
  "person.personFullName": "Họ và tên ",
  "document.issuePlace": "Địa điểm , ngày 04 tháng 3 năm 2026",
  "document.issueDate": "Địa điểm , ngày 04 tháng 3 năm 2026",
  "document.fullDocumentCode": "Số văn bản / quyết định ",
} as const;

const BM184_RUNTIME_UX_PROFILE: RuntimeUxProfile = {
  templateCode: "BM-184",
  // Stable version label, surfaced in audit artifacts.
  versionLabel: `BM-184 runtime-ux remaining curated source-render profile`,
  sections: BM184_SECTIONS,
  fields: BM184_FIELDS,
  demo: BM184_DEMO_RUNTIME_UX,
};

registerRuntimeUxProfile(BM184_RUNTIME_UX_PROFILE);
