/**
 * BM-182 runtime-ux remaining curated source-render profile.
 *
 * Generated by: scripts/audit/generate-runtime-ux-profiles.mjs
 * Generator phase: 213-form input linkage, conservative template.
 *
 * This profile lifts BM-182 from FIDELITY_PENDING (generic
 * getSampleData fallback) to INPUT_CONNECTED_PARTIAL (route opens,
 * sections labelled, safe synthetic demo, no smart controls).
 *
 * Boundaries honoured here:
 *   - No mutation of the locked contract, the normalized DOCX, or
 *     the compiled contract.
 *   - No DB row creation, no generatedDocumentId fabrication.
 *   - No call to the generated-document save endpoint.
 *   - No smart controls emitted. Hand-curated smart controls are
 *     added by a separate, code-by-code promotion (see BM-001 /
 *     BM-171 for the reference shape).
 *   - No legacy stale tokens in demo (Nguyễn Văn A / Trần Thị B /
 *     1980 / Ông  cung cấp / Nguyễn Thị Hồng Hạnh).
 *
 * Promotion to INPUT_CONNECTED_PASS requires:
 *   - Hand-curated labels for the high-importance fields,
 *   - Smart controls only where evidence permits,
 *   - Golden-render + browser smoke evidence.
 *
 * See `QLLAW_FORM_INPUT_LINKAGE_CONTRACT.latest.md` for the contract
 * status codex.
 */

import {
  type RuntimeUxProfile,
  registerRuntimeUxProfile,
} from "./runtime-ux-profile";

const BM182_SECTIONS = [
  {
    sectionId: "section-thong-tin-bieu-mau",
    title: "Thông tin quyết định hủy bỏ thủ tục rút gọn",
    description: "Cơ quan ban hành, ngày và số quyết định hủy bỏ quyết định áp dụng thủ tục rút gọn.",
  },
] as const;

const BM182_FIELDS = {
  "agency.name": {
    label: "Tên Viện kiểm sát ban hành",
    placeholder: "Ghi tên Viện kiểm sát ban hành",
  },
  "document.issueDate": {
    label: "Ngày ban hành",
    placeholder: "Ngày, tháng, năm ban hành quyết định",
  },
  "document.fullDocumentCode": {
    label: "Số quyết định hủy bỏ thủ tục rút gọn",
    placeholder: ".../QĐ-VKS",
  },
} as const;

const BM182_DEMO_RUNTIME_UX = {} as const;

const BM182_RUNTIME_UX_PROFILE: RuntimeUxProfile = {
  templateCode: "BM-182",
  // Stable version label, surfaced in audit artifacts.
  versionLabel: `BM-182 runtime-ux remaining curated source-render profile`,
  sections: BM182_SECTIONS,
  fields: BM182_FIELDS,
  demo: BM182_DEMO_RUNTIME_UX,
};

registerRuntimeUxProfile(BM182_RUNTIME_UX_PROFILE);
