/**
 * BM-183 runtime-ux remaining curated source-render profile.
 *
 * Generated by: scripts/audit/generate-runtime-ux-profiles.mjs
 * Generator phase: 213-form input linkage, conservative template.
 *
 * This profile lifts BM-183 from FIDELITY_PENDING (generic
 * getSampleData fallback) to INPUT_CONNECTED_PARTIAL (route opens,
 * sections labelled, safe synthetic demo, no smart controls).
 *
 * Boundaries honoured here:
 *   - No mutation of the locked contract, the normalized DOCX, or
 *     the compiled contract.
 *   - No DB row creation, no generatedDocumentId fabrication.
 *   - No call to the generated-document save endpoint.
 *   - No smart controls emitted. Hand-curated smart controls are
 *     added by a separate, code-by-code promotion (see BM-001 /
 *     BM-171 for the reference shape).
 *   - No legacy stale tokens in demo (Nguyễn Văn A / Trần Thị B /
 *     1980 / Ông  cung cấp / Nguyễn Thị Hồng Hạnh).
 *
 * Promotion to INPUT_CONNECTED_PASS requires:
 *   - Hand-curated labels for the high-importance fields,
 *   - Smart controls only where evidence permits,
 *   - Golden-render + browser smoke evidence.
 *
 * See `QLLAW_FORM_INPUT_LINKAGE_CONTRACT.latest.md` for the contract
 * status codex.
 */

import {
  type RuntimeUxProfile,
  registerRuntimeUxProfile,
} from "./runtime-ux-profile";

const BM183_SECTIONS = [
  {
    sectionId: "section-thong-tin-bieu-mau",
    title: "Thông tin biểu mẫu",
  },
] as const;

const BM183_FIELDS = {
  "agency.name": {
    label: "Tên cơ quan",
    placeholder: "Tên cơ quan ",
  },
  "person.dateOfBirth": {
    label: "Ngày sinh",
    placeholder: "Ngày sinh ",
  },
  "person.personFullName": {
    label: "Họ và tên",
    placeholder: "Họ và tên ",
  },
  "legalBasis.statuteReference": {
    label: "Điều luật tham chiếu",
    placeholder: "Điều luật tham chiếu ",
  },
  "document.contentLine": {
    label: "Nội dung (dòng)",
    placeholder: "Nội dung (dòng) ",
  },
  "legalBasis.legalBasisLine2": {
    label: "Căn cứ pháp luật (dòng 2)",
    placeholder: "Căn cứ pháp luật (dòng 2) ",
  },
  "legalBasis.legalBasisLine": {
    label: "Căn cứ pháp luật (dòng)",
    placeholder: "Căn cứ pháp luật (dòng) ",
  },
  "document.issueDate": {
    label: "Ngày ban hành",
    placeholder: "Địa điểm , ngày 04 tháng 3 năm 2026",
  },
  "document.fullDocumentCode": {
    label: "Số văn bản / quyết định",
    placeholder: "Số văn bản / quyết định ",
  },
} as const;

const BM183_DEMO_RUNTIME_UX = {
  "agency.name": "Tên cơ quan ",
  "person.dateOfBirth": "Ngày sinh ",
  "person.personFullName": "Họ và tên ",
  "legalBasis.statuteReference": "Điều luật tham chiếu ",
  "document.contentLine": "Nội dung (dòng) ",
  "legalBasis.legalBasisLine2": "Căn cứ pháp luật (dòng 2) ",
  "legalBasis.legalBasisLine": "Căn cứ pháp luật (dòng) ",
  "document.issueDate": "Địa điểm , ngày 04 tháng 3 năm 2026",
  "document.fullDocumentCode": "Số văn bản / quyết định ",
} as const;

const BM183_RUNTIME_UX_PROFILE: RuntimeUxProfile = {
  templateCode: "BM-183",
  // Stable version label, surfaced in audit artifacts.
  versionLabel: `BM-183 runtime-ux remaining curated source-render profile`,
  sections: BM183_SECTIONS,
  fields: BM183_FIELDS,
  demo: BM183_DEMO_RUNTIME_UX,
};

registerRuntimeUxProfile(BM183_RUNTIME_UX_PROFILE);
