/**
 * BM-201 runtime-ux remaining curated source-render profile.
 *
 * Generated by: scripts/audit/generate-runtime-ux-profiles.mjs
 * Generator phase: 213-form input linkage, conservative template.
 *
 * This profile lifts BM-201 from FIDELITY_PENDING (generic
 * getSampleData fallback) to INPUT_CONNECTED_PARTIAL (route opens,
 * sections labelled, safe synthetic demo, no smart controls).
 *
 * Boundaries honoured here:
 *   - No mutation of the locked contract, the normalized DOCX, or
 *     the compiled contract.
 *   - No DB row creation, no generatedDocumentId fabrication.
 *   - No call to the generated-document save endpoint.
 *   - No smart controls emitted. Hand-curated smart controls are
 *     added by a separate, code-by-code promotion (see BM-001 /
 *     BM-171 for the reference shape).
 *   - No legacy stale tokens in demo (Nguyễn Văn A / Trần Thị B /
 *     1980 / Ông  cung cấp / Nguyễn Thị Hồng Hạnh).
 *
 * Promotion to INPUT_CONNECTED_PASS requires:
 *   - Hand-curated labels for the high-importance fields,
 *   - Smart controls only where evidence permits,
 *   - Golden-render + browser smoke evidence.
 *
 * See `QLLAW_FORM_INPUT_LINKAGE_CONTRACT.latest.md` for the contract
 * status codex.
 */

import {
  type RuntimeUxProfile,
  registerRuntimeUxProfile,
} from "./runtime-ux-profile";

const BM201_SECTIONS = [
  {
    sectionId: "section-thong-tin-bieu-mau",
    title: "Thông tin biểu mẫu",
  },
] as const;

const BM201_FIELDS = {
  "agency.name": {
    label: "Tên cơ quan",
    placeholder: "Tên cơ quan ",
  },
  "recipients.personLine": {
    label: "Người bị áp dụng",
    placeholder: "Người bị áp dụng ",
  },
  "recipients.personLine14": {
    label: "Người nhận (dòng 14)",
    placeholder: "Người nhận (dòng 14) ",
  },
  "recipients.personLine13": {
    label: "Người nhận (dòng 13)",
    placeholder: "Người nhận (dòng 13) ",
  },
  "recipients.personLine12": {
    label: "Người nhận (dòng 12)",
    placeholder: "Người nhận (dòng 12) ",
  },
  "document.issueDate": {
    label: "Ngày ban hành",
    placeholder: "Địa điểm , ngày 04 tháng 3 năm 2026",
  },
  "recipients.personLine11": {
    label: "Người nhận (dòng 11)",
    placeholder: "Người nhận (dòng 11) ",
  },
  "recipients.personLine10": {
    label: "Người nhận (dòng 10)",
    placeholder: "Người nhận (dòng 10) ",
  },
  "recipients.personLine9": {
    label: "Người nhận (dòng 9)",
    placeholder: "Người nhận (dòng 9) ",
  },
  "recipients.personLine8": {
    label: "Người nhận (dòng 8)",
    placeholder: "Người nhận (dòng 8) ",
  },
  "recipients.personLine7": {
    label: "Người nhận (dòng 7)",
    placeholder: "Người nhận (dòng 7) ",
  },
  "recipients.personLine6": {
    label: "Người nhận (dòng 6)",
    placeholder: "Người nhận (dòng 6) ",
  },
  "recipients.personLine5": {
    label: "Người nhận (dòng 5)",
    placeholder: "Người nhận (dòng 5) ",
  },
  "recipients.personLine4": {
    label: "Người nhận (dòng 4)",
    placeholder: "Người nhận (dòng 4) ",
  },
  "recipients.personLine3": {
    label: "Người nhận (dòng 3)",
    placeholder: "Người nhận (dòng 3) ",
  },
  "recipients.personLine2": {
    label: "Người nhận (dòng 2)",
    placeholder: "Người nhận (dòng 2) ",
  },
  "document.fullDocumentCode": {
    label: "Số văn bản / quyết định",
    placeholder: "Số văn bản / quyết định ",
  },
} as const;

const BM201_DEMO_RUNTIME_UX = {
  "agency.name": "Tên cơ quan ",
  "recipients.personLine": "Người bị áp dụng ",
  "recipients.personLine14": "Người nhận (dòng 14) ",
  "recipients.personLine13": "Người nhận (dòng 13) ",
  "recipients.personLine12": "Người nhận (dòng 12) ",
  "document.issueDate": "Địa điểm , ngày 04 tháng 3 năm 2026",
  "recipients.personLine11": "Người nhận (dòng 11) ",
  "recipients.personLine10": "Người nhận (dòng 10) ",
  "recipients.personLine9": "Người nhận (dòng 9) ",
  "recipients.personLine8": "Người nhận (dòng 8) ",
  "recipients.personLine7": "Người nhận (dòng 7) ",
  "recipients.personLine6": "Người nhận (dòng 6) ",
  "recipients.personLine5": "Người nhận (dòng 5) ",
  "recipients.personLine4": "Người nhận (dòng 4) ",
  "recipients.personLine3": "Người nhận (dòng 3) ",
  "recipients.personLine2": "Người nhận (dòng 2) ",
  "document.fullDocumentCode": "Số văn bản / quyết định ",
} as const;

const BM201_RUNTIME_UX_PROFILE: RuntimeUxProfile = {
  templateCode: "BM-201",
  // Stable version label, surfaced in audit artifacts.
  versionLabel: `BM-201 runtime-ux remaining curated source-render profile`,
  sections: BM201_SECTIONS,
  fields: BM201_FIELDS,
  demo: BM201_DEMO_RUNTIME_UX,
};

registerRuntimeUxProfile(BM201_RUNTIME_UX_PROFILE);
